/* ML Academy · KONU ANLATIMI (Türkçe)
   Her ders adımında, modele dokunmadan ÖNCE okunacak metin. Amaç: kavramı
   insana anlatmak. Model ve grafik bu anlatımın kanıtı olarak gelir, tersi değil.
   Anahtar: 'dersId:adimNo'  (adım numarası 1'den başlar)
   İngilizcesi anlatim-en.js içinde, aynı anahtarlarla.                        */
var ANLATIM = {
  'veri:1': '<p>Makine öğrenmesi bir tabloyla başlar. Kulağa sıradan geliyor ama bütün alanın temeli burada: <b>modele dünyayı tablo olarak gösteririz</b>. Ne kadar karmaşık olursa olsun, bir problem bu biçime sokulamıyorsa model onu göremez.</p><p>Tablonun iki yönü var ve ikisi farklı şey söyler. <b>Satırlar</b> kimi ölçtüğümüzü, <b>sütunlar</b> ne ölçtüğümüzü anlatır. Bir öğrenci tablosunda her satır bir öğrenci, her sütun o öğrenci hakkında bir bilgi parçasıdır.</p><p>Bu ayrım önemsiz görünür ama bir modelin ne öğrenebileceğini doğrudan belirler. Model satırlar arasındaki <b>düzeni</b> arar: "şu sütun büyükken şu sütun da büyüyor mu?" Sorunun sorulabilmesi için önce tablonun düzgün kurulması gerekir.</p>',
  'veri:2': '<p>Bir tablonun sütunları eşit değildir. Bazıları modele <b>verdiğimiz</b> bilgidir, biri ise modelden <b>istediğimiz</b> cevaptır.</p><p>Verdiklerimize <b>özellik</b> (feature) denir ve genelde x ile gösterilir. İstediğimize <b>etiket</b> (label) denir, y ile gösterilir. Bir evin fiyatını tahmin ediyorsan metrekare, oda sayısı ve semt özelliktir; fiyat etikettir.</p><p>Bu ayrımı yapan sensin, veri değil. Aynı tabloyu farklı bir soruyla ele alsan başka bir sütun etiket olurdu. Yani <b>etiket, verinin bir özelliği değil, sorunun bir özelliğidir</b>.</p><p>Ve kritik nokta şu: etiket, tahmin anında <b>elinde olmayan</b> şeydir. Elindeyse ortada tahmin edilecek bir şey yoktur. Bu cümle basit görünüyor ama ileride "veri sızıntısı" dersinde bütün bir hata sınıfının kaynağı olacak.</p>',
  'veri:3': '<p>Sütunlar neyi ölçtüğümüzü söylüyordu. <b>Satırlar kimi ölçtüğümüzü</b> söyler. Her satır tek bir gözlemdir: bir öğrenci, bir işlem, bir hasta, bir fotoğraf.</p><p>Model tek bir satırdan öğrenemez. Bir satır sadece "bu öğrenci 6 saat çalıştı ve 66 aldı" der; bu bir olgudur, kural değil. Kural ancak <b>çok sayıda satıra birden</b> bakınca ortaya çıkar: "çalışma saati arttıkça puan artıyor."</p><p>Bu yüzden veri kümesinin büyüklüğü tesadüfi bir ayrıntı değil. Her yeni satır, aranan kuralın üstündeki gürültüyü biraz daha siler. On satırla bulduğun eğilim şansa bağlı olabilir; bin satırla bulduğun büyük ihtimalle gerçektir.</p>',
  'veri:4': '<p>Tablo doğru bir gösterim ama insan gözü için kötü bir gösterimdir. On satırlık bir tabloya bakıp ilişkiyi göremezsin; aynı on satırı grafiğe koyunca ilişki bir bakışta görünür.</p><p>Dönüşüm basit: <b>her satır bir nokta olur</b>. Bir özelliği yatay eksene, etiketi dikey eksene koyarsın. Artık "çalışma saati arttıkça puan artıyor" cümlesi bir cümle değil, ekrandaki bir <b>yükseliş</b>tir.</p><p>Bu kurs boyunca gördüğün hemen her grafik bu dönüşümün üstüne kurulu. Model de aslında aynı şeyi yapar: noktalara bakar ve aralarından geçen bir kural arar.</p>',
  'veri:5': '<p>"Model" kelimesi günlük dilde bulanıktır. Makine öğrenmesinde tanımı çok dardır: <b>model, girdiyi çıktıya çeviren bir fonksiyondur.</b> İçinde ayarlanabilir birkaç sayı vardır ve öğrenmek, o sayıları ayarlamaktır.</p><p>En basit hâliyle bir doğru: <code>y = w·x + b</code>. Burada x girdidir, y tahmindir, <b>w ve b modelin bilgisidir</b>. Model "öğrendi" demek, w ve b sayılarının veriye uyacak şekilde değiştiği demektir. Başka hiçbir sihir yok.</p><p>Dev bir dil modelinin de yapısı budur, sadece iki sayı yerine yüz milyarlarca sayı vardır. Bu yüzden "yapay zekâ nasıl öğreniyor" sorusunun cevabı her ölçekte aynıdır ve bir sonraki derste tam olarak onu göreceksin.</p>',

  'ezber:1': '<p>Bir modelin işe yarayıp yaramadığını nasıl anlarsın? İlk akla gelen cevap yanlıştır: "verdiğim veride doğru cevap veriyor mu?"</p><p>Bu ölçüt yanlıştır çünkü bir modelin veriyi <b>ezberlemesi</b> ile <b>anlaması</b> arasında ayrım yapamaz. Elindeki tabloyu olduğu gibi hafızasına yazan bir program da, aradaki kuralı bulan bir program da aynı veride kusursuz görünür.</p><p>Bu iki yaklaşım burada yan yana duruyor. Biri her öğrenciyi tek tek hatırlıyor, diğeri "çalışma saati arttıkça puan artıyor" kuralını çıkarıyor. İkisi de aynı veriye bakıyor ve ikisi de çalışıyor gibi görünüyor.</p><p>Aradaki farkı görebileceğin tek yer, ikisinin de <b>daha önce görmediği</b> bir öğrencidir. Bütün ders bunun üstüne kurulu.</p>',
  'ezber:2': '<p>Bir modeli öğrendiği veriyle sınamak, öğrenciye sınavda çalıştığı soruların aynısını sormaya benzer. Yüksek not alır ama o not bir şey kanıtlamaz.</p><p>Ezberleyen model bu sınavdan her zaman tam puan alır, çünkü sorulan her soruyu daha önce görmüş ve cevabını saklamıştır. Kural öğrenen model de yüksek puan alır ama tam puan almak zorunda değildir; kural her noktadan tam geçmeyebilir.</p><p>Buradaki ters durum önemli: <b>eğitim verisinde daha iyi görünen model, daha kötü model olabilir.</b> Çünkü mükemmel uyum çoğu zaman ezberin işaretidir, anlamanın değil.</p><p>Bu yüzden makine öğrenmesinde tek bir kural vardır ve istisnası yoktur: <b>modeli, öğrenirken görmediği veriyle sına.</b></p>',
  'ezber:3': '<p>Şimdi asıl soru: model daha önce hiç görmediği bir öğrenciye ne diyecek?</p><p>Ezberleyen modelin elinde o öğrenci yok. Yapabileceği tek şey en benzediği kaydı bulup onun cevabını vermek. Bu bazen tutar, çoğu zaman tutmaz; ve neden tuttuğunu ya da tutmadığını kimse açıklayamaz.</p><p>Kural öğrenen model ise formülü uygular. Yeni öğrenciyi hiç görmemiş olması sorun değil, çünkü bir <b>kural</b> öğrenmiştir, bir <b>liste</b> değil.</p><p>Bu farkın adı <b>genelleme</b>dir: görülmemiş veride doğru davranabilme yeteneği. Makine öğrenmesinde ölçmeye değer tek şey budur. Eğitim verisindeki başarı, bunun yanında hiçbir şey ifade etmez.</p>',
  'ezber:4': '<p>İki hatanın da standart bir adı var ve ikisi de tehlikeli.</p><p><b>Aşırı uyum (overfitting):</b> model veriyi fazla ciddiye almış, gürültüyü de kural sanmıştır. Eğitimde mükemmel, yeni veride kötüdür. Belirtisi net: eğitim hatası düşük, test hatası yüksek.</p><p><b>Yetersiz uyum (underfitting):</b> model veriyi hiç ciddiye almamıştır; kuralı yakalayacak kadar esnek değildir. Bu sefer hem eğitimde hem testte kötüdür.</p><p>Bu ikisi bir kadranın iki ucudur ve <b>ortada bir tatlı nokta vardır</b>. Kursun büyük bir kısmı, o noktayı bulmanın yollarını anlatır: ceza terimleri, çapraz doğrulama, erken durdurma. Hepsi aynı soruya cevap arar: model ne kadar esnek olmalı?</p>',
/*SON*/
};
