/* ML Academy · THE EXPOSITION (English)
   Same keys as anlatim.js: 'lessonId:stepNo'. Read before touching the model. */
var ANLATIM_EN = {
  'veri:1': '<p>Machine learning starts with a table. That sounds ordinary, but the whole field rests on it: <b>we show the world to a model as a table</b>. However complex a problem is, if it cannot be put into that shape the model cannot see it.</p><p>A table has two directions and they say different things. The <b>rows</b> tell you who was measured and the <b>columns</b> what was measured. In a table of students every row is a student and every column a piece of information about that student.</p><p>That distinction looks trivial but it directly determines what a model can learn. A model looks for a <b>pattern</b> across the rows: "when this column is large, is that one large too?" For the question to be askable at all, the table has to be built properly first.</p>',
  'veri:2': '<p>The columns of a table are not equal. Some are information we <b>give</b> the model and one is the answer we <b>ask</b> of it.</p><p>What we give is called a <b>feature</b> and is usually written x. What we ask for is called the <b>label</b>, written y. If you are predicting the price of a house, the floor area, the number of rooms and the district are features; the price is the label.</p><p>You make that split, not the data. Ask a different question of the same table and a different column becomes the label. So <b>the label is a property of the question, not of the data</b>.</p><p>And the critical point: the label is the thing you do <b>not</b> have at prediction time. If you have it there is nothing to predict. That sentence looks simple, but in the data leakage lesson it turns out to be the source of a whole class of errors.</p>',
  'veri:3': '<p>The columns told you what was measured. The <b>rows tell you who</b>. Every row is a single observation: one student, one transaction, one patient, one photograph.</p><p>A model cannot learn from a single row. One row only says "this student worked 6 hours and scored 66"; that is a fact, not a rule. A rule only appears when you look at <b>many rows at once</b>: "as study hours grow the score grows."</p><p>This is why the size of a dataset is not an incidental detail. Every new row wipes a little more noise off the rule you are looking for. A tendency found in ten rows may be luck; one found in a thousand is probably real.</p>',
  'veri:4': '<p>A table is a correct representation but a bad one for the human eye. Look at ten rows and you will not see the relationship; put the same ten rows on a plot and it appears at a glance.</p><p>The transformation is simple: <b>every row becomes a point</b>. You put a feature on the horizontal axis and the label on the vertical one. Now "as study hours grow the score grows" is no longer a sentence but a <b>rise</b> on your screen.</p><p>Almost every plot you see in this course rests on that transformation. And a model does the same thing: it looks at the points and searches for a rule that runs through them.</p>',
  'veri:5': '<p>The word "model" is vague in everyday speech. In machine learning its definition is very narrow: <b>a model is a function that turns an input into an output.</b> It contains a few adjustable numbers, and learning means adjusting them.</p><p>In its simplest form it is a line: <code>y = w·x + b</code>. Here x is the input, y the prediction and <b>w and b are the model\'s knowledge</b>. Saying the model "learned" means those two numbers changed to fit the data. There is no other magic.</p><p>A huge language model has the same structure; it just has hundreds of billions of numbers instead of two. This is why the answer to "how does AI learn" is the same at every scale, and the next lesson shows exactly that.</p>',

  'ezber:1': '<p>How do you tell whether a model works? The first answer that comes to mind is wrong: "does it give the right answer on the data I gave it?"</p><p>That criterion is wrong because it cannot tell <b>memorising</b> the data from <b>understanding</b> it. A program that writes your table into memory verbatim and a program that finds the underlying rule both look perfect on that data.</p><p>The two approaches sit side by side here. One remembers every student individually, the other extracts the rule "as study hours grow the score grows". Both look at the same data and both appear to work.</p><p>The only place you can see the difference is a student <b>neither of them has seen</b>. The whole lesson rests on that.</p>',
  'ezber:2': '<p>Testing a model on the data it learned from is like giving a student an exam made of exactly the questions they revised. They get a high mark, and the mark proves nothing.</p><p>A memorising model always gets full marks on that exam, because it has seen every question before and stored the answer. A rule learning model also scores highly, but it does not have to be perfect; a rule need not pass exactly through every point.</p><p>The inversion here matters: <b>the model that looks better on the training data can be the worse model.</b> Because a perfect fit is usually a sign of memorisation rather than understanding.</p><p>This is why machine learning has one rule with no exceptions: <b>test a model on data it did not see while learning.</b></p>',
  'ezber:3': '<p>Now the real question: what will the model say about a student it has never seen?</p><p>The memorising model does not have that student. All it can do is find the closest record it has and return that answer. Sometimes it works, mostly it does not, and nobody can explain why it did or did not.</p><p>The rule learning model applies its formula. Never having seen the new student is not a problem, because it learned a <b>rule</b>, not a <b>list</b>.</p><p>That difference has a name: <b>generalisation</b>, the ability to behave correctly on unseen data. It is the only thing worth measuring in machine learning. Success on the training data means nothing next to it.</p>',
  'ezber:4': '<p>Both failures have standard names and both are dangerous.</p><p><b>Overfitting:</b> the model took the data too seriously and mistook the noise for the rule. Perfect in training, bad on new data. The symptom is clear: a low training error and a high test error.</p><p><b>Underfitting:</b> the model did not take the data seriously at all; it is not flexible enough to catch the rule. This time it is bad in both training and testing.</p><p>These are the two ends of one dial, and <b>there is a sweet spot in the middle</b>. Much of this course is about ways of finding it: penalty terms, cross validation, early stopping. They all answer the same question: how flexible should the model be?</p>',
/*SON*/
};
