/* ML Academy · ders sayfasındaki DİNAMİK metinlerin sözlüğü (TR → EN)
   Bu metinler content.js'teki fonksiyonlardan üretilir (live sayaçları,
   unlockMsg, bodyFn, animasyon kareleri, kod laboratuvarı çıktısı), bu yüzden
   content-en.js onları geçersiz kılamaz. lesson.html'deki CEVIR() bu tabloyu
   kullanır; sayılar # ile temsil edilir.
   Eksikleri görmek için: node sozluk-eksik.js 200 0 arayuz   */
var ARAYUZ_EN = {
  "TUR": "PASS",
  "ADIM": "STEP",
  "DİZİ": "LIST",
  "TAKAS": "SWAPS",
  "EPOCH": "EPOCH",
  "KAYIP": "LOSS",
  "AŞAMA": "STAGE",
  "SIRALI": "SORTED",
  "ETİKET": "LABEL",
  "SIRASIZ": "UNSORTED",
  "PENCERE": "WINDOW",
  "İŞLENEN": "PROCESSED",
  "DOĞRULUK": "ACCURACY",
  "KARŞILAŞTIRMA": "COMPARISONS",
  "SOL": "LEFT",
  "SAĞ": "RIGHT",
  "BAŞ": "HEAD",
  "TÜR": "KIND",
  "kuş": "bird",
  "YOL": "PATH",
  "ACI": "ANGLE",
  "TAM": "FULL",
  "KAT": "FOLD",
  "PAY": "SHARE",
  "FARK": "GAP",
  "HATA": "ERROR",
  "ORAN": "RATIO",
  "KAPI": "GATE",
  "AĞAÇ": "TREE",
  "MARJ": "MARGIN",
  "UZAY": "SPACE",
  "HARF": "LETTER",
  "SIRA": "ORDER",
  "UYUM": "AGREEMENT",
  "CEZA": "PENALTY",
  "SKOR": "SCORE",
  "kedi": "cat",
  "ÖZET": "SUMMARY",
  "SAYI": "COUNT",
  "ÖRNEK": "EXAMPLES",
  "HEDEF": "TARGET",
  "DURUM": "STATE",
  "KALAN": "LEFT",
  "KARAR": "DECISION",
  "SORGU": "QUERY",
  "KAÇAN": "MISSED",
  "SONUÇ": "RESULT",
  "ERİME": "DECAY",
  "PARÇA": "CHUNK",
  "AYLIK": "MONTHLY",
  "BÜTÇE": "BUDGET",
  "köpek": "dog",
  "KOŞUL": "CONDITION",
  "TAVAN": "CEILING",
  "KÂHİN": "ORACLE",
  "GENEL": "OVERALL",
  "GOREV": "TASK",
  "AYRIM": "SEPARATION",
  "KANAL": "CHANNEL",
  "SISME": "INFLATION",
  "ARAMA": "SEARCH",
  "TABAN": "BASE RATE",
  "KENDI": "SELF",
  "KUCUK": "SMALL",
  "EN İYİ": "BEST",
  "DERECE": "DEGREE",
  "EĞİTİM": "TRAINING",
  "+ bias": "+ bias",
  "KAZANÇ": "GAIN",
  "YAPRAK": "LEAVES",
  "KELİME": "WORD",
  "İSABET": "HIT RATE",
  "SÖZLÜK": "VOCAB",
  "TOPLAM": "TOTAL",
  "İZİNLİ": "ALLOWED",
  "DÜRÜST": "HONEST",
  "ARALIK": "INTERVAL",
  "YILLIK": "YEARLY",
  "ZORLUK": "DIFFICULTY",
  "DENEME": "TRIALS",
  "YÖNTEM": "METHOD",
  "AÇILAN": "EXPANDED",
  "TAHMİN": "PREDICTION",
  "GERÇEK": "TRUTH",
  "YANLIŞ": "WRONG",
  "BASKIN": "DOMINANT",
  "TURKCE": "TURKISH",
  "SAFLIK": "PURITY",
  "GERCEK": "TRUE",
  "BELLEK": "MEMORY",
  "TENSOR": "TENSOR",
  "KAZANC": "GAIN",
  "KATMAN": "LAYER",
  "ISABET": "HIT RATE",
  "w_sag": "w_right",
  "ÇIKTI": "OUTPUT",
  "tahmin": "prediction",
  "<p>aşama # / #</p>": "<p>stage # / #</p>",
  "<p>Adım # · hata <b>#</b></p>": "<p>Step # · error <b>#</b></p>",
  "<p>x = # · sağ dal ağırlığı <b>#%</b> · tahmin <b>#</b></p>": "<p>x = # · right branch weight <b>#%</b> · prediction <b>#</b></p>",
  "<p style=\"color:#f#\"><b>Sayılar taştı.</b> Model öğrenmek yerine uzaklaşıyor.</p>": "<p style=\"color:#f#\"><b>The numbers overflowed.</b> Instead of learning, the model is moving away.</p>",
  "<p style=\"color:#f#\">x = # · ağırlık <b>#</b>, bu bir olasılık değil, kapı bozuk.</p>": "<p style=\"color:#f#\">x = # · weight <b>#</b>, that is not a probability, the gate is broken.</p>",
  "<p><b>Başlangıç. Hata <b>#</b>.</p>": "<p><b>Start. Error <b>#</b>.</p>",
  "<p>Başlangıç. Hata <b>#</b>.</p>": "<p>The start. Error <b>#</b>.</p>",
  "<p>Başlangıç: elimizde sadece sayılar var.</p>": "<p>The start: all we have is numbers.</p>",
  "<p>Dizi karışık. Algoritma soldan başlayacak.</p>": "<p>The list is unsorted. The algorithm will start from the left.</p>",
  "<p>İkisi de aynı soruyu arıyor: <b># nerede?</b></p>": "<p>Both are looking for the same thing: <b>where is #?</b></p>",
  "<p><b>Karşılaştır.</b> Soldaki sağdakinden büyük mü? Hayır, sıra doğru, geç.</p>": "<p><b>Compare.</b> Is the left one larger than the right? No, the order is correct, move on.</p>",
  "<p><b>İlk adımlar en büyük kazancı sağlar.</b> Eğim dik, adımlar uzun, hata hızla düşüyor.</p>": "<p><b>The first steps bring the biggest gain.</b> The slope is steep, the steps are long and the error falls fast.</p>",
  "<p><b>Yakınsadı.</b> w=#, b=#, matematiksel en iyiye (# / #) neredeyse eşit. Hata <b>#</b>.</p>": "<p><b>Converged.</b> w=#, b=#, almost exactly the mathematical optimum (# / #). Error <b>#</b>.</p>",
  "<p><b>Takas edildi.</b> Büyük değer bir adım sağa <b>kabardı</b>. Adı buradan geliyor: bubble.</p>": "<p><b>Swapped.</b> The larger value <b>bubbled</b> one step to the right. That is where the name comes from: bubble.</p>",
  "<p><b>Karşılaştır.</b> Soldaki sağdakinden büyük mü? <b style=\"color:#fb#c\">Evet, takas gerekiyor.</b></p>": "<p><b>Compare.</b> Is the left one larger than the right? <b style=\"color:#fb#c\">Yes, a swap is needed.</b></p>",
  "<p><b>Epoch #.</b> Kayıp #, doğruluk %#. Sınır şekilleniyor, ağ önce kaba bir ayrım, sonra çemberi buluyor.</p>": "<p><b>Epoch #.</b> Loss #, accuracy #%. The boundary is taking shape: the network first finds a rough split, then the circle.</p>",
  "<p>Her satır, yatay eksende <b>x</b> (saat), dikey eksende <b>y</b> (puan) olacak şekilde bir noktaya taşınıyor.</p>": "<p>Every row moves to a point with <b>x</b> (hours) on the horizontal axis and <b>y</b> (score) on the vertical one.</p>",
  "<p><b>Epoch #, rastgele ağırlıklar.</b> Karar sınırı anlamsız, doğruluk %#, yani yazı tura. Ağ hiçbir şey bilmiyor.</p>": "<p><b>Epoch #, random weights.</b> The decision boundary is meaningless and the accuracy #%, a coin flip. The network knows nothing.</p>",
  "<p><b>Bitti.</b> # karşılaştırma, # takas. Bilgisayar hiçbir noktada resmin tamamını görmedi, sadece komşu ikilileri karşılaştırdı.</p>": "<p><b>Done.</b> # comparisons, # swaps. At no point did the computer see the whole picture; it only compared neighbouring pairs.</p>",
  "<p>Filtre sol üst köşeden başlıyor. #×#'lük pencerenin altındaki # piksel, filtrenin # ağırlığıyla teker teker çarpılıp toplanıyor.</p>": "<p>The filter starts at the top left corner. The # pixels under the #×# window are multiplied one by one by the filter's # weights and summed.</p>",
  "<p>Sıralı dizi işini bitireli çok oldu. Sırasız dizi hâlâ tarıyor, <b>#. kutuda</b>. Elinde hiçbir ipucu yok, tek yapabildiği sırayla bakmak.</p>": "<p>The sorted list finished long ago. The unsorted one is still scanning, at <b>box #</b>. It has no clue to go on; all it can do is look in order.</p>",
  "<p><b style=\"color:##d#a#\">ADIM #, GÜNCELLE.</b> Her merkez, kendisine bağlanan noktaların <b>tam ortasına</b> taşındı. Atamalar hiç değişmedi.</p>": "<p><b style=\"color:##d#a#\">STEP #, UPDATE.</b> Every centre moved to the <b>exact middle</b> of the points attached to it. The assignments did not change at all.</p>",
  "<p><b style=\"color:##cc#ff\">ADIM #, ATA.</b> Her nokta, kendisine <b>en yakın</b> merkeze bağlandı ve onun rengini aldı. Merkezler hiç kımıldamadı.</p>": "<p><b style=\"color:##cc#ff\">STEP #, ASSIGN.</b> Every point attached itself to its <b>nearest</b> centre and took its colour. The centres did not move at all.</p>",
  "<p><b style=\"color:##d#a#\">Sıralı dizi ikinci kontrolde buldu.</b> Ortadaki sayıya baktı, hedef büyüktü, sol yarıyı tamamen eledi. Bir bakışta yarısını çöpe attı.</p>": "<p><b style=\"color:##d#a#\">The sorted list found it on the second check.</b> It looked at the middle number, the target was larger, and it eliminated the whole left half. It threw away half the list in one glance.</p>",
  "<p><b>Vadi tabanına inildi.</b> Eğim küçüldü, ilerleme yavaşladı, model sürünerek en iyiye yaklaşıyor. Momentum ve Adam gibi optimizerlar tam olarak bu yavaşlığı çözmek için icat edildi.</p>": "<p><b>The floor of the valley has been reached.</b> The slope shrank, progress slowed, and the model crawls towards the optimum. Optimisers like Momentum and Adam were invented to solve exactly this slowness.</p>",
  "<p><b>İşte veri budur.</b> Aynı bilgi, ama artık ilişkiyi <i>görüyorsun</i>: noktalar sağa doğru yükseliyor. Çalışma saati arttıkça puan artıyor.</p><p>Modelin işi bu yükselişi <b>sayısal bir kurala</b> çevirmek.</p>": "<p><b>This is what data is.</b> The same information, but now you <i>see</i> the relationship: the points rise towards the right. As study hours grow the score grows.</p><p>The model's job is to turn that rise into <b>a numerical rule</b>.</p>",
  "<p><b style=\"color:##d#a#\">ADIM #, GÜNCELLE.</b> Her merkez, kendisine bağlanan noktaların <b>tam ortasına</b> taşındı. Atamalar hiç değişmedi.</p><p>Merkezler artık kımıldamıyor, algoritma <b>yakınsadı</b>. Üç grup da doğru bulundu: # / # / #.</p>": "<p><b style=\"color:##d#a#\">STEP #, UPDATE.</b> Every centre moved to the <b>exact middle</b> of the points attached to it. The assignments did not change at all.</p><p>The centres no longer move: the algorithm has <b>converged</b>. All three groups were found correctly: # / # / #.</p>",
  "<p>Pencere bir adım kaydı. <b>Aynı # ağırlık</b> tekrar kullanılıyor, yeni parametre yok.</p><p>Bu filtre <b>dikey kenar</b> arıyor (Sobel). Solda açık, sağda koyu piksel varsa yüksek değer üretiyor. Yeşil = güçlü kenar, kırmızı = ters yönlü kenar.</p>": "<p>The window moved one step. The <b>same # weights</b> are used again; there are no new parameters.</p><p>This filter looks for a <b>vertical edge</b> (Sobel). If there is a light pixel on the left and a dark one on the right it produces a high value. Green = a strong edge, red = an edge in the opposite direction.</p>",
  "<p>Şimdiye kadarki bütün derslerde <b>doğru cevap</b> elimizdeydi: sınav puanı, geçti/kaldı, sınıf #/#. Buna <b>gözetimli öğrenme</b> denir.</p><p>Burada hiçbir etiket yok. Sadece noktalar. Yine de gözünle üç grup görüyorsun, model de bulabilir mi?</p><p># merkez (yıldız) bilerek kötü bir yere, sol alt köşeye kondu.</p>": "<p>In every lesson so far we had the <b>right answer</b>: the exam score, pass/fail, class #/#. That is called <b>supervised learning</b>.</p><p>Here there are no labels at all. Only points. And yet you see three groups with your eyes; can the model find them too?</p><p>The # centres (stars) were deliberately placed somewhere bad, in the bottom left corner.</p>",
  "<p><b style=\"color:##d#a#\">Epoch #, halkayı öğrendi.</b> Doğruluk %#, kayıp #.</p><p>Dikkat: karar sınırı bir <b>çember</b>. Hiçbir doğru bu veriyi ayıramaz, ağ bunu kendisi keşfetti. Gizli katmanlar sayesinde <b>doğrusal olmayan</b> sınırlar çizebiliyor.</p><p>Ağırlık çizgilerine bak: bazıları kalınlaştı (önemli bağlantılar), bazıları soldu (işe yaramazlar).</p>": "<p><b style=\"color:##d#a#\">Epoch #, it learned the ring.</b> Accuracy #%, loss #.</p><p>Note: the decision boundary is a <b>circle</b>. No straight line can separate this data, and the network discovered that by itself. Thanks to the hidden layers it can draw <b>non-linear</b> boundaries.</p><p>Look at the weight lines: some thickened (the important connections) and some faded (the useless ones).</p>",
  "<p><b>Tamamlandı.</b> #×# girdiden #×#'luk bir <b>özellik haritası</b> çıktı.</p><p>Haritada “#” rakamının dikey kenarları parlıyor. Filtre görüntüyü değil, <b>bir örüntünün nerede bulunduğunu</b> gösteriyor.</p><p>Gerçek bir CNN'de bu filtrelerden düzinelerce var ve <b>hepsi öğreniliyor</b>, ben Sobel'i elle yazdım ama ağ kendi filtrelerini gradient descent ile buluyor. İlk katmanlar kenar ve renk, orta katmanlar doku ve şekil, son katmanlar “kedi kulağı” gibi parçalar öğreniyor.</p>": "<p><b>Complete.</b> A #×# input produced a #×# <b>feature map</b>.</p><p>On the map the vertical edges of the digit “#” light up. The filter does not show the image but <b>where a pattern is located</b>.</p><p>A real CNN has dozens of these filters and <b>every one of them is learned</b>. I wrote Sobel by hand, but a network finds its own filters by gradient descent. The first layers learn edges and colour, the middle ones texture and shape, and the last ones parts such as “a cat's ear”.</p>",
  "<p><b>Sırasız: # kontrol. Sıralı: # kontrol.</b></p><p># elemanda fark küçük görünüyor. Ama sırasız arama <b>n</b>, ikili arama <b>log₂n</b> adım harcar:</p><p style=\"font-family:var(--mono);background:rgba(#,#,.#);padding:#px #px;border-radius:#px\"># eleman  →  #  vs  #<br>#.#     →  #.#  vs  #<br># milyar      →  # milyar  vs  #</p><p>Google'ın aramayı, veritabanlarının indeksi, öneri sistemlerinin “en iyi #” listesini bu kadar hızlı verebilmesinin sebebi bu. <b>Sıralama tek başına bir amaç değil, hızlı aramanın ön koşulu.</b></p>": "<p><b>Unsorted: # checks. Sorted: # checks.</b></p><p>With # elements the difference looks small. But an unsorted search spends <b>n</b> steps and a binary search <b>log₂n</b>:</p><p style=\"font-family:var(--mono);background:rgba(#,#,.#);padding:#px #px;border-radius:#px\"># elements  →  #  vs  #<br>#.#     →  #.#  vs  #<br># billion      →  # billion  vs  #</p><p>This is why Google can search, databases can index and recommender systems can produce a “top #” list so fast. <b>Sorting is not an end in itself but the precondition for fast search.</b></p>",
  "<p><b style=\"color:##d#a#\">Sağlıklı bölge.</b> # adımda hata #'e indi. Yeterince hızlı, yeterince kararlı.</p>": "<p><b style=\"color:##d#a#\">The healthy region.</b> In # steps the error fell to #. Fast enough and stable enough.</p>",
  "<p><b style=\"color:#facc#\">η çok küçük.</b> Yön doğru ama adımlar minicik. # adımda hâlâ hedefe varamadı. Gerçek hayatta bu, GPU'da boşa yanan günler demek.</p>": "<p><b style=\"color:#facc#\">η is too small.</b> The direction is right but the steps are tiny. After # steps it still has not reached the target. In real life that means days of GPU time burned for nothing.</p>",
  "<p><b style=\"color:#f#\">η çok büyük.</b> Her adım vadinin karşı yamacına, üstelik <b>daha yükseğe</b> fırlıyor. Değerler katlanarak büyüyor ve #. adımda sayısal olarak taşıyor. Ekranda <code>loss: nan</code> gördüğünde olan tam olarak budur.</p>": "<p><b style=\"color:#f#\">η is too large.</b> Every step leaps to the opposite slope of the valley, and <b>higher up</b> at that. The values grow by compounding and overflow numerically at step #. That is exactly what is happening when you see <code>loss: nan</code> on your screen.</p>",
  "gw = <span class=\"fn\">dL_dw</span>(w, b)         <span class=\"cm\"># w yönündeki eğim</span>": "gw = <span class=\"fn\">dL_dw</span>(w, b)         <span class=\"cm\"># the slope in the w direction</span>",
  "gb = <span class=\"fn\">dL_db</span>(w, b)         <span class=\"cm\"># b yönündeki eğim</span>": "gb = <span class=\"fn\">dL_db</span>(w, b)         <span class=\"cm\"># the slope in the b direction</span>",
  "lr = <span class=\"st\">#</span>                <span class=\"cm\"># öğrenme hızı (adım boyu)</span>": "lr = <span class=\"st\">#</span>                <span class=\"cm\"># learning rate (step size)</span>",
  "w, b = <span class=\"st\">#</span>, <span class=\"st\">#</span>        <span class=\"cm\"># şu anki model</span>": "w, b = <span class=\"st\">#</span>, <span class=\"st\">#</span>        <span class=\"cm\"># the current model</span>",
  "w = w <span class=\"op\">-</span> lr <span class=\"op\">*</span> gw          <span class=\"cm\"># eğimin TERSİNE, lr kadar</span>": "w = w <span class=\"op\">-</span> lr <span class=\"op\">*</span> gw          <span class=\"cm\"># AGAINST the slope, by lr</span>",
  "    <span class=\"kw\">for</span> tur <span class=\"kw\">in</span> <span class=\"fn\">range</span>(n - <span class=\"st\">#</span>):": "    <span class=\"kw\">for</span> p <span class=\"kw\">in</span> <span class=\"fn\">range</span>(n - <span class=\"st\">#</span>):",
  "        <span class=\"kw\">for</span> i <span class=\"kw\">in</span> <span class=\"fn\">range</span>(n - <span class=\"st\">#</span> - tur):": "        <span class=\"kw\">for</span> i <span class=\"kw\">in</span> <span class=\"fn\">range</span>(n - <span class=\"st\">#</span> - p):",
  "<b>x + t yazdın.</b> Kapı artık eşikte değil, x = −t civarında dönüyor. Eşiğin anlamı kayboldu: bütün örnekler aynı tarafa gidiyor.": "<b>You wrote x + t.</b> The gate no longer turns at the threshold but around x = −t. The threshold lost its meaning: every example goes to the same side.",
  "<b>Bias ile çarptın.</b> Bias sıfır olsaydı her şey sıfırlanırdı. Bias bir <i>kaydırma</i>dır: eşiği sağa sola oynatır, ölçeklemez.": "<b>You multiplied by the bias.</b> Had the bias been zero everything would have gone to zero. A bias is a <i>shift</i>: it moves the threshold left or right, it does not scale.",
  "<b>Böldün.</b> Adım boyu = öğrenme hızı <b>×</b> eğim. Bölünce lr=# iken adım # katına çıkıyor ve model her adımda vadiyi aşıp patlıyor.": "<b>You divided.</b> The step size = the learning rate <b>×</b> the slope. Dividing makes the step # times larger at lr=#, and the model overshoots the valley at every step and blows up.",
  "<b>step seçtin</b>, bu zaten sert kapının kendisi. Ağırlıklar yine %# / %# ve türev yine sıfır. Hiçbir şey değişmedi; ağaç hâlâ eğitilemez.": "<b>You picked step</b>, which is the hard gate itself. The weights are #% / #% again and the derivative is zero again. Nothing changed; the tree still cannot be trained.",
  "Hata <b># → #</b>. Model matematiksel en iyiye (#) ulaştı. <b>θ ← θ − η·∇L</b> satırını doğru kurdun, makine öğrenmesinin en önemli tek satırı bu.": "The error went <b># → #</b>. The model reached the mathematical optimum (#). You built the line <b>θ ← θ − η·∇L</b> correctly, and that is the single most important line in machine learning.",
  "<b>Son satır yanlış.</b> Bir katman, aynı işlemi <i>birçok</i> nöron için tekrarlar. Tek nöronlu bir katman, lojistik regresyondan başka bir şey değildir.": "<b>The last line is wrong.</b> A layer repeats the same operation for <i>many</i> neurons. A layer with a single neuron is nothing other than logistic regression.",
  "<b>round kullandın.</b> Çıktı basamak fonksiyonuna döndü ve türevi sıfır. neural-trees dersinde gördüğün sorunun aynısı: gradient descent bu nöronu eğitemez.": "<b>You used round.</b> The output turned into a step function and its derivative is zero. The same problem you saw in the neural-trees lesson: gradient descent cannot train this neuron.",
  "<b>T yerine x ile böldün.</b> Sıcaklık kapının keskinliğini ayarlayan parametre, x ile bölünce her örnek için farklı bir keskinlik oluyor ve kapı anlamsızlaşıyor.": "<b>You divided by x instead of T.</b> The temperature is the parameter that sets the sharpness of the gate; dividing by x gives a different sharpness for every example and the gate becomes meaningless.",
  "<b>abs kullandın.</b> Çıktı #, #'i aşıyor, olasılık olarak okunamaz. Ayrıca abs negatif ve pozitifi aynı yere gönderir; nöron “geçer” ile “kalır”ı ayırt edemez hâle gelir.": "<b>You used abs.</b> The output is # and exceeds #, so it cannot be read as a probability. And abs sends negative and positive to the same place; the neuron can no longer tell “pass” from “fail”.",
  "<b>+ koydun.</b> Eğim yokuş yukarıyı gösterir; artı koyunca model <i>tepeye tırmandı</i>. Buna gradient <b>ascent</b> denir ve hatayı büyütür. Kayıp fonksiyonunu küçültmek için eksi şart.": "<b>You put a +.</b> The slope points uphill; with a plus the model <i>climbed the hill</i>. That is called gradient <b>ascent</b> and it grows the error. A minus is mandatory to reduce a loss function.",
  "<b>ReLU türevlenebilir ama sınırsız.</b> Çıktısı #'i aşabiliyor, gördüğün gibi \"ağırlık #\" gibi değerler çıktı. Ağırlık bir <b>olasılık</b> olmalı, yani # ile # arasında. Sigmoid tam bunu yapar.": "<b>ReLU is differentiable but unbounded.</b> Its output can exceed #, and as you saw values such as \"weight #\" came out. A weight has to be a <b>probability</b>, that is between # and #. A sigmoid does exactly that.",
  "<b>lr = # çok büyük.</b> Yön doğru ama adımlar devasa; model vadinin karşı yamacına daha yükseğe fırlıyor ve ıraksıyor. Bu ekranda gördüğün <code>nan</code>, gerçek eğitimde de aynı sebepten çıkar.": "<b>lr = # is too large.</b> The direction is right but the steps are huge; the model leaps to the opposite slope of the valley, higher up, and diverges. The <code>nan</code> you see on this screen appears in real training for the same reason.",
  "<b>Topladın, çarpmadın.</b> O zaman ağırlıkların hiçbir etkisi kalmıyor: w=# ile w=# aynı davranışı üretmiyor ama <i>ölçekleme</i> gücü kayboluyor. Ağırlık, girdinin <b>ne kadar önemli</b> olduğunu söyler, bu ancak çarpımla ifade edilir.": "<b>You added instead of multiplying.</b> Then the weights have no effect left: w=# and w=# do not produce the same behaviour but the power to <i>scale</i> is lost. A weight says <b>how important</b> an input is, and that can only be expressed by multiplication.",
  "Çıktı <b>#</b>, # ile # arasında, \"%# geçer\" diye okunabilir. Yazdığın bu dört satır, bir sinir ağının <b>tek yapıtaşı</b>. Bir katman, aynı işlemi birçok nöron için paralel yapmaktan ibaret ve bu yüzden GPU'larda bu kadar hızlı çalışıyor (hepsi tek matris çarpımı).": "The output is <b>#</b>, between # and #, and can be read as \"passes with #%\". These four lines you wrote are the <b>single building block</b> of a neural network. A layer is nothing but doing the same operation in parallel for many neurons, and that is why it runs so fast on GPUs (it is all one matrix multiplication).",
  "Kapı çalıştı. x eşiğe yaklaştıkça ağırlık pürüzsüz kayıyor (%# → %# → %#) ve tahmin # ile # arasında <b>sürekli</b> değişiyor. Sert ağaçta bu geçiş tek adımda zıplıyordu.<br><br>Yazdığın bu üç satır, <b>neural-trees</b>'in temelidir: kapı türevlenebilir olduğu için eşik <b>t</b>, sıcaklık <b>T</b> ve yaprak değerleri artık gradient descent ile birlikte öğrenilebilir.": "The gate works. As x approaches the threshold the weight slides smoothly (#% → #% → #%) and the prediction varies <b>continuously</b> between # and #. In a hard tree that transition jumped in a single step.<br><br>These three lines you wrote are the basis of <b>neural-trees</b>: because the gate is differentiable, the threshold <b>t</b>, the temperature <b>T</b> and the leaf values can now all be learned together by gradient descent.",
  "ETIKET": "LABELS",
  "KİLİTLİ": "LOCKED",
  "AĞIRLIK": "WEIGHT",
  "KÜMELER": "CLUSTERS",
  "YARIÇAP": "RADIUS",
  "BİLEŞEN": "COMPONENTS",
  "KORUNAN": "PRESERVED",
  "ENTROPİ": "ENTROPY",
  "UYDURMA": "INVENTION",
  "SALDIRI": "ATTACK",
  "CEZASIZ": "UNPENALISED",
  "VARYANS": "VARIANCE",
  "EN UZAK": "FURTHEST",
  "KAÇ KAT": "FACTOR",
  "YAYILIM": "SPREAD",
  "OPTİMAL": "OPTIMAL",
  "AÇGÖZLÜ": "GREEDY",
  "HEDEF x": "TARGET x",
  "ORTANCA": "MEDIAN",
  "DOĞRU p": "CORRECT p",
  "AYARSIZ": "UNTUNED",
  "MASKELİ": "MASKED",
  "KONUŞMA": "CONVERSATION",
  "GETİRME": "RETRIEVAL",
  "SVAHILI": "SWAHILI",
  "MALIYET": "COST",
  "KESISIM": "CROSSING",
  "B TABAN": "B BASE RATE",
  "HAVUZDA": "IN THE POOL",
  "BASABAS": "BREAK-EVEN",
  "GECIKME": "LATENCY",
  "# ORNEK": "# EXAMPLES",
  "SON HATA": "FINAL ERROR",
  "KESİNLİK": "PRECISION",
  "DERİNLİK": "DEPTH",
  "SON DOĞ.": "FINAL ACC.",
  "KATEGORİ": "CATEGORY",
  "EN YAKIN": "NEAREST",
  "SIFIRDAN": "FROM SCRATCH",
  "TRANSFER": "TRANSFER",
  "TAM AYAR": "FULL TUNE",
  "BİRLEŞME": "MERGES",
  "EN OLASI": "MOST LIKELY",
  "p-DEĞERİ": "p-VALUE",
  "SIRALAMA": "RANKING",
  "BİRLİKTE": "TOGETHER",
  "J ÖLÇÜSÜ": "MEASURE J",
  "POLİTİKA": "POLICY",
  "GERÇEK f": "TRUE f",
  "NEWTON x": "NEWTON x",
  "GERÇEKTE": "IN TRUTH",
  "DOĞRUSAL": "LINEAR",
  "EN BÜYÜK": "LARGEST",
  "ÖN-GÖREV": "PRETEXT",
  "DOĞRUDAN": "DIRECT",
  "RASTGELE": "RANDOM",
  "ORTALAMA": "MEAN",
  "KURTARMA": "RECOVERY",
  "DAR UZAY": "NARROW SPACE",
  "DOGRULUK": "ACCURACY",
  "MUDAHALE": "INTERVENTION",
  "KULLANIM": "UTILISATION",
  "BIRLESME": "MERGES",
  "# ÜYEYLE": "WITH # MEMBERS",
  "PARAMETRE": "PARAMETERS",
  "BAŞLANGIÇ": "START",
  "YAKALANAN": "CAUGHT",
  "FONKSİYON": "FUNCTION",
  "OLASILIĞI": "PROBABILITY",
  "KV BELLEK": "KV MEMORY",
  "VERİ PAYI": "DATA SHARE",
  "ORT. HATA": "MEAN ERROR",
  "YANLILIK²": "BIAS²",
  "EN KISASI": "SHORTEST",
  "GRADYAN x": "GRADIENT x",
  "LOG KANIT": "LOG EVIDENCE",
  "YENİ ALAN": "NEW AREA",
  "ALT SINIR": "LOWER BOUND",
  "TEK-SİMGE": "SINGLE-TOKEN",
  "O GÖREVDE": "ON THAT TASK",
  "TERS ÇİFT": "REVERSED PAIRS",
  "YARI ÖMÜR": "HALF LIFE",
  "INGILIZCE": "ENGLISH",
  "ESIT OLSA": "IF EQUAL",
  "YAZI TURA": "COIN FLIP",
  "FPR FARKI": "FPR GAP",
  "PPV FARKI": "PPV GAP",
  "BOS ALARM": "EMPTY ALARMS",
  "DOGAL DIL": "NATURAL LANGUAGE",
  "# ÖRNEKTE": "AT # EXAMPLES",
  "EZBERLEYEN": "MEMORISING",
  "HATA (MSE)": "ERROR (MSE)",
  "ÖLÜ MERKEZ": "DEAD CENTRES",
  "DUYARLILIK": "SENSITIVITY",
  "KAYBEDİLEN": "LOST",
  "MAKS TÜREV": "MAX DERIVATIVE",
  "BLOK PARAM": "BLOCK PARAMS",
  "TOKEN BAŞI": "PER TOKEN",
  "HESAP PAYI": "COMPUTE SHARE",
  "İSTEK BAŞI": "PER REQUEST",
  "EĞİTİM RSS": "TRAINING RSS",
  "SIFIRLANAN": "ZEROED OUT",
  "x₁ KAYMASI": "x₁ SHIFT",
  "VERİDE std": "std IN THE DATA",
  "ALAN ORANI": "AREA RATIO",
  "HEDEF ORAN": "TARGET RATIO",
  "ÇIKTI BOYU": "OUTPUT LENGTH",
  "DEĞİŞTİ Mİ": "DID IT CHANGE",
  "TEK ZİNCİR": "SINGLE CHAIN",
  "KONTROLSÜZ": "UNCHECKED",
  "P(GEÇERLİ)": "P(VALID)",
  "TV SAPMASI": "TV DISTORTION",
  "AYKIRI YOK": "NO OUTLIER",
  "AYKIRI VAR": "WITH OUTLIER",
  "VARSAYILAN": "DEFAULT",
  "GENIS UZAY": "WIDE SPACE",
  "NET KAZANC": "NET GAIN",
  "# ETİKETLE": "WITH # LABELS",
  "# ETIKET R": "# LABELS R",
  "# ETIKET B": "# LABELS B",
  "TEST HATASI": "TEST ERROR",
  "SERT tahmin": "HARD prediction",
  "BAŞLANGICIN": "OF THE START",
  "EN İYİ DOĞ.": "BEST ACC.",
  "HIZ KAZANCI": "SPEEDUP",
  "TOPLAM HATA": "TOTAL ERROR",
  "İÇ ÇEKİRDEK": "INNER CORE",
  "EN İYİ SKOR": "BEST SCORE",
  "KABA KUVVET": "BRUTE FORCE",
  "DETERMİNANT": "DETERMINANT",
  "TABAN ORANI": "BASE RATE",
  "DENENEN TUR": "TOURS TRIED",
  "DOĞRUSAL AE": "LINEAR AE",
  "VERİ İÇİ sd": "sd IN THE DATA",
  "FAZLA KAYIP": "EXCESS LOSS",
  "TV UZAKLIĞI": "TV DISTANCE",
  "SIGAN METIN": "TEXT THAT FITS",
  "GERCEK FARK": "TRUE GAP",
  "POZITIF PAY": "POSITIVE SHARE",
  "KUCUK MODEL": "SMALL MODEL",
  "# TEN SAPMA": "DEVIATION FROM #",
  "YANLIŞ ALARM": "FALSE ALARMS",
  "BAYES TAVANI": "BAYES CEILING",
  "EĞİTİM KAYBI": "TRAINING LOSS",
  "ARAÇ ÇAĞRISI": "TOOL CALLS",
  "TİPİK BAŞARI": "TYPICAL SUCCESS",
  "AYAKTA KALAN": "SURVIVORS",
  "RIDGE EN İYİ": "RIDGE BEST",
  "FARKLI DEĞER": "DISTINCT VALUES",
  "KOŞUL SAYISI": "CONDITION NUMBER",
  "ULAŞAN HÜCRE": "CELLS REACHED",
  "ŞU ANKİ ORAN": "CURRENT RATIO",
  "AÇILAN DÜĞÜM": "NODES EXPANDED",
  "DOYGUN BİRİM": "SATURATED UNITS",
  "KUYRUK ORANI": "TAIL RATIO",
  "DÜZ AĞ KAYBI": "PLAIN NET LOSS",
  "DEĞER SAYISI": "NUMBER OF VALUES",
  "EN ZOR (ilk)": "HARDEST (first)",
  "GEÇERLİ DİZİ": "VALID SEQUENCES",
  "EN ÇOK ŞİŞEN": "MOST INFLATED",
  "EN ÇOK SÖNEN": "MOST SUPPRESSED",
  "DENK PENCERE": "EQUIV. WINDOW",
  "HEDEF ALANDA": "ON THE TARGET",
  "DIŞ %# KABUK": "OUTER #% SHELL",
  "KURAL ÖĞRENEN": "RULE LEARNING",
  "EĞİTİM HATASI": "TRAINING ERROR",
  "EN İYİ DERECE": "BEST DEGREE",
  "A ile B farkı": "A minus B",
  "EN KÖTÜ SAPMA": "WORST DEVIATION",
  "DOĞRUSAL HATA": "LINEAR ERROR",
  "kNN DOĞRULUĞU": "kNN ACCURACY",
  "DENENEN ATAMA": "ASSIGNMENTS",
  "TÜREV ÇARPIMI": "DERIVATIVE PRODUCT",
  "DİZİ UZUNLUĞU": "SEQUENCE LENGTH",
  "ORTALAMA KAPI": "MEAN GATE",
  "DAL TEPESİNDE": "AT THE BRANCH TOP",
  "BAĞLAM SAYISI": "CONTEXT COUNT",
  "KAZANAN DOGRU": "WINNER CORRECT",
  "# PARAMETREDE": "AT # PARAMETERS",
  "YUMUŞAK tahmin": "SOFT prediction",
  "EN ÇOK BAKTIĞI": "LOOKS MOST AT",
  "YAKALAMA ORANI": "RECALL",
  "DESTEK VEKTÖRÜ": "SUPPORT VECTORS",
  "AYRILABİLİR Mİ": "SEPARABLE?",
  "DOĞRULAMA DOĞ.": "VALIDATION ACC.",
  "MODEL AĞIRLIĞI": "MODEL WEIGHTS",
  "GÜRÜLTÜ TABANI": "NOISE FLOOR",
  "KENAR UZUNLUĞU": "EDGE LENGTH",
  "HASTALIK ORANI": "DISEASE RATE",
  "SON KATMAN std": "LAST LAYER std",
  "AÇIKLANAN ORAN": "SHARE EXPLAINED",
  "BELLEK KAZANCI": "MEMORY SAVED",
  "BELGE UZUNLUĞU": "DOCUMENT LENGTH",
  "SONSAL ENTROPİ": "POSTERIOR ENTROPY",
  "M TOKEN BASINA": "PER M TOKENS",
  "MERKEZ UZAKLIĞI": "CENTRE DISTANCE",
  "DOĞRULAMA KAYBI": "VALIDATION LOSS",
  "EKSENİN YÜZDESİ": "SHARE OF THE AXIS",
  "TEK TEK TOPLAMI": "SUM ONE AT A TIME",
  "EĞİTİMDE BAŞARI": "SUCCESS IN TRAINING",
  "ZİRVEYE UZAKLIK": "DISTANCE TO THE PEAK",
  "TOPLAMSAL MODEL": "ADDITIVE MODEL",
  "TEK TEK ÇARPIMI": "PRODUCT ONE AT A TIME",
  "GENEL HATIRLAMA": "OVERALL RECALL",
  "ağırlıklı toplam": "weighted sum",
  "TAM SIFIR VAR MI": "ANY EXACT ZEROS?",
  "KLİPLİ SON KAYIP": "CLIPPED FINAL LOSS",
  "SILUETIN SECTIGI": "SILHOUETTE'S PICK",
  "GEREKEN DOGRULUK": "ACCURACY NEEDED",
  "SIFIR ATISLI LLM": "ZERO-SHOT LLM",
  "# PİKSEL DEĞİŞİM": "CHANGE AT # PIXELS",
  "ETİKET GEREKİR Mİ": "ARE LABELS NEEDED?",
  "ADIM BAŞINA SÖNÜM": "DECAY PER STEP",
  "EN BÜYÜK YANLIŞ q": "LARGEST WRONG q",
  "DERECE # İLE FARK": "GAP WITH DEGREE #",
  "YANLIŞ ALARM ORANI": "FALSE ALARM RATE",
  "İKİ ÖRNEKLEM FARKI": "GAP BETWEEN SAMPLES",
  "ORTALAMA KARE HATA": "MEAN SQUARED ERROR",
  "İKİNCİ DERECE HATA": "SECOND ORDER ERROR",
  "KATMAN BAŞINA ORAN": "RATIO PER LAYER",
  "PCA YA GÖRE KAZANÇ": "GAIN OVER PCA",
  "BELIRSIZLIK TOPLADI": "UNCERTAINTY COLLECTED",
  "# ÖRNEKTE · GÖRÜLEN": "AT # EXAMPLES · SEEN",
  "YENİDEN KURMA HATASI": "RECONSTRUCTION ERROR",
  "# ÖRNEKTE · GÖRÜLMEYEN": "AT # EXAMPLES · UNSEEN",
  "ÖNEMLİ AYARDA FARKLI DEĞER": "DISTINCT VALUES ON THE KEY SETTING",
  "Altı adımı da gez": "Go through all six steps",
  "#. ağaca kadar çek": "Drag to tree #",
  "Tahta boyunu # yap": "Set the board size to #",
  "Üye sayısını # yap": "Set the number of members to #",
  "Altı parçayı da gez": "Go through all six parts",
  "Turu #'ye kadar çek": "Drag the pass up to #",
  "#. tura kadar götür": "Take it to pass #",
  "Bir başı tek tek seç": "Select each head one by one",
  "k'yı #'e kadar çıkar": "Raise k to #",
  "Derinliği #'ya çıkar": "Raise the depth to #",
  "#. adıma kadar götür": "Take it to step #",
  "#. aşamaya kadar git": "Go up to stage #",
  "Eşiği #'a kadar indir": "Lower the threshold to #",
  "Determinantı sıfır yap": "Make the determinant zero",
  "C'yi #'in üstüne çıkar": "Raise C above #",
  "T'yi #'in üstüne çıkar": "Raise T above #",
  "# bileşene kadar indir": "Go down to # components",
  "Adımı #'ün üstüne çıkar": "Raise the step above #",
  "Dereceyi #'a kadar çıkar": "Raise the degree to #",
  "Hatayı #'in altına indir": "Get the error below #",
  "Çıktıyı #'un altına indir": "Get the output below #",
  "Epoch'u #'ün üstüne çıkar": "Raise the epoch above #",
  "Kesinliği %# altına indir": "Get the precision below #%",
  "Kesinliği %# üstüne çıkar": "Raise the precision above #%",
  "Eğitimi sonuna kadar götür": "Run the training to the end",
  "Döngüyü sonuna kadar götür": "Run the loop to the end",
  "Fazla kaybı # altına indir": "Get the excess loss below #",
  "Eşiği #'a çek ve sonucu gör": "Drag the threshold to # and see the result",
  "f₁ sapmasını # altına indir": "Get the f₁ deviation below #",
  "y ekseninde # civarına getir": "Bring it to around # on the y axis",
  "#. gizli katmana kadar götür": "Take it to hidden layer #",
  "Birleşmeyi #'in üstüne çıkar": "Raise the merges above #",
  "Doğruluğu %#'ın altına düşür": "Drop the accuracy below #%",
  "Doğruluğu %#'in üstüne çıkar": "Raise the accuracy above #%",
  "Test hatasını # altına indir": "Get the test error below #",
  "Önce hatayı #'ün altına indir": "First get the error below #",
  "T'yi bir uca (# veya #) götür": "Take T to one extreme (# or #)",
  "Bağlamı #K token üstüne çıkar": "Raise the context above #K tokens",
  "Test MSE'yi #'in altına indir": "Get the test MSE below #",
  "T'yi iki uca da götür (# ve #)": "Take T to both extremes (# and #)",
  "Ölçeği bir uca (# veya #) götür": "Take the scale to one extreme (# or #)",
  "Adım sayısını #'ün üstüne çıkar": "Raise the number of steps above #",
  "kNN doğruluğunu %# üstüne çıkar": "Raise the kNN accuracy above #%",
  "Açıklanan oranı %# üstüne çıkar": "Raise the share explained above #%",
  "Sonsal entropiyi # altına indir": "Get the posterior entropy below #",
  "LSTM’in öne geçtiği uzunluğu bul": "Find the length at which the LSTM gets ahead",
  "Ağaç sayısını #'nin üstüne çıkar": "Raise the number of trees above #",
  "Örnek sayısını #'ün üstüne çıkar": "Raise the number of examples above #",
  "Toplam hatayı #'nin altına indir": "Get the total error below #",
  "Koşul sayısını #'ün altına indir": "Get the condition number below #",
  "Türev çarpımını #⁻⁴ altına indir": "Get the derivative product below #⁻⁴",
  "Karşılaştırmayı #'ün üstüne çıkar": "Raise the comparisons above #",
  "Test RMSE değerini # altına indir": "Get the test RMSE below #",
  "Kenar uzunluğunu #'ın üstüne çıkar": "Raise the edge length above #",
  "Kabuktaki hacmi %#'ın üstüne çıkar": "Raise the volume in the shell above #%",
  "Oranı #¹⁰ üstüne çıkaran bir x bul": "Find an x that takes the ratio above #¹⁰",
  "Newton'u hedefe #e# yakınlığa getir": "Get Newton within #e# of the target",
  "Toplam kazancı # katın üstüne çıkar": "Raise the total gain above a factor of #",
  "Denenen tur sayısını # üstüne çıkar": "Raise the tours tried above #",
  "Değer sayısını # ya da altına indir": "Get the number of values to # or below",
  "PCA’ya göre kazancı %# üstüne çıkar": "Raise the gain over PCA above #%",
  "Oranı # üstüne çıkaran uzunluğu bul": "Find the length that takes the ratio above #",
  "En az bir katsayıyı tam sıfıra indir": "Drive at least one coefficient to exactly zero",
  "Duyarlılığı yüzde birin altına indir": "Get the sensitivity below one per cent",
  "Siluetin yanlış k seçtiği ayrımı bul": "Find the separation at which the silhouette picks the wrong k",
  "T'yi #'in altına indir ve sonucu gör": "Lower T below # and see the result",
  "GQA'yı aç ve bağlamı #K üstüne çıkar": "Turn GQA on and raise the context above #K",
  "Dört özelliği birden sıfırla (λ ≈ #)": "Zero out all four features at once (λ ≈ #)",
  "# adımlık zinciri %# in altına düşür": "Drop the # step chain below #%",
  "wd'yi #'ün üstüne çıkar ve çöküşü gör": "Raise wd above # and watch it collapse",
  "Uyumu %#'nin altına indir ve κ'ya bak": "Get the agreement below #% and look at κ",
  "Test MSE'yi #'in altına indir (λ ≈ #)": "Get the test MSE below # (λ ≈ #)",
  "Bellek kazancını # katın üstüne çıkar": "Raise the memory saving above a factor of #",
  "Öğrenme hızını ıraksayacak kadar büyüt": "Raise the learning rate until it diverges",
  "Aktarimin tamamen kayboldugu aciyi bul": "Find the angle at which the transfer disappears entirely",
  "Kötü başlangıcı seç ve sona kadar götür": "Pick the bad start and run it to the end",
  "Sıralamanın bilgi taşımadığı durumu bul": "Find the case where the ranking carries no information",
  "Dolaylı enjeksiyona (#. sıra) kadar git": "Go as far as indirect injection (row #)",
  "Kuyruk oranını bir milyonun üstüne çıkar": "Raise the tail ratio above a million",
  "Belirsizlik oranını # katın üstüne çıkar": "Raise the uncertainty ratio above a factor of #",
  "Adım başına sönüm oranını # üstüne çıkar": "Raise the decay per step above #",
  "ReLU'yu (veya sonrasını) seç ve farkı gör": "Pick ReLU (or later) and see the difference",
  "Son kelimeye (korpusta olmayan) kadar git": "Go to the last word (the one not in the corpus)",
  "Optimal olmayan bir yol bulan yöntemi seç": "Pick a method that finds a non-optimal path",
  "Hiçbir doğruluğun yetmediği bir durum bul": "Find a case where no accuracy is enough",
  "Sıcaklığı #'in altına indir ve sonucu gör": "Lower the temperature below # and see the result",
  "x = #'deki belirsizliği #'un altına indir": "Get the uncertainty at x = # below #",
  "Şeklin alanını # katından fazlasına çıkar": "Grow the area of the shape beyond a factor of #",
  "CE gradyanını MSE'nin # katından fazla yap": "Make the CE gradient more than # times the MSE one",
  "Naive Bayes tavanına çık (# örnek ve üstü)": "Reach the naive Bayes ceiling (# examples or more)",
  "#×# havuzun direncini kıracak kadar kaydır": "Shift enough to break the resistance of the #×# pool",
  "Bir katsayıyı tam sıfır yapan bir bütçe bul": "Find a budget that makes one coefficient exactly zero",
  "RNN’e göre farkı yüz bin katın üstüne çıkar": "Raise the gap over the RNN above a hundred thousand",
  "RAG'i aç ve günlük isteği #'in üstüne çıkar": "Turn RAG on and raise the daily requests above #",
  "# piksel kaydırmada değişimi # altına indir": "Get the change under a # pixel shift below #",
  "Fazla kaybın # üstünde takıldığı durumu bul": "Find the case where the excess loss sticks above #",
  "Saflığı %# yapan ayrım ve k birleşimini bul": "Find the separation and k that give a purity of #%",
  "x₀ ile x₁ arasındaki farkı #'nin altına indir": "Get the gap between x₀ and x₁ below #",
  "Ayırıcı modelin farkını # puanın üstüne çıkar": "Raise the discriminative model's lead above # points",
  "Hem # hücre açan hem # adım bulan yöntemi seç": "Pick the method that expands # cells and finds # steps",
  "Ön-görev temsilini %# doğruluğun üstüne çıkar": "Raise the pretext representation above #% accuracy",
  "Şişmeyi # puanın üstüne çıkaran birleşimi bul": "Find the combination that takes the inflation above # points",
  "Üç bölgeyi de dene (yavaş · sağlıklı · patlak)": "Try all three regions (slow · healthy · blown up)",
  "Birkaç örnekli LLM i geçen etiket sayısını bul": "Find the number of labels that beats the few-shot LLM",
  "Bütçeyi # denemede tut ve yöntemi RASTGELE yap": "Keep the budget at # trials and set the method to RANDOM",
  "Başlangıçtaki değeri #'in altına düşür (γ = #)": "Drop the starting value below # (γ = #)",
  "Doğrusal yaklaşımın hatasını #'in üstüne çıkar": "Raise the error of the linear approximation above #",
  "Geri izlemeye göre # kattan fazla kazanç sağla": "Gain more than a factor of # over backtracking",
  "CoT modelini %# e çıkaracak örnek sayısını bul": "Find the number of examples that takes the CoT model to #%",
  "Yüksek doğrulukta bile zarar eden bir durum bul": "Find a case that loses money even at high accuracy",
  "Test R² değerini # üstüne çıkaran kodlamayı bul": "Find the encoding that takes the test R² above #",
  "Kullanım oranını %# in üstüne çıkaran hacmi bul": "Find the volume that takes the utilisation above #%",
  "Girdi kaymasını # standart sapmanın üstüne çıkar": "Raise the input shift above # standard deviations",
  "Birlikte karıştırmanın farkını #'ün üstüne çıkar": "Raise the gap from shuffling together above #",
  "# oyla doğruluğu %# in üstüne çıkaracak ε yi bul": "Find the ε that takes # votes above #% accuracy",
  "Varyansı #'nin üstüne çıkar (derece # ve sonrası)": "Raise the variance above # (degree # and beyond)",
  "Yayılımı #'nın üstüne çıkar (PCA yönü, #° civarı)": "Raise the spread above # (the PCA direction, around #°)",
  "Boş alarm oranını %# ın üstüne çıkaran durumu bul": "Find the case that takes the empty alarm rate above #%",
  "top-k'yı #'e indir ya da top-p'yi #'nın altına çek": "Lower top-k to # or pull top-p below #",
  "Perplexity’yi teorik alt sınırın %# yakınına getir": "Get the perplexity within #% of the theoretical lower bound",
  "Üç tekrar hakkıyla %# ı geçen yakalama oranını bul": "Find the recall that passes #% with three retries",
  "Sigan metin oranini %# in altina dusuren orani bul": "Find the ratio that drops the share of text that fits below #%",
  "Altuzayi # in uzerinde kurtaran gorev sayisini bul": "Find the number of tasks that recovers the subspace above #",
  "PPV farkını # nin üstüne çıkaran taban oranını bul": "Find the base rate that takes the PPV gap above #",
  "Açıklanan oranı sıfırın altına düşüren uzunluğu bul": "Find the length that drops the share explained below zero",
  "Kısayolun # kattan fazla kazandırdığı derinliği bul": "Find the depth where the shortcut gains more than a factor of #",
  "Ön-görev doğruluğunu %# üstüne çıkaran uzunluğu bul": "Find the length that takes the pretext accuracy above #%",
  "Beş görevi de %# e çıkaran toplam örnek sayısını bul": "Find the total number of examples that takes all five tasks to #%",
  "Hatayı # nin altında tutan en düşük bit sayısını bul": "Find the lowest bit count that keeps the error below #",
  "PPV eşitliğinin bedelini # FPR farkının üstüne çıkar": "Push the price of PPV equality above an FPR gap of #",
  "Hedefe varan bir politika öğret (keşif oranını artır)": "Teach a policy that reaches the goal (raise the exploration rate)",
  "Son katmandaki standart sapmayı # ile # arasına getir": "Bring the standard deviation in the last layer between # and #",
  "Modeli # kat hızlandırmaktan iyi bir isabet oranı bul": "Find a hit rate that beats speeding the model up by a factor of #",
  "Aramayı varsayılanın önüne geçiren deneme sayısını bul": "Find the number of trials that takes the search past the default",
  "Kaybı #'ün üstüne çıkar (kediyi düşür, köpeği yükselt)": "Raise the loss above # (lower the cat, raise the dog)",
  "Hatayı #'in altına indir (spline, # parametre ve üstü)": "Get the error below # (a spline, # parameters or more)",
  "Atış sayısını # üstüne çıkar ve sapmayı # altına indir": "Raise the number of tosses above # and get the deviation below #",
  "Düz ağın eğitim kaybını # üstüne çıkaran derinliği bul": "Find the depth that takes the plain network's training loss above #",
  "Kendi barındırmanın API den ucuz olduğu bir noktayı bul": "Find a point where self hosting is cheaper than the API",
  "En uzak komşuyu, en yakının # katından daha yakına getir": "Bring the furthest neighbour to within a factor of # of the nearest",
  "A* ile optimal olmayan bir yol bulduracak bir ağırlık seç": "Pick a weight that makes A* find a non-optimal path",
  "İki örneklem arasındaki katsayı farkını #'in üstüne çıkar": "Raise the coefficient gap between the two samples above #",
  "Derece # seçip ikinci dereceden hatayı #'nin altına indir": "Pick degree # and get the second order error below #",
  "Genel hatırlamayı %# in üstüne çıkaran pencere boyunu bul": "Find the window size that takes the overall recall above #%",
  "x₁'in permütasyon önemini #'ün üstüne çıkar (modeli değiştir)": "Raise x₁'s permutation importance above # (change the model)",
  "Ziyaret kümesini kapatıp açılan düğüm sayısını # üstüne çıkar": "Turn the visited set off and raise the nodes expanded above #",
  "Beş görev ortalamasını %# in üstüne çıkaran örnek sayısını bul": "Find the number of examples that takes the five task average above #%",
  "Toplanan pozitif payı havuzdakinin iki katını geçen dengeyi bul": "Find the balance where the collected positive share is more than twice the pool's",
  "Eğitim başarısını %#'un altına düşür ama politikayı bozma (ε = #)": "Drop the training success below #% without breaking the policy (ε = #)",
  "Uçtan uca kazancı # katın üstüne çıkaran katman ve hızlanmayı bul": "Find the layer and speedup that take the end to end gain above a factor of #",
  "Derece #’ye göre kanıtı # log biriminin üstüne çıkaran dereceyi bul": "Find the degree whose evidence exceeds degree #'s by more than # log units",
  "başlangıç": "start",
  "ATA": "ASSIGN",
  "GÜNCELLE": "UPDATE",
  "Aston Zhang, Zachary C. Lipton, Mu Li, Alexander J. Smola (2022) · Derin Öğrenmeye Dalış (Dive into Deep Learning)": "Aston Zhang, Zachary C. Lipton, Mu Li, Alexander J. Smola (2022) · Dive into Deep Learning",
  "AÇIK": "ON",
  "açık": "on",
  "kapalı": "off",
  "# ağ": "# networks",
  "IZGARA": "GRID",
  "# saat": "# hours",
  "#. tur": "pass #",
  "#. MLP": "#. MLP",
  "# atış": "# tosses",
  "POLİNOM": "POLYNOMIAL",
  "# · SFT": "# · SFT",
  "# bölüm": "# episodes",
  "# boyut": "# dimensions",
  "# konum": "# positions",
  "# simge": "# tokens",
  "# gorev": "# tasks",
  "# ornek": "# examples",
  "# birim": "# units",
  "ham saat": "the raw hour",
  "önce ger": "stretch first",
  "maksimum": "maximum",
  "#. girdi": "input #",
  "#K token": "#K tokens",
  "# · RLHF": "# · RLHF",
  "#. DÜŞÜN": "#. THINK",
  "#. ÇAĞIR": "#. CALL",
  "# deneme": "# trials",
  "# katman": "# layers",
  "# derece": "degree #",
  "fiil–özne": "verb–subject",
  "henüz yok": "not yet",
  "görülmedi": "not seen",
  "öğrenci #": "student #",
  "#. GÖZLEM": "#. OBSERVE",
  "#. + artık": "#. + residual",
  "#. CEVAPLA": "#. ANSWER",
  "derinlik #": "depth #",
  "# birlesme": "# merges",
  "girdi uzayı": "the input space",
  "önce döndür": "rotate first",
  "#. tur sonu": "end of pass #",
  "#. ARAÇ SEÇ": "#. PICK A TOOL",
  "# · parabol": "# · a parabola",
  "# × optimal": "# × optimal",
  "hepsi birden": "all at once",
  "önceki token": "the previous token",
  "KÜBİK SPLINE": "CUBIC SPLINE",
  "# · doğrusal": "# · linear",
  "açık (τ = #)": "on (τ = #)",
  "kendine bakan": "self attending",
  "CEZASIZ (OLS)": "UNPENALISED (OLS)",
  "# · Ön-eğitim": "# · Pretraining",
  "gizli katman #": "hidden layer #",
  "#×# = # deneme": "#×# = # trials",
  "AÇIK (×# girdi)": "ON (×# input)",
  "ön eğitimde görüldü": "seen in pretraining",
  "gönderim (zamir→isim)": "reference (pronoun→noun)",
  "kötü (üçü aynı köşede)": "bad (all three in the same corner)",
  "iyi (köşelere dağılmış)": "good (spread to the corners)",
/*SON*/
};

/* Bilerek olduğu gibi bırakılanlar: simge, birim, model adı, kod parçası. */
var ARAYUZ_AYNI = [
  "x","w","b","k","C","T","r","f","OY","wd","x₀","x₁","F#","AUC","MSE","SGD","‖W‖","RNN","PCA","CoT","API","LLM",
  "Adam","∂L/∂w","∂L/∂b","p / q","BIT","# OY","DENK ρ","TEST","MODEL","TOKEN",
  "    n = <span class=\"fn\">len</span>(a)",
  "b = b <span class=\"op\">-</span> lr <span class=\"op\">*</span> gb",
  "<span class=\"kw\">def</span> <span class=\"fn\">bubble_sort</span>(a):",
  "            <span class=\"kw\">if</span> a[i] &gt; a[i + <span class=\"st\">#</span>]:",
  "                a[i], a[i+<span class=\"st\">#</span>] = a[i+<span class=\"st\">#</span>], a[i]",
  "# BLOK","#-GRAM","# ADIM","Cohen κ","p(kedi)","CART d#","x=# std","x (saat)","y (puan)","t (eşik)",
  "Momentum","det(XᵀX)","λ=# İKEN","r = # DA","r = f DE","MODEL #x","KATMAN #","IZGARA #","# TEKRAR",
  "|x₀ − x₁|","PERPLEXITY","SOFT TREE","DIJKSTRA","TEORİK γ¹⁰","PENCERE #","x=# TE sd","R=# ÇAĞRI",
  "BN YOK std","BN VAR std","top-k eler","top-p eler","f₁ SAPMASI","f₂ SAPMASI","ÇIKTI  σ(z)",
  "x₀ katsayı","x₁ katsayı","x₂ katsayı","x₀ önem","x₁ önem","x₂ önem","KV BAŞI","TEST R²","TEST MSE","TEST RMSE",
  "lr","naive Bayes","SINIR (#/a)","GETİRME r=#","Q(başlangıç)","AĞAÇ TEST R²","DOĞRUSAL TEST R²",
  "CE gradyanı","MSE gradyanı","T (sıcaklık)","TEK AĞAÇ (d#)","#×# DEĞİŞİM","x=# için sağ","x=# ortalama",
  "R=# DOĞRULUK","BN YOK doygun","BN VAR doygun","lojistik reg.","|DETERMİNANT|","#e# DUYARLILIĞI",
  "y=# DA YOĞUNLUK","# ADIM ÖNCE · LSTM","KATMAN # / KATMAN #","DOĞRUSAL + en×boy","#→# SIÇRAMA",
  "A*","GELU","LeakyReLU","sin/cos","w = #","l = #","a = #","b = #","d = #","r = #","r = #x",
  "epoch #","#. Q,K,V","#. RMSNorm","#. Attention","#. Çıkış izd.","RIDGE λ=#","RIDGE (L#)","LASSO (L#)",
/*SONAYNI*/
];
