/* ML Academy · tuval etiketleri sözlüğü (TR → EN)
   viz.js içindeki CEV() bu tabloyu kullanır. Sayı içeren metinlerde sayılar
   # ile temsil edilir ve karşılıkta aynı sırayla geri konur.
   Envanteri güncellemek için: node tuval-metin.js eksik   */
var TUVAL_EN = {
  "gürültü": "noise",
  "doğru sınıfa verilen olasılık": "probability given to the correct class",
  "kuş": "bird",
  "doğruluk": "accuracy",
  "ceza gücü λ": "penalty strength λ",
  "köpek": "dog",
  "çalışma saati": "study hours",
  "eğitim": "training",
  "■ çapraz entropi": "■ cross entropy",
  "ÇAPRAZ ENTROPİ  = −log( p(doğru) )": "CROSS ENTROPY  = −log( p(correct) )",
  "emin ve yanlış → ceza patlar": "confident and wrong → the penalty explodes",
  "Ham puanlar olasılığa dönüşür, kayıp yalnızca DOĞRU sınıfa verilen olasılığa bakar.": "Raw scores turn into probabilities; the loss looks only at the probability given to the CORRECT class.",
  "kayıp": "loss",
  "model en çok yanıldığında MSE en az öğrenir": "MSE learns least when the model is most wrong",
  "SOFTMAX ve ÇAPRAZ ENTROPİ": "SOFTMAX AND CROSS ENTROPY",
  "DETERMİNANT": "DETERMINANT",
  "gerçek fonksiyon": "true function",
  "b (kesişim)": "b (intercept)",
  "BU NOKTADAKİ MODEL": "THE MODEL AT THIS POINT",
  "EN İYİ": "BEST",
  "KAYIP HARİTASI": "LOSS MAP",
  "w (eğim)": "w (slope)",
  "ham doğrusal": "raw linear",
  "EĞİTİM RSS": "TRAINING RSS",
  "katsayı değeri": "coefficient value",
  "süt": "milk",
  "SAĞ yaprak": "RIGHT leaf",
  "|DETERMİNANT|": "|DETERMINANT|",
  "gri: özgün şekil": "grey: the original shape",
  "MATRİS": "MATRIX",
  "MATRİS · UZAYA UYGULANAN İŞLEM": "MATRIX · AN OPERATION APPLIED TO SPACE",
  "Matris bir sayı tablosu değil. Her noktayı başka bir noktaya taşıyan bir kural.": "A matrix is not a table of numbers. It is a rule that moves every point to another point.",
  "oranla aynı sayı": "the same number as the ratio",
  "ÖZGÜN ALAN": "ORIGINAL AREA",
  "renkli: dönüşmüş hâli": "colour: the transformed version",
  "yeni / özgün": "new / original",
  "YENİ ALAN": "NEW AREA",
  "Alan tam olarak |determinant| katına çıkıyor.": "The area grows by exactly a factor of |determinant|.",
  "DETERMİNANT NE ANLATIYOR": "WHAT THE DETERMINANT TELLS YOU",
  "Determinant pozitif: yön korundu.": "The determinant is positive: the orientation is preserved.",
  "görülen görev": "seen task",
  "çapraz entropi": "cross entropy",
  "Eğitim yok. Soru gelince tüm veriye bakar, en yakın k komşuya oy verdirir.": "No training. When a question arrives it looks at all the data and lets the nearest k neighbours vote.",
  "DOĞRULUK": "ACCURACY",
  "çıktı": "output",
  "GERÇEK": "TRUTH",
  "ı": "i",
  "sayı": "number",
  "çalışma": "study",
  "Girdileri ağırlıklarla çarpar, toplar, bir eşikten geçirir. Sinir ağının tek yapıtaşı.": "It multiplies the inputs by weights, sums them and passes them through a threshold. The single building block of a neural network.",
  "önceki": "previous",
  "TEK NÖRON": "A SINGLE NEURON",
  "VERİ": "DATA",
  "AKTİVASYON": "ACTIVATION",
  "ÇIKTI": "OUTPUT",
  "◎ yanlış": "◎ wrong",
  "● sınıf A": "● class A",
  "● sınıf B": "● class B",
  "BAŞLANGIÇTAKİ DEĞER": "THE STARTING VALUE",
  "bölüm": "episode",
  "görülmeyen görev": "unseen task",
  "ÖDÜL SİNYALİ ULAŞAN HÜCRE": "CELLS THE REWARD SIGNAL REACHED",
  "ÖĞRENİLEN POLİTİKA": "THE LEARNED POLICY",
  "öğrenirken kaç kez kazandı": "how often it won while learning",
  "polinom + ölçekleme": "polynomial + scaling",
  "Q-ÖĞRENME · ÖDÜLLE ÖĞRENMEK": "Q-LEARNING · LEARNING FROM REWARD",
  "Sınıflandırma = uzayı ikiye bölen bir çizgi çizmek.": "Classification = drawing a line that splits the space in two.",
  "\"Kahvaltıda genellikle ___\"  ·  model olasılık verir, seçimi SEN ayarlarsın.": "\"For breakfast usually ___\"  ·  the model gives probabilities and YOU tune the choice.",
  "çay": "tea",
  "ÇEŞİTLİLİK": "DIVERSITY",
  "en olası": "most likely",
  "ham olasılık (soluk)  ·  filtrelenmiş ve yeniden normalize (parlak)": "raw probability (faint)  ·  filtered and renormalised (bright)",
  "olasılığı": "probability",
  "ÖRNEKLEME  ·  bir sonraki token nasıl seçilir": "SAMPLING  ·  how the next token is chosen",
  "reçel": "jam",
  "test hatası": "test error",
  "polinom özellikler": "polynomial features",
  "ALGORİTMA": "ALGORITHM",
  "Aynı problem, aynı test kümesi. Değişen sadece hangi kaldıracı çektiğin.": "The same problem, the same test set. The only difference is which lever you pull.",
  "KALDIRAÇLARI TEK TEK ÇEKİNCE": "PULLING THE LEVERS ONE BY ONE",
  "log₁₀ eğitim turu": "log₁₀ training rounds",
  "log₁₀ test hatası": "log₁₀ test error",
  "TEMELE GÖRE KAZANÇ": "GAIN OVER THE BASELINE",
  "ÜÇ KALDIRAÇ · VERİ, HESAP, ALGORİTMA": "THREE LEVERS · DATA, COMPUTE, ALGORITHM",
  "ÜÇÜ BİRDEN": "ALL THREE AT ONCE",
  "çünkü": "because",
  "meraklıydı": "was curious",
  "AYNI BÜTÇE, İKİ ESNEKLİK BİÇİMİ": "THE SAME BUDGET, TWO FORMS OF FLEXIBILITY",
  "BU EĞRİNİN ORTALAMA KARE HATASI": "THE MEAN SQUARED ERROR OF THIS CURVE",
  "EN KÖTÜ SAPMA": "WORST DEVIATION",
  "Global polinom derece yükseltir, spline düğüm ekler. Parametre sayısı eşit.": "A global polynomial raises its degree, a spline adds knots. The parameter count is equal.",
  "parametre sayısı": "number of parameters",
  "yoğunluk": "density",
  "+ artık": "+ residual",
  "ADIMDAN SONRA GERÇEK f": "THE TRUE f AFTER THE STEP",
  "buradayız": "we are here",
  "değer": "value",
  "EĞİTİM ÖRNEĞİ": "TRAINING EXAMPLES",
  "gerçek": "truth",
  "GERÇEK EN KÜÇÜK NOKTA": "THE TRUE MINIMUM",
  "gerçek f(x)": "true f(x)",
  "Gradyan inişi \"buradan sonrası düz\" varsayar. Adım büyüdükçe bu varsayım çöker.": "Gradient descent assumes \"it is flat from here on\". That assumption collapses as the step grows.",
  "haftalık çalışma saati": "weekly study hours",
  "ölçekli": "scaled",
  "sınav puanı": "exam score",
  "TAHMİN HATASI": "PREDICTION ERROR",
  "YEREL YAKLAŞIM · TAYLOR": "LOCAL APPROXIMATION · TAYLOR",
  "■ sınıf A": "■ class A",
  "■ sınıf B": "■ class B",
  "BU YÖNDE DOĞRULUK": "ACCURACY IN THIS DIRECTION",
  "CANLIDA ÖLÇEBİLİRSİN · sadece girdiler": "MEASURABLE IN PRODUCTION · inputs only",
  "CANLIDA ÖLÇEMEZSİN · etiket yok": "NOT MEASURABLE IN PRODUCTION · no labels",
  "DAĞILIM KAYMASI": "DISTRIBUTION SHIFT",
  "doğruluk %": "accuracy %",
  "doğrusal yaklaşım (teğet)": "linear approximation (tangent)",
  "DOĞRUSAL YAKLAŞIMIN TAHMİNİ": "THE LINEAR APPROXIMATION'S PREDICTION",
  "FISHER ÖLÇÜSÜ J": "FISHER MEASURE J",
  "FISHER: SINIFLARI AYIRAN YÖN": "FISHER: THE DIRECTION THAT SEPARATES THE CLASSES",
  "gerçek kural (eğri)": "the true rule (curve)",
  "Katsayılar sıfıra doğru ÇEKİLİR ama sıfır olmaz.": "The coefficients are PULLED towards zero but never become zero.",
  "kayma miktarı": "amount of shift",
  "Model bir satır bile değişmedi. Değişen tek şey, gelen verinin nereden geldiği.": "Not a single line of the model changed. The only thing that changed is where the incoming data comes from.",
  "modelin sınırı (doğru)": "the model's boundary (line)",
  "soluk = eğitim · parlak = canlı": "faint = training · bright = production",
  "top-k  kapalı": "top-k  off",
  "Veriyi tek bir yöne indireceğiz. Hangi yön? En çok yayılan mı, en iyi ayıran mı?": "We will reduce the data to a single direction. Which one? The one that spreads most or the one that separates best?",
  "yazı tura seviyesi": "coin flip level",
  "yön (derece)": "direction (degrees)",
  "yön üstündeki konum": "position along the direction",
  "■ dolandırıcılık": "■ fraud",
  "AĞIRLIK İLKLEME · SİNYAL KATMAN KATMAN": "WEIGHT INITIALISATION · THE SIGNAL LAYER BY LAYER",
  "BAŞLANGIÇ ÖLÇEĞİ": "INITIAL SCALE",
  "doğru geçen": "correctly passed",
  "DOĞRULUK NEDEN YALAN SÖYLER": "WHY ACCURACY LIES",
  "dolandırıcı": "fraudulent",
  "dolandırıcılık": "fraud",
  "eşik": "threshold",
  "KAÇAN": "MISSED",
  "Kapı doğrusal olduğu için ÇAPRAZ kesebilir. CART merdiven yapmak zorundaydı.": "Because the gate is linear it can cut DIAGONALLY. CART had to build a staircase.",
  "KATMAN BAŞINA ORAN": "RATIO PER LAYER",
  "Katsayılar sıfıra ÇARPILIR, model özellik seçer.": "The coefficients are SLAMMED to zero and the model selects features.",
  "KESİNLİK (precision)": "PRECISION",
  "METRİKLER": "METRICS",
  "MODELİN DEDİĞİ": "WHAT THE MODEL SAID",
  "SKOR DAĞILIMI": "SCORE DISTRIBUTION",
  "top-p  kapalı": "top-p  off",
  "yakalama oranı": "recall",
  "yanlış alarm": "false alarm",
  "yanlış alarm oranı": "false alarm rate",
  "ağırlık normu ‖W‖": "weight norm ‖W‖",
  "AŞIRI UYUM ve DÜZENLİLEŞTİRME": "OVERFITTING AND REGULARISATION",
  "doğrulama": "validation",
  "KLASİK KARAR AĞACI": "A CLASSICAL DECISION TREE",
  "BAĞLAM": "CONTEXT",
  "ETİKET SAYISI": "NUMBER OF LABELS",
  "öğretmen": "teacher",
  "(uzak−yakın)/yakın": "(far−near)/near",
  "BOYUT LANETİ": "THE CURSE OF DIMENSIONALITY",
  "EN UZAK KOMŞU, EN YAKININDAN KAÇ KAT UZAK": "HOW MANY TIMES FURTHER THE FURTHEST NEIGHBOUR IS THAN THE NEAREST",
  "noktaların bu kadarı kenara yapışık": "this share of the points is stuck to the edge",
  "sağlıklı": "healthy",
  "sorgu noktasına uzaklık": "distance to the query point",
  "AYNI SÜREÇTEN İKİ AYRI ÖRNEKLEM": "TWO SEPARATE SAMPLES FROM THE SAME PROCESS",
  "en büyük / en küçük eğrilik": "largest / smallest curvature",
  "hatırlama": "recall",
  "HESSIAN · VADİNİN ŞEKLİ": "THE HESSIAN · THE SHAPE OF THE VALLEY",
  "İKİ ÖRNEKLEM ARASI FARK (w₁)": "DIFFERENCE BETWEEN THE TWO SAMPLES (w₁)",
  "İki yön, iki farklı eğrilik. Gradyan inişi dar yönde titrerken geniş yönde sürünüyor.": "Two directions, two different curvatures. Gradient descent oscillates in the narrow direction while crawling in the wide one.",
  "KOŞUL SAYISI": "CONDITION NUMBER",
  "KOŞUL SAYISI κ": "CONDITION NUMBER κ",
  "örneklem A": "sample A",
  "örneklem B": "sample B",
  "Tek adımda kapalı çözüm. Ama XᵀX tersi alınamaz hale gelirse ne olur?": "A closed form solution in a single step. But what if XᵀX becomes impossible to invert?",
  "BU STRATEJİ": "THIS STRATEGY",
  "Değişken: sütun. Alan: satırlar. Kısıt: aynı satır ya da köşegen olmasın.": "Variable: a column. Domain: the rows. Constraint: not the same row or diagonal.",
  "GERİ DÖNÜŞ": "BACKTRACK",
  "GERİ İZLEMEYE GÖRE": "COMPARED WITH BACKTRACKING",
  "hiç kısıt kullanmadan": "using no constraints at all",
  "İzmir": "Izmir",
  "kaç kat az": "times fewer",
  "KISIT TATMİN · N-VEZİR": "CONSTRAINT SATISFACTION · N-QUEENS",
  "kısıtlar aramayı budayınca": "when the constraints prune the search",
  "■ yanlılık²": "■ bias²",
  "hata bileşeni": "error component",
  "kraliçe": "queen",
  "● eğitim": "● training",
  "BPE TOKENİZASYON": "BPE TOKENISATION",
  "En sık geçen karakter çiftlerini birleştire birleştire alt-kelime sözlüğü kurar.": "It builds a sub-word vocabulary by merging the most frequent character pairs over and over.",
  "İstanbul": "Istanbul",
  "kitaplarımızdan": "kitaplarımızdan",
  "öğrenilen birleşme sayısı": "number of merges learned",
  "ÖĞRENİLEN BİRLEŞMELER (sırayla)": "THE MERGES LEARNED (in order)",
  "token sayısı": "number of tokens",
  "BAŞABAŞ HACİM": "BREAK-EVEN VOLUME",
  "İKİ FARKLI MALİYET ŞEKLİ": "TWO DIFFERENT COST SHAPES",
  "kadın": "woman",
  "■ eğitim hatası (ayrı ölçek, hep düşüyor)": "■ training error (separate scale, always falling)",
  "■ ızgara": "■ grid",
  "■ log kanıt": "■ log evidence",
  "bağlamdaki örnek sayısı": "number of examples in the context",
  "BU DERECENİN LOG KANITI": "THE LOG EVIDENCE OF THIS DEGREE",
  "BULUNAN EN İYİ SKOR": "BEST SCORE FOUND",
  "deneme bütçesi": "trial budget",
  "derece arttıkça hep düşer": "it always falls as the degree rises",
  "Doğrulama kümesi yok. Model karmaşıklığını verinin kendisi seçiyor.": "There is no validation set. The data itself chooses the model complexity.",
  "EĞİTİM HATASI": "TRAINING ERROR",
  "en iyi bölge": "the best region",
  "HİPERPARAMETRE ARAMASI": "HYPERPARAMETER SEARCH",
  "İki ayar var ama sadece biri sonucu belirliyor. Bütçeni nasıl harcarsın?": "There are two settings but only one determines the result. How do you spend your budget?",
  "KANITIN ZİRVESİ": "THE PEAK OF THE EVIDENCE",
  "log kanıt": "log evidence",
  "ÖNEMLİ ayar": "the setting that MATTERS",
  "ÖNEMLİ AYARDA KAÇ FARKLI DEĞER": "HOW MANY DISTINCT VALUES ON THE SETTING THAT MATTERS",
  "önemsiz ayar": "the setting that does not matter",
  "■ ÖNBELLEKLİ": "■ WITH CACHE",
  "■ ÖNBELLEKSİZ": "■ WITHOUT CACHE",
  "API FİYATI": "API PRICE",
  "aylık token hacmi": "monthly token volume",
  "KV CACHE BELLEĞİ  (GB)": "KV CACHE MEMORY  (GB)",
  "Üretilen her token için tüm geçmişi yeniden hesaplamak yerine, K ve V'yi sakla.": "Instead of recomputing the whole history for every token generated, store K and V.",
  "üretilen token": "tokens generated",
  "ÜRETİM MALİYETİ": "GENERATION COST",
  "ağırlık başına bit": "bits per weight",
  "BELİRSİZLİK · VERİ NOKTASINDA": "UNCERTAINTY · AT A DATA POINT",
  "BİT": "BITS",
  "çocuk": "child",
  "en büyük": "largest",
  "GAUSSIAN PROCESS · BELİRSİZLİĞİNİ SÖYLEYEN MODEL": "GAUSSIAN PROCESS · A MODEL THAT STATES ITS UNCERTAINTY",
  "GP ortalaması": "GP mean",
  "model nerede bilmediğini biliyor": "the model knows where it does not know",
  "Tek bir sayı değil, bir dağılım. Bant daraldıkça model emin, açıldıkça bilmiyor.": "Not a single number but a distribution. The narrower the band the more confident the model, the wider the less it knows.",
  "\"kitaplarımızdan\" nasıl parçalanıyor?": "how is \"kitaplarımızdan\" split up?",
  "−∇L gideceğimiz yön": "−∇L the direction we go",
  "■ lojistik regresyon · ayırıcı": "■ logistic regression · discriminative",
  "■ naive Bayes · üretici": "■ naive Bayes · generative",
  "Aynı veri, iki felsefe. Hangisi kazanır? Cevap elindeki veri miktarına bağlı.": "The same data, two philosophies. Which wins? The answer depends on how much data you have.",
  "eğitim örneği (log ölçek)": "training examples (log scale)",
  "LOJİSTİK REGRESYON · ayırıcı": "LOGISTIC REGRESSION · discriminative",
  "NAIVE BAYES · üretici": "NAIVE BAYES · generative",
  "test doğruluğu %": "test accuracy %",
  "ÜRETİCİ ve AYIRICI": "GENERATIVE AND DISCRIMINATIVE",
  "○ destek vektörü": "○ support vector",
  "● şehir": "● city",
  "Ankara Üniversitesi'nden": "from Ankara University",
  "Boğaziçi Üniversitesi'nden": "from Bogazici University",
  "Bu kişi hakkında bilgim yok.": "I have no information about this person.",
  "destek vektörü": "support vectors",
  "Doğrusal bir skor üretir, sigmoid ile olasılığa çevirir, çapraz entropi ile eğitilir.": "It produces a linear score, turns it into a probability with a sigmoid, and is trained with cross entropy.",
  "doygun nöron": "saturated neurons",
  "EVAL SETİ · kaç örnek yeterli?": "EVAL SET · how many examples are enough?",
  "gözlenen doğruluk": "observed accuracy",
  "HALÜSİNASYON NEDEN OLUYOR?": "WHY DOES HALLUCINATION HAPPEN?",
  "Her katmanda aktivasyonları yeniden ölçekler. Başlangıç ağırlıkları ne olursa olsun dağılım sabit kalır.": "It rescales the activations at every layer. Whatever the initial weights, the distribution stays fixed.",
  "Hiç etiket verilmedi. Model kategorileri sadece BİRLİKTE GEÇMEDEN öğrendi.": "No labels were given. The model learned the categories from CO-OCCURRENCE alone.",
  "İstanbul Teknik Üniversitesi'nden": "from Istanbul Technical University",
  "kategori DIŞI ortalama kosinüs": "mean cosine ACROSS categories",
  "kategori İÇİ ortalama kosinüs": "mean cosine WITHIN a category",
  "KATMAN KATMAN DAĞILIM": "THE DISTRIBUTION LAYER BY LAYER",
  "KAZANÇ": "GAIN",
  "KELİME GÖMMELERİ": "WORD EMBEDDINGS",
  "kötü": "bad",
  "LOJİSTİK REGRESYON": "LOGISTIC REGRESSION",
  "marj genişliği": "margin width",
  "Model \"doğru ol\" diye eğitilmedi. \"Bir sonraki tokenı tahmin et\" diye eğitildi.": "The model was not trained to \"be correct\". It was trained to \"predict the next token\".",
  "Negatif çıktıları sıfırladığı için varyans her": "Because it zeroes the negative outputs, the variance",
  "ODTÜ'den": "from METU",
  "OLASILIK HARİTASI": "PROBABILITY MAP",
  "ÖRNEK SAYISI  →  ARALIK GENİŞLİĞİ": "NUMBER OF EXAMPLES  →  WIDTH OF THE INTERVAL",
  "ReLU SİNYALİN YARISINI ATIYOR": "ReLU THROWS AWAY HALF THE SIGNAL",
  "Sadece ayırmakla yetinmez, iki sınıf arasındaki BOŞLUĞU en geniş yapmaya çalışır.": "It is not content with separating; it tries to make the GAP between the two classes as wide as possible.",
  "sarı bant = marj": "yellow band = the margin",
  "∇L yokuş YUKARI": "∇L UPHILL",
  "ÇOK BAŞLI DİKKAT": "MULTI-HEAD ATTENTION",
  "KESİŞİM": "CROSSING",
  "olgunun yaşı (kaç tur önce söylendi)": "age of the fact (how many turns ago it was said)",
  "ŞİŞME": "INFLATION",
  "Tek bir dikkat yetmez. Paralel başlar farklı ilişki türlerini aynı anda izler.": "One attention is not enough. Parallel heads track different kinds of relation at the same time.",
  "katman sayısı": "number of layers",
  "yaklaşım artık geçersiz": "the approximation is no longer valid",
  "AÇILAN HÜCRE": "CELLS EXPANDED",
  "Algoritma sadece noktaların yerini biliyor.": "The algorithm only knows where the points are.",
  "arasındaki bağ kopuyor ve bunu fark etmek zor.": "breaks down, and that is hard to notice.",
  "artı: gerçek konu merkezleri": "crosses: the true topic centres",
  "Dört gerçek konu var. Kümeleme etiketleri görmüyor, sadece gömmeleri görüyor.": "There are four true topics. Clustering does not see the labels, only the embeddings.",
  "Harita biliniyor. Soru öğrenmek değil, en az hücreyi açarak en kısa yolu bulmak.": "The map is known. The question is not to learn but to find the shortest path expanding the fewest cells.",
  "Konu diye bir kavramı yok; sadece birbirine": "It has no concept of a topic; it only gathers",
  "KONU KEŞFİ · GÖMMELER VE KÜMELER": "TOPIC DISCOVERY · EMBEDDINGS AND CLUSTERS",
  "Konular üst üste bindikçe kümeler ile konular": "As the topics overlap, the link between the clusters and the topics",
  "KÜME SAYISI": "NUMBER OF CLUSTERS",
  "KÜMELEME ETİKET GÖRMÜYOR": "CLUSTERING DOES NOT SEE THE LABELS",
  "merkezler arası": "between centres",
  "OPTİMAL Mİ": "OPTIMAL?",
  "renk: kümeleme kararı": "colour: the clustering decision",
  "SİLUET": "SILHOUETTE",
  "test doğ.": "test acc.",
  "TRANSFER ÖĞRENME": "TRANSFER LEARNING",
  "yakın noktaları bir araya topluyor.": "nearby points together.",
  "DİZİ UZUNLUĞU": "SEQUENCE LENGTH",
  "Etiket yok. Model verideki grupları kendisi buluyor.": "No labels. The model finds the groups in the data by itself.",
  "k-MEANS KÜMELEME": "k-MEANS CLUSTERING",
  "ÖĞRENME  gözetimsiz": "LEARNING  unsupervised",
  "-, gerçek ilişki": "-, the true relationship",
  "(tipik dağılım, önce GETİRMEYİ ölç)": "(a typical distribution, measure RETRIEVAL first)",
  "⚠ DİKKAT": "⚠ CAUTION",
  "bağlam + soru → LLM": "context + question → LLM",
  "Çıkış izd.": "Out proj.",
  "deneme sayısı": "number of trials",
  "eşit": "equal",
  "GENİŞ UZAY": "WIDE SPACE",
  "getirme (vektör arama)": "retrieval (vector search)",
  "getirme hatası": "retrieval error",
  "Halüsinasyonu azaltmanın ana yolu: modele cevaplamadan önce doğru belgeleri ver.": "The main way to reduce hallucination: give the model the right documents before it answers.",
  "her parça → vektör (çok dilli model)": "every chunk → a vector (a multilingual model)",
  "hiç arama yok": "no search at all",
  "iki özellik neredeyse tek çizgi": "the two features are almost a single line",
  "karakter başına token": "tokens per character",
  "model doğruluğu": "model accuracy",
  "vektörler → vektör veritabanı (HNSW)": "vectors → a vector database (HNSW)",
  "◎ test (model bunları hiç görmedi)": "◎ test (the model never saw these)",
  "BAĞLAM İÇİ ÖĞRENME · AĞIRLIKLAR SABİT": "IN-CONTEXT LEARNING · THE WEIGHTS ARE FIXED",
  "Bağlamdaki örnek sayısı arttıkça tahmin iyileşiyor. Hiçbir ağırlık güncellenmiyor.": "The prediction improves as the number of examples in the context grows. No weight is updated.",
  "Bu iki sayı hiç değişmiyor. Değişen tek şey": "These two numbers never change. The only thing that changes",
  "DOĞRU POZİTİF": "TRUE POSITIVE",
  "görevi bilseydi": "if it knew the task",
  "Görülen görevde fazla kayıp sıfıra iniyor:": "On a seen task the excess loss falls to zero:",
  "Görülmeyen görevde bir tabanda takılıyor.": "On an unseen task it sticks at a floor.",
  "ICL, görevi bilen tahminciyi yakalıyor.": "ICL catches the predictor that knows the task.",
  "KÂHİN NLL": "ORACLE NLL",
  "kâhine göre fazla kayıp": "excess loss over the oracle",
  "KESİNLİK": "PRECISION",
  "POZİTİF ÇIKANLARIN İÇİNDE": "AMONG THOSE FLAGGED POSITIVE",
  "pozitifin ne kadarı doğru": "what share of the positives is correct",
  "temsildeki bağıl değişim": "relative change in the representation",
  "YANLIŞ POZİTİF": "FALSE POSITIVE",
  "⚠ KV cache modelin ağırlıklarından BÜYÜK, uzun bağlamın asıl maliyeti bu": "⚠ the KV cache is LARGER than the model's weights; that is the real cost of long context",
  "AÇIK MI KAPALI MI · BAŞABAŞ HACMİ": "OPEN OR CLOSED · THE BREAK-EVEN VOLUME",
  "AI PROJESİ KARARI · BAŞABAŞ DOĞRULUK": "AI PROJECT DECISION · BREAK-EVEN ACCURACY",
  "Altında API, üstünde kendi barındırma ucuz.": "Below it the API is cheaper, above it self hosting.",
  "Altında hiçbir model, hiçbir doğrulukla kâr etmez.": "Below it no model turns a profit at any accuracy.",
  "API doğrusal: hacimle birlikte artar, sıfırda": "The API is linear: it grows with the volume and at zero",
  "artık": "residual",
  "aşırı uyum: yanlılık küçük ama modeller birbirinden çok farklı": "overfitting: the bias is small but the models differ greatly from each other",
  "aylık": "monthly",
  "BAŞABAŞ NOKTASI KAPALI FORMDA": "THE BREAK-EVEN POINT IN CLOSED FORM",
  "BİR BLOKTAKİ PARAMETRE DAĞILIMI": "THE PARAMETER DISTRIBUTION IN ONE BLOCK",
  "BU HACİMDE API": "THE API AT THIS VOLUME",
  "BU HACİMDE KENDİ": "SELF HOSTING AT THIS VOLUME",
  "büyük C → dar marj, az destek vektörü, hataya tahammülsüz (aşırı uyum riski)": "large C → a narrow margin, few support vectors, no tolerance for error (a risk of overfitting)",
  "büyük model": "large model",
  "çalışma saati (x)": "study hours (x)",
  "çoğu görev için yeter": "enough for most tasks",
  "DEĞİŞİM": "CHANGE",
  "dolana kadar sabit, sonra GPU ekleyip zıplar.": "flat until it fills up, then it jumps as a GPU is added.",
  "GEREKEN DOĞRULUK": "ACCURACY REQUIRED",
  "günlük": "daily",
  "HATA EĞRİSİ": "ERROR CURVE",
  "HAVUZLAMA · KAYDIRMAYA DİRENÇ": "POOLING · RESISTANCE TO SHIFT",
  "HAVUZSUZ DEĞİŞİM": "CHANGE WITHOUT POOLING",
  "İMKÂNSIZLIK EŞİĞİ": "THE IMPOSSIBILITY THRESHOLD",
  "istek başı": "per request",
  "k'yı düşür, reranker koy": "lower k, add a reranker",
  "küçük model": "small model",
  "log₁₀ aylık maliyet": "log₁₀ monthly cost",
  "MALİYET ve GECİKME": "COST AND LATENCY",
  "MALİYETİ DÜŞÜRME SIRASI": "THE ORDER OF COST REDUCTION",
  "MSE nin cevabı": "MSE's answer",
  "MÜDAHALE MALİYETİ": "COST OF INTERVENTION",
  "olayın taban oranı (log)": "base rate of the event (log)",
  "ön-görev temsili": "pretext task representation",
  "SEÇİLİ MODEL": "SELECTED MODEL",
  "sıfırdır. Kendi barındırma basamaklı: kapasite": "is zero. Self hosting is stepped: capacity",
  "sınav puanı (y)": "exam score (y)",
  "sinyal söndü": "the signal died out",
  "taban bunun altında ise": "if the base rate is below this",
  "Taban oranı düştükçe gereken doğruluk hızla": "As the base rate falls the accuracy required rises",
  "TEK-SİMGE": "SINGLE-TOKEN",
  "test doğruluğu": "test accuracy",
  "Token başına ücret küçük görünür. Ölçekte hiç öyle değil.": "The price per token looks small. At scale it is not at all.",
  "TRANSFORMER BLOĞU": "A TRANSFORMER BLOCK",
  "turuncu: kendi barındırma": "orange: self hosting",
  "yıllık": "yearly",
  "alanı seçmek, en şanslı ölçüm hatasını seçmektir.": "the highest one is picking the luckiest measurement error.",
  "BİRİNCİ OLMAK BİR SEÇİM İŞLEMİDİR": "BEING FIRST IS AN ACT OF SELECTION",
  "BİRİNCİNİN SKORU": "THE LEADER'S SCORE",
  "Bu bir hile değil; hiç kimse yanlış bir şey yapmadı.": "This is not cheating; nobody did anything wrong.",
  "Bütün modeller aynı. Aralarından en yüksek skoru": "Every model is the same. Picking",
  "cezasız çözüm": "the unpenalised solution",
  "gözlenen skor": "observed score",
  "henüz sağlıklı, doğrulama kaybı hâlâ düşüyor": "still healthy, the validation loss is still falling",
  "hepsinde aynı": "the same in all of them",
  "ÖN EĞİTİM GÖREVİ": "PRETEXT TASK",
  "P(GEÇERLİ)": "P(VALID)",
  "Sadece en yüksek sayı seçildi ve o sayı sapmalı.": "The highest number was simply picked, and that number is biased.",
  "SKOR TABLOSU · KAZANANIN SKORU ŞİŞMİŞTİR": "LEADERBOARD · THE WINNER'S SCORE IS INFLATED",
  "skor tablosundaki model sayısı": "number of models on the leaderboard",
  "yaklaşım hâlâ geçerli": "the approximation is still valid",
  "yeni görevden örnek sayısı": "number of examples from the new task",
  "BN OLMADAN: NÖRONLAR DOYUYOR": "WITHOUT BN: THE NEURONS SATURATE",
  "ÇAĞIR": "CALL",
  "değerlendirme": "evaluation",
  "DÜŞÜN": "THINK",
  "GÖZLEM": "OBSERVE",
  "kapı çıktısı  =  sağ dala gitme ağırlığı": "gate output  =  the weight of going to the right branch",
  "ÖRNEK SAYISI": "NUMBER OF EXAMPLES",
  "x  (özelliğin değeri)": "x  (the feature's value)",
  "en küçük": "smallest",
  "EZBERLEYEN, en yakın kaydı söyler": "MEMORISING, it returns the nearest record",
  "karşılaştırma": "comparison",
  "KLASİK ML": "CLASSICAL ML",
  "KURAL ÖĞRENEN, formül uygular": "RULE LEARNING, it applies a formula",
  "AÇI": "ANGLE",
  "aday eşik": "candidate threshold",
  "ağırlıklı çocuk Gini": "weighted child Gini",
  "AI MÜH.": "AI ENG.",
  "AI MÜHENDİSLİĞİ vs KLASİK ML · EMEK NEREYE GİDİYOR": "AI ENGINEERING vs CLASSICAL ML · WHERE THE EFFORT GOES",
  "ARADAKİ FARK": "THE DIFFERENCE",
  "Aynı problemi iki farklı çalışma biçimiyle çözerken emeğin dağılımı.": "How the effort is distributed when solving the same problem in two different ways.",
  "bağlam": "context",
  "BÖLÜNME NASIL SEÇİLİR?": "HOW IS A SPLIT CHOSEN?",
  "dağıtım": "deployment",
  "doğal dil": "natural language",
  "eğitimi": "training",
  "emek payı (%)": "share of effort (%)",
  "Gini kazancı": "Gini gain",
  "Her aday eşik denenir, Gini kazancı hesaplanır, en büyüğü kazanır.": "Every candidate threshold is tried, the Gini gain is computed, and the largest wins.",
  "İngilizce": "English",
  "kayıt / izleme": "logging / monitoring",
  "KAZANÇ = ebeveyn − çocuk": "GAIN = parent − children",
  "mühendisliği": "engineering",
  "özellik": "feature",
  "SEÇİLİ AŞAMA": "SELECTED STAGE",
  "tanımı": "definition",
  "tasarımı": "design",
  "Türkçe": "Turkish",
  "yeşil: AI mühendisliği": "green: AI engineering",
  "✓ değme noktası KÖŞEDE, bir katsayı tam sıfır": "✓ the touch point is at a CORNER, one coefficient is exactly zero",
  "ağaç derinliği": "tree depth",
  "aynı veri, test R²": "the same data, test R²",
  "bağlam kurma": "context building",
  "çıktı doğrulama": "output validation",
  "doğrudan cevap": "direct answer",
  "DOĞRUSAL MODEL": "LINEAR MODEL",
  "düşünme zinciri": "chain of thought",
  "düz: modelin bulduğu": "solid: what the model found",
  "eğitim R²": "training R²",
  "giriş / yetkilendirme": "auth / authorisation",
  "kesikli: gerçek şekil": "dashed: the true shape",
  "model çağrısı": "model call",
  "TOPLAMSAL MODEL · GERİ-UYDURMA": "ADDITIVE MODEL · BACKFITTING",
  "y = a₀ + f₁(x₁) + f₂(x₂). Her eğri, diğerinin artığına uyduruluyor.": "y = a₀ + f₁(x₁) + f₂(x₂). Every curve is fitted to the residual of the other.",
  "YANLIŞ ALARM f": "FALSE ALARM f",
  "| artık (hata)": "| residual (error)",
  "● gerçek": "● truth",
  "adım sayısı": "number of steps",
  "Ağaç yalnızca EKSEN-HİZALI kesebilir. Çapraz sınırı merdivenle yaklaşır.": "A tree can only cut AXIS ALIGNED. It approximates a diagonal boundary with a staircase.",
  "AĞAÇ YAPISI": "TREE STRUCTURE",
  "ağırlık başına": "per weight",
  "AI YIĞINI · GECİKME NEREYE GİDİYOR": "THE AI STACK · WHERE THE LATENCY GOES",
  "ARAMA ÖNCE VARSAYILANI YAKALAMALI": "THE SEARCH HAS TO CATCH THE DEFAULT FIRST",
  "artık kuantalama değil, model değiştirme oluyor.": "it stops being quantisation and becomes changing the model.",
  "Asıl soru \"hangisi daha iyi\" değil, \"kaç etiket": "The real question is not \"which is better\" but \"how many labels",
  "AUTOML · GENİŞ UZAYDA RASTGELE ARAMA": "AUTOML · RANDOM SEARCH IN A WIDE SPACE",
  "belirsizlik örneklemesi": "uncertainty sampling",
  "bilmiyor. Özet her yaşta bir şans veriyor ama": "does not know. The summary gives a chance at every age but",
  "Çünkü uzayın çoğu kötü ve rastgele seçim onlara": "Because most of the space is bad and random selection lands",
  "dağınık": "scattered",
  "DOĞRUDAN": "DIRECT",
  "dünkü olgu aynı olasılıkla geliyor.": "yesterday's fact comes back with the same probability.",
  "düşüyor.": "on them.",
  "Eğitilmiş ağın ağırlıkları n bitle yeniden yazılıyor. Ağ yeniden eğitilmiyor.": "The weights of a trained network are rewritten with n bits. The network is not retrained.",
  "eğitim örneği": "training examples",
  "eklenen ağaç sayısı": "number of trees added",
  "eklenen düzeltme": "the correction added",
  "EN İYİSİ": "THE BEST",
  "etiket bütçesi": "label budget",
  "etiketli örnek sayısı": "number of labelled examples",
  "GETİRME · GENEL": "RETRIEVAL · OVERALL",
  "HATA ARTIŞI": "ERROR INCREASE",
  "Her yeni kütük, önceki modelin KALAN hatasına uyar. Hatalar birikerek erir.": "Every new stump fits the REMAINING error of the previous model. The errors melt away as they accumulate.",
  "KAÇ BİLEŞEN YETER?": "HOW MANY COMPONENTS ARE ENOUGH?",
  "kanal bazında": "per channel",
  "KARAR AĞACI  ·  CART": "DECISION TREE  ·  CART",
  "KARAR BÖLGELERİ  ·  ◎ hatalı": "DECISION REGIONS  ·  ◎ misclassified",
  "KONUŞMA HAFIZASI · ÜÇ STRATEJİ YAN YANA": "CONVERSATION MEMORY · THREE STRATEGIES SIDE BY SIDE",
  "KUANTİZASYON · KAÇ BİT YETİYOR": "QUANTISATION · HOW MANY BITS ARE ENOUGH",
  "KÜÇÜK MODEL": "SMALL MODEL",
  "kümülatif varyans": "cumulative variance",
  "LLM BİR TABAN ÇİZGİSİDİR": "AN LLM IS A BASELINE",
  "LLM in doğruluğu etiket sayısından bağımsız:": "The LLM's accuracy is independent of the number of labels:",
  "LLM SINIFLANDIRICI · NE ZAMAN KÜÇÜK MODELE GEÇMELİ": "LLM CLASSIFIER · WHEN TO SWITCH TO A SMALL MODEL",
  "LLM veri miktarından bağımsız sabit. Küçük model etiketle öğreniyor.": "The LLM is flat regardless of the amount of data. The small model learns from the labels.",
  "MODEL ÇAĞRISININ PAYI": "THE MODEL CALL'S SHARE",
  "öğrenci": "student",
  "ÖZET · GENEL": "SUMMARY · OVERALL",
  "SEKİZ BİT NEREDEYSE BEDAVA": "EIGHT BITS IS ALMOST FREE",
  "SIFIR ATIŞLI LLM": "ZERO-SHOT LLM",
  "sıfır atışlıyı geçtiği": "it passes zero-shot",
  "ŞEKİLLER FARKLI, SAYILAR KARŞILAŞTIRILABİLİR": "THE SHAPES DIFFER, THE NUMBERS ARE COMPARABLE",
  "tensör bazında": "per tensor",
  "Uzun konuşmada tek ölçeklenen strateji bu.": "In a long conversation this is the only strategy that scales.",
  "yaş büyüdükçe şans üstel azalıyor.": "the chance falls exponentially as the age grows.",
  "yeşil: küçük model": "green: the small model",
  "YUMUŞAK EŞİK  ·  σ((x−t)/T)": "SOFT THRESHOLD  ·  σ((x−t)/T)",
  "· biçim yanlılığı": "· format bias",
  "· kendini kayırma": "· self preference",
  "· konum yanlılığı": "· position bias",
  "· uzunluk yanlılığı": "· length bias",
  "■ gradyan inişi": "■ gradient descent",
  "adım": "step",
  "artar. Model belleğe sığmıyorsa iyi bir takas.": "rises. A good trade if the model does not fit in memory.",
  "atış sayısı": "number of tosses",
  "Aynı kayıp yüzeyi, aynı başlangıç. Fark sadece adımı nasıl attıkları.": "The same loss surface, the same start. The only difference is how they take the step.",
  "büyüse de std patlamıyor. Bedeli türevde.": "grows, the std does not explode. The price is in the derivative.",
  "Cevap kalitesini bir modelle puanlamak, ucuz ve hızlı. Ama önce judge'ı doğrula.": "Scoring answer quality with a model is cheap and fast. But validate the judge first.",
  "eğitim adımı": "training step",
  "EĞRİLİĞİ KULLANMAK · NEWTON": "USING THE CURVATURE · NEWTON",
  "Elo puanı": "Elo rating",
  "EN BÜYÜK": "LARGEST",
  "en büyük / ortanca:": "largest / median:",
  "geçiş sırasında yeniden hesaplar.": "recomputes them during the pass.",
  "Geri geçiş, ileri geçişteki ara değerlere ihtiyaç duyar. Onlar saklanmak zorunda.": "The backward pass needs the intermediate values from the forward pass. They have to be stored.",
  "Gradyan sadece yönü bilir. Newton eğriliği de bilir ve adımın boyunu kendi hesaplar.": "The gradient only knows the direction. Newton also knows the curvature and computes the step size itself.",
  "hangi kaynağı harcadığını değiştiriyor.": "changes which resource you spend.",
  "HEPSİNİ SAKLA": "STORE THEM ALL",
  "Her ağaç farklı bir örneklem ve farklı özelliklerle büyür. Sonra hepsi oy verir.": "Every tree grows on a different sample with different features. Then they all vote.",
  "her nokta İKİ dala da ağırlıkla gider": "every point goes to BOTH branches with a weight",
  "HESAPLAMA ÇİZGESİ · TERS MODUN BEDELİ": "THE COMPUTATION GRAPH · THE PRICE OF REVERSE MODE",
  "iki bağımsız yön": "two independent directions",
  "ilk gösterilen cevabı tercih eder": "it prefers the answer shown first",
  "İNSAN": "HUMAN",
  "JUDGE'IN BİLİNEN YANLILIKLARI": "THE JUDGE'S KNOWN BIASES",
  "KAYIP HARİTASINDA YOL": "THE PATH ON THE LOSS MAP",
  "kendi ürettiği metni yüksek puanlar": "it scores its own text highly",
  "kesikli = gerçek güç  ·  düz = Elo tahmini": "dashed = true strength  ·  solid = the Elo estimate",
  "Kombinatorik dersindeki gibi: sınıfı değil,": "As in the combinatorics lesson: not the class",
  "kontrol noktası (√L)": "checkpointing (√L)",
  "Kontrol noktası, saklanmayan ara değerleri geri": "Checkpointing recomputes the intermediate values it did not store during the backward",
  "KÖR KARŞILAŞTIRMA · ELO": "BLIND COMPARISON · ELO",
  "KUYRUK NE KADAR AĞIR": "HOW HEAVY THE TAIL IS",
  "log₁₀ atış sayısı": "log₁₀ number of tosses",
  "log₁₀ kayıp": "log₁₀ loss",
  "log₁₀ saklanan değer": "log₁₀ values stored",
  "madde işaretli metni tercih eder": "it prefers bulleted text",
  "milyonlarca kat büyük gradyan üretiyor.": "produce gradients millions of times larger.",
  "OLASILIK · BÜYÜK SAYILAR": "PROBABILITY · LARGE NUMBERS",
  "Olasılık tek bir denemeyi değil, uzun vadeli oranı söyler.": "Probability tells you the long run rate, not a single trial.",
  "OPTIMIZER YARIŞI": "OPTIMISER RACE",
  "Ortalama bir sayı değil, dağılım var:": "The average is not a number, there is a distribution:",
  "parantez içi = gerçek güç": "in brackets = true strength",
  "parti sayısı": "number of batches",
  "Partilerin çoğu sorunsuz. Bir kısmı": "Most batches are fine. Some of them",
  "PATLAYAN GRADYAN · PARTİLERİN DAĞILIMI": "EXPLODING GRADIENTS · THE DISTRIBUTION OVER BATCHES",
  "uzun cevabı daha iyi sanır": "it takes a long answer for a better one",
  "ve kuyruk eğitimi öldüren şey.": "and the tail is what kills the training.",
  "yazı oranı": "share of tails",
  "yeşil = uyum  ·  kırmızı = anlaşmazlık": "green = agreement  ·  red = disagreement",
  "yok sayılır": "is ignored",
  "zayıf": "weak",
  "Ağı \"derin\" yapan şey budur. Ve türevi çok küçükse gradyan derinlere ulaşamaz.": "This is what makes a network \"deep\". And if its derivative is tiny the gradient cannot reach the depths.",
  "AI YIĞINI · BİR KATMANI HIZLANDIRMAK NE KAZANDIRIR": "THE AI STACK · WHAT SPEEDING UP ONE LAYER BUYS",
  "AKTİVASYON FONKSİYONLARI": "ACTIVATION FUNCTIONS",
  "BAYESÇİ AĞ · TOPLULUK YAYILIMI": "BAYESIAN NETWORK · THE SPREAD OF AN ENSEMBLE",
  "DEĞER  V": "VALUE  V",
  "Dolayısıyla durağan dağılım hepsinde tekdüze ve": "So the stationary distribution is uniform in all of them and",
  "düz ağ": "plain network",
  "FONKSİYON": "FUNCTION",
  "Hangi katmana yatırım yapacağın burada belli oluyor.": "This is where it becomes clear which layer to invest in.",
  "Her kelime, cümledeki diğer kelimelere ne kadar “bakacağına” kendi karar verir.": "Every word decides for itself how much to \"look at\" the other words in the sentence.",
  "katman sıfır olsa bile": "even if the layer is zero",
  "katmanın hızlanma katsayısı": "the layer's speedup factor",
  "Kazancın tamamı ön-görevden geliyor.": "The whole gain comes from the pretext task.",
  "KENDİ KENDİNE GÖZETİM · ETİKETSİZ VERİDEN TEMSİL": "SELF SUPERVISION · A REPRESENTATION FROM UNLABELLED DATA",
  "kesikli: gerçek fonksiyon": "dashed: the true function",
  "konu başına etiketli örnek": "labelled examples per topic",
  "KURULUM NEDEN ADİL": "WHY THE SETUP IS FAIR",
  "MASKELİ AÇGÖZLÜ": "MASKED GREEDY",
  "modelin A ya eğilimi": "the model's leaning towards A",
  "NEDEN AÇILIYOR": "WHY IT OPENS UP",
  "ÖN-GÖREV": "PRETEXT TASK",
  "Payı p olan bir katmanı sonsuz hızlandırsan bile": "Even if you speed up a layer with share p infinitely",
  "Seçilen katman s kat hızlanırsa uçtan uca kazanç. Kesikli çizgi sonsuz hızlanma sınırı.": "The end to end gain if the selected layer is sped up by a factor of s. The dashed line is the infinite speedup limit.",
  "sıfırdan / temelli": "from scratch / pretrained",
  "tek-simge sayımları SIFIR bilgi taşıyor.": "single-token counts carry ZERO information.",
  "TÜREV": "DERIVATIVE",
  "uçtan uca kazanç": "end to end gain",
  "uymak zorunda, dolayısıyla birbirlerine yakınlar.": "have to fit the same points, so they are close to each other.",
  "Üç konu da aynı simge dağılımına sahip. Fark yalnızca geçişlerde.": "All three topics have the same token distribution. The difference is only in the transitions.",
  "Üç konunun geçiş matrisi de çift stokastik.": "The transition matrix of all three topics is doubly stochastic.",
  "ÜYE SAYISI": "NUMBER OF MEMBERS",
  "ve başlangıç farkları ayrışmaya dönüşüyor.": "and the differences in initialisation turn into divergence.",
  "Veri bitince onları kısıtlayan bir şey kalmıyor": "When the data runs out nothing constrains them any more",
  "VERİ İÇİ sd": "sd INSIDE THE DATA",
  "Veri olan yerde bütün üyeler aynı noktalara": "Where there is data every member",
  "YENİ SÜRE": "NEW TIME",
  "✓ sıralama doğru bulundu": "✓ the ranking was recovered correctly",
  "AÇIKLANAN ORAN": "SHARE EXPLAINED",
  "aylık istek sayısı (log)": "monthly requests (log)",
  "aylık maliyet (log)": "monthly cost (log)",
  "Aynı veri, aynı boğaz. Doğrusal otokodlayıcı nereye varıyor?": "The same data, the same bottleneck. Where does a linear autoencoder end up?",
  "Aynı veri, iki farklı model. Hangi özelliğin önemli olduğu konusunda anlaşamıyorlar.": "The same data, two different models. They do not agree on which feature matters.",
  "bir kerelik etiketleme masrafıdır.": "is a one-off labelling cost.",
  "birlikte > ayrı ayrı": "together > separately",
  "boğaz boyu": "bottleneck size",
  "BU HACİMDE KÜÇÜK": "THE SMALL MODEL AT THIS VOLUME",
  "BU HACİMDE LLM": "THE LLM AT THIS VOLUME",
  "DOĞRUSAL AE": "LINEAR AE",
  "DOĞRUSAL AE İLE PCA FARKI": "THE DIFFERENCE BETWEEN A LINEAR AE AND PCA",
  "DOĞRUSAL OLMAYAN": "NON-LINEAR",
  "doğrusal olmayan otokodlayıcı": "non-linear autoencoder",
  "doğrusal otokodlayıcı": "linear autoencoder",
  "hacimle birlikte açılmaya devam eder.": "keeps widening with the volume.",
  "KATSAYININ BÜYÜKLÜĞÜ": "THE SIZE OF THE COEFFICIENT",
  "kısayollu": "with a shortcut",
  "Küçük modelin maliyeti neredeyse tamamen": "The small model's cost is almost entirely",
  "LLM çağrı başına ödenir. Küçük model bir kerelik etiket maliyeti ister, sonra bedavaya yakındır.": "An LLM is paid per call. A small model asks for a one-off label cost and is nearly free after that.",
  "LLM in maliyeti hacimle doğrusal artar.": "The LLM's cost grows linearly with the volume.",
  "NE KADAR DAHA İYİ": "HOW MUCH BETTER",
  "OTOKODLAYICI · PCA İLE KARŞILAŞTIRMA": "AUTOENCODER · COMPARED WITH PCA",
  "ÖZELLİK ÖNEMİ": "FEATURE IMPORTANCE",
  "PCA (kalın)": "PCA (thick)",
  "PCA ya göre": "compared with PCA",
  "PERMÜTASYON ÖNEMİ (test MSE artışı)": "PERMUTATION IMPORTANCE (rise in test MSE)",
  "SIRALAMA  DOĞRU": "RANKING  CORRECT",
  "sinyal patladı": "the signal exploded",
  "toplam talimat örneği": "total instruction examples",
  "turuncu: LLM · her çağrıda öde": "orange: the LLM · pay on every call",
  "Üstünde küçük model her zaman ucuz ve fark": "Above it the small model is always cheap and the gap",
  "yeniden kurma hatası": "reconstruction error",
  "yeşil: küçük model · etiket + neredeyse sıfır": "green: the small model · labels + almost zero",
  "ADİLLİK · AYNI EŞİK, AYNI MODEL": "FAIRNESS · THE SAME THRESHOLD, THE SAME MODEL",
  "AI PROJESİ KARARI · ALARMLARIN KAÇI BOŞ": "AI PROJECT DECISION · HOW MANY ALARMS ARE EMPTY",
  "AI PROJESİ KARARI · MODEL PARA KAZANDIRIYOR MU": "AI PROJECT DECISION · DOES THE MODEL MAKE MONEY",
  "ALANA ÖZEL MODEL · UZMAN MI, GENELCİ Mİ": "A DOMAIN SPECIFIC MODEL · SPECIALIST OR GENERALIST",
  "alanlar arası": "across domains",
  "ALDIĞI BÜTÇE": "THE BUDGET IT GETS",
  "ALGORİTMA SADIK DAVRANIYOR": "THE ALGORITHM BEHAVES FAITHFULLY",
  "aynı eşik, aynı ayırt etme gücü.": "the same threshold, the same discriminative power.",
  "AYNI MODEL, FARKLI SONUÇ": "THE SAME MODEL, A DIFFERENT RESULT",
  "Aynı veri, aynı adım sayısı. Ölçülen şey eğitim kaybı, yani aşırı uyum değil.": "The same data, the same number of steps. What is measured is the training loss, so this is not overfitting.",
  "Az alan verisiyle genelci önde: genel veri": "With little domain data the generalist leads: the general data",
  "AZ VERİDE GENELCİ, ÇOK VERİDE UZMAN": "THE GENERALIST WITH LITTLE DATA, THE SPECIALIST WITH A LOT",
  "bile pozitiflerin tamamını sayıca eziyor.": "outnumbers all the positives put together.",
  "BİRLEŞME": "MERGE",
  "birleşme bütçesinden pay alamıyorlar.": "they get no share of the merge budget.",
  "birleşme sayısı": "number of merges",
  "Birleşme sayısı arttıkça doğal dil hızla": "As the number of merges grows natural language",
  "birleşmeyi seçer. Kazanç sıklıkla ölçülür, sıklık": "merge. The gain is measured by frequency, and frequency",
  "boş alarm oranı": "empty alarm rate",
  "BOŞ ALARM ORANI": "EMPTY ALARM RATE",
  "boşluğu dolduruyor.": "fills the gap.",
  "BOŞUNA MÜDAHALE": "WASTED INTERVENTION",
  "BPE açgözlüdür: her adımda en çok kazandıran": "BPE is greedy: at every step it picks the most rewarding",
  "BPE her adımda en sık geçen çifti birleştirir. Sıklığı korpus payı belirler.": "BPE merges the most frequent pair at every step. The frequency is set by the share of the corpus.",
  "bütçe payı": "share of the budget",
  "ÇOK DİLLİ KÖR NOKTA · BİRLEŞME BÜTÇESİ ÇOĞUNLUĞA GİDİYOR": "THE MULTILINGUAL BLIND SPOT · THE MERGE BUDGET GOES TO THE MAJORITY",
  "Çünkü öğretilen şey işlem değil, hangi işlemin": "Because what is taught is not the operation but the address that says which operation",
  "da korpus payıyla gelir.": "comes from the corpus share as well.",
  "DERİNLİKLE NE OLUYOR": "WHAT HAPPENS WITH DEPTH",
  "DOĞAL DİL": "NATURAL LANGUAGE",
  "Doğruluk beşinci sayıdır ve tek başına hiçbir şey": "Accuracy is the fifth number and on its own it says",
  "Dört sayı yeter: olayın taban oranı, kaçırmanın": "Four numbers are enough: the base rate of the event, the cost of a miss,",
  "düz": "solid",
  "DÜZ AĞ KAYBI": "PLAIN NETWORK LOSS",
  "GERÇEK OLAY": "THE REAL EVENT",
  "gerçekten dolandırıcı": "really fraudulent",
  "gruba göre değişiyor. Model ayrımcılık yapmıyor.": "varies by group. The model is not discriminating.",
  "Hata oranları da eşit: FPR ve FNR farkı sıfır.": "The error rates are equal too: the FPR and FNR difference is zero.",
  "hedef alandan örnek sayısı": "number of examples from the target domain",
  "İki grup için skor dağılımları birebir aynı. Tek fark taban oranları.": "The score distributions of the two groups are identical. The only difference is their base rates.",
  "İNGİLİZCE PAYI": "SHARE OF ENGLISH",
  "istendiğini söyleyen adres.": "is wanted.",
  "kaç kişinin gerçekten dolandırıcı olduğu.": "how many people are really fraudulent.",
  "KARAR BİR DOĞRULUK DEĞİL, BİR ARİTMETİK": "THE DECISION IS NOT AN ACCURACY BUT AN ARITHMETIC",
  "kısayol": "shortcut",
  "KISAYOL · DERİNLİK EĞİTİMİ ZORLAŞTIRIYOR": "SHORTCUTS · DEPTH MAKES TRAINING HARDER",
  "Kimse azınlık dilini cezalandırmıyor; bu sadece": "Nobody is punishing the minority language; this is simply",
  "Korpus doğal dil ağırlıklı. Sayılar ve kod nadir. Ölçüm görülmeyen kelimelerde.": "The corpus is weighted towards natural language. Numbers and code are rare. The measurement is on unseen words.",
  "korpusta İngilizcenin payı": "the share of English in the corpus",
  "Küçük örnek sayılarında eğriler dalgalı, çünkü": "At small sample sizes the curves are wobbly, because",
  "küme sayısı k": "number of clusters k",
  "log₁₀ eğitim kaybı": "log₁₀ training loss",
  "maliyet modelsizden düşük mü\".": "cost lower than with no model\".",
  "maliyeti, müdahalenin maliyeti, çağrı maliyeti.": "the cost of an intervention, the cost of a call.",
  "Model iki grupta birebir aynı: aynı skor dağılımı,": "The model is identical in both groups: the same score distribution,",
  "MODELLİ MALİYET": "COST WITH THE MODEL",
  "MODELSİZ MALİYET": "COST WITHOUT A MODEL",
  "net kazanç": "net gain",
  "NET KAZANÇ": "NET GAIN",
  "OLASILIK · AYNI MODEL, FARKLI DÜNYA": "PROBABILITY · THE SAME MODEL, A DIFFERENT WORLD",
  "olay nadir olduğu için negatiflerin küçük bir payı": "because the event is rare, even a small share of the negatives",
  "olduğu korpusun bileşiminde yazılıdır.": "is written into the composition of the corpus.",
  "ÖLÇEK MESELESİ DEĞİL": "NOT A MATTER OF SCALE",
  "Ön eğitim milyonlarca örnek istiyor. Talimat": "Pretraining wants millions of examples. Instruction",
  "ÖRNEK  ·  sample  ·  bir satır": "EXAMPLE  ·  sample  ·  one row",
  "seçilme": "selection",
  "sıfır · altı zarar": "zero · below it a loss",
  "sıklığa bakan bir sayacın doğal sonucu.": "the natural consequence of a counter that looks at frequency.",
  "Soru \"model yeterince iyi mi\" değil, \"modelli": "The question is not \"is the model good enough\" but \"is the",
  "söylemez.": "nothing.",
  "SÖZLÜK KİME BÜYÜYOR": "WHO THE VOCABULARY GROWS FOR",
  "SVAHİLİ": "SWAHILI",
  "TABAN · DOĞRULUK": "BASELINE · ACCURACY",
  "TALİMAT AYARI · TOPLAM BÜTÇE": "INSTRUCTION TUNING · TOTAL BUDGET",
  "TOKENIZER FARKI · SÖZLÜK BÜYÜDÜKÇE KİM KAZANIYOR": "TOKENISER GAP · WHO GAINS AS THE VOCABULARY GROWS",
  "TÜRKÇE": "TURKISH",
  "Yani \"pozitif\" dediğinde haklı çıkma oranın": "So the rate at which you are right when you say \"positive\"",
  "YÜKSEK DOĞRULUK, BOŞ ALARM DENİZİ": "HIGH ACCURACY, A SEA OF EMPTY ALARMS",
  "AÇIK MI KAPALI MI · ASIL BELİRLEYİCİ KULLANIM ORANI": "OPEN OR CLOSED · THE REAL DETERMINANT IS UTILISATION",
  "açıklanan oran": "share explained",
  "Ağırlıklar hiç değişmiyor. Değişen tek şey hangi görevde olduğuna dair inanç.": "The weights never change. The only thing that changes is the belief about which task it is on.",
  "alt sınıra göre": "against the lower bound",
  "API de kullandığın kadar ödersin; kendi": "With an API you pay for what you use; with self",
  "AYLIK HACİM": "MONTHLY VOLUME",
  "BAĞLAM İÇİ ÖĞRENME · SONSAL DAĞILIM KESKİNLEŞİYOR": "IN-CONTEXT LEARNING · THE POSTERIOR SHARPENS",
  "barındırmada kapasitenin tamamını ödersin.": "hosting you pay for all the capacity.",
  "BİLGİ OLARAK BEDELİ": "THE COST IN INFORMATION",
  "Birinci ile ikinci arasındaki fark ölçüm hatasından": "If the gap between first and second is smaller than the measurement error,",
  "BİRİNCİLİK BİR ÖLÇÜM DEĞİL": "BEING FIRST IS NOT A MEASUREMENT",
  "BOŞ KAPASİTE DOĞRUDAN ZARAR": "IDLE CAPACITY IS A DIRECT LOSS",
  "Bu sayı eğitimle değil, kapalı formda": "This number was computed in closed form rather than by training:",
  "çağrı) hem aşağı iniyor (daha az doğruluk).": "calls) and downwards (less accuracy).",
  "ÇIKTI BOYU": "OUTPUT LENGTH",
  "çünkü doğrusu seçenekler arasında yok.": "because the right one is not among the options.",
  "DAL TEPESİNDE": "AT THE TOP OF THE BRANCH",
  "DEĞER SAYISI": "NUMBER OF VALUES",
  "Eğri log ölçekte düz iniyor: maliyet hacme değil,": "The curve falls in a straight line on a log scale: the cost depends on capacity rather than volume,",
  "EMİN OLMAK DOĞRU OLMAK DEĞİL": "BEING CONFIDENT IS NOT BEING RIGHT",
  "En iyi tek Gauss, gerçek karışıma göre": "The best single Gaussian, compared with the true mixture",
  "evrişim çıktısı": "convolution output",
  "f büyüdükçe eğri hem sağa kayıyor (daha çok": "As f grows the curve moves right (more",
  "GERÇEK FARK": "TRUE DIFFERENCE",
  "gerçek yoğunluk": "true density",
  "gerçek yoğunluk (karışım)": "true density (a mixture)",
  "gerçekten hasta": "really ill",
  "Görülmeyen görevde de sonsal keskinleşiyor:": "The posterior sharpens on an unseen task too:",
  "HAVUZLAMA · ÖZET ÇIKARMAK": "POOLING · EXTRACTING A SUMMARY",
  "HAVUZLAMANIN PARAMETRESİ YOK": "POOLING HAS NO PARAMETERS",
  "her çağrıda taşınan tur": "turns carried on every call",
  "hesaplandı: hiçbir eğitim bunu kapatamaz.": "no amount of training can close it.",
  "iki katı hatırlama iki katı bağlam demek.": "twice the recall means twice the context.",
  "KAÇ KAT AZALDI": "HOW MANY TIMES SMALLER",
  "kaç kat olası": "how many times more likely",
  "kaç kişinin gerçekten hasta olduğu.": "how many people are really ill.",
  "KAÇ σ UZAKTA": "HOW MANY σ AWAY",
  "kapasiteye bağlı olduğu için hacim onu böler.": "so the volume divides it.",
  "KARIŞIM YOĞUNLUK · TEK GAUSS NEYİ KAYBEDER": "A MIXTURE DENSITY · WHAT A SINGLE GAUSSIAN LOSES",
  "kaynağın entropisi": "entropy of the source",
  "kazanan doğru mu": "is the winner right",
  "KAZANAN DOĞRU MU": "IS THE WINNER RIGHT",
  "Kendi barındırmada donanımı kirala ya da kirala, ödersin. Boş kapasite doğrudan zarardır.": "With self hosting you pay for the hardware whether you use it or not. Idle capacity is a direct loss.",
  "komşu modeller arası gerçek fark": "true gap between neighbouring models",
  "KONUŞMA HAFIZASI · HATIRLAMA BAŞINA BAĞLAM": "CONVERSATION MEMORY · CONTEXT PER UNIT OF RECALL",
  "konuşma uzadıkça düşmüyor.": "does not fall as the conversation grows.",
  "kuralıdır. Maks en büyüğü, ortalama hepsinin": "rule. Max takes the largest and mean takes the average of",
  "küçükse, sıralamanın bir anlamı yoktur.": "the ranking means nothing.",
  "M TOKEN BAŞINA": "PER M TOKENS",
  "MERTEBEYE GÖRE": "BY ORDER OF MAGNITUDE",
  "o kadar az çarpma yapar.": "it does that few multiplications.",
  "ortalamasını alır.": "all of them.",
  "Öğrenilecek ağırlık içermez: sadece bir özet": "It contains no weights to learn: it is only a summary",
  "ÖZETİN DENGİ": "THE EQUIVALENT OF THE SUMMARY",
  "pencere alanı kadar": "as many as the window area",
  "Pencerede hatırlama taşınan turla doğru orantılı:": "With a window, recall is directly proportional to the turns carried:",
  "PERPLEXITY · MODEL KAÇ SEÇENEK ARASINDA ŞAŞIRIYOR": "PERPLEXITY · AMONG HOW MANY OPTIONS THE MODEL IS UNSURE",
  "RASTGELE SEÇSEN": "IF YOU PICKED AT RANDOM",
  "SKOR TABLOSU · KAZANAN GERÇEKTEN EN İYİ Mİ": "LEADERBOARD · IS THE WINNER REALLY THE BEST",
  "SONSAL ENTROPİ": "POSTERIOR ENTROPY",
  "TEORİK ALT SINIR": "THEORETICAL LOWER BOUND",
  "ters alma güvenilmez": "inversion is unreliable",
  "toplam model çağrısı": "total model calls",
  "turuncu: kendi barındırmada M token başına maliyet": "orange: the cost per M tokens with self hosting",
  "ve kararından emin. Ama seçtiği görev yanlış,": "and is confident in its decision. But the task it chose is wrong,",
  "Yani model hangi görevde olduğuna karar veriyor": "So the model decides which task it is on",
  "YANLIŞ ALARM İKİ KERE ÖDETİYOR": "A FALSE ALARM MAKES YOU PAY TWICE",
  "Yatay eksen her çağrıda taşınan tur sayısı, dikey eksen genel hatırlama.": "The horizontal axis is the turns carried on every call and the vertical axis the overall recall.",
  "yetersiz uyum: yanlılık büyük, modeller birbirine benziyor": "underfitting: the bias is large and the models resemble each other",
  "ZİNCİRLEME PROMPT · DOĞRULUK KAÇ ÇAĞRIYA MAL OLUYOR": "PROMPT CHAINING · HOW MANY CALLS ACCURACY COSTS",
  "AJAN DÖNGÜSÜ": "THE AGENT LOOP",
  "AKTİF ÖĞRENME · HANGİ ÖRNEĞİ ETİKETLEYELİM": "ACTIVE LEARNING · WHICH EXAMPLE SHOULD WE LABEL",
  "ARAÇ SEÇ": "PICK A TOOL",
  "Bağlam taşırma": "Context overflow",
  "BİR DİL MODELİ NASIL EĞİTİLİR?": "HOW IS A LANGUAGE MODEL TRAINED?",
  "ceza güçlü, model fazla basitleşti (yetersiz uyum)": "the penalty is strong and the model got too simple (underfitting)",
  "Doğrudan talimat": "Direct instruction",
  "düz RNN": "plain RNN",
  "ETİKET PAHALIYSA HANGİSİNİ SORARSIN": "IF LABELS ARE EXPENSIVE, WHICH ONE DO YOU ASK ABOUT",
  "geri düşmüyor: genel veri artık engel.": "does not fall back: the general data is now a hindrance.",
  "getirir. Belirsizlik örneklemesi ise modelin en": "brings the typical examples of the pool. Uncertainty sampling asks for the ones the model is most",
  "GÖSTERİLEN  hepsi": "SHOWN  all",
  "GÖZETİMLİ İNCE AYAR": "SUPERVISED FINE-TUNING",
  "gürültü sınırı": "noise limit",
  "Her turda en büyük kalan sayı, dizinin sonuna “kabarıyor”.": "On every pass the largest remaining number \"bubbles\" to the end of the list.",
  "hesap gücü": "compute",
  "İNSAN GERİ BİLDİRİMİ": "HUMAN FEEDBACK",
  "kararsız olduğu, yani sınıra en yakın örneği ister.": "unsure about, that is the ones nearest the boundary.",
  "Kazanç var ama sihirli değil: aynı doğruluğa": "There is a gain but it is not magic: the same accuracy",
  "Kullanıcı \"geçen ayki satış toplamı\" istedi. Veritabanına so…": "The user asked for \"last month's total sales\". Query the datab…",
  "MALİYET": "COST",
  "Model tek seferde cevap vermez, düşünür, araç çağırır, sonucu görür, tekrar düşünür.": "The model does not answer in one go: it thinks, calls a tool, sees the result and thinks again.",
  "ÖN-EĞİTİM": "PRETRAINING",
  "ÖRNEK": "EXAMPLE",
  "POZİTİF PAYI": "POSITIVE SHARE",
  "Rastgele örnekleme havuzun tipik örneklerini": "Random sampling",
  "softmax → ağırlıklar": "softmax → weights",
  "Sonucu aldım. Kullanıcı karşılaştırma da istemişti, bir sorg…": "I got the result. The user also wanted a comparison, one more…",
  "sql_sorgu(...)  seçildi": "sql_query(...)  selected",
  "Üç aşama. Bilginin neredeyse tamamı ilkinde, davranışın tamamı son ikisinde.": "Three stages. Almost all the knowledge is in the first and all the behaviour in the last two.",
  "ÜÇ AŞAMANIN PAYI": "THE SHARE OF THE THREE STAGES",
  "veri miktarı": "amount of data",
  "yaklaşık iki kat az etiketle ulaşılıyor, yüz kat değil.": "is reached with about half as many labels, not a hundredth.",
  "yüksek T → dağılım düzleşti, alakasız token'lar da gelebilir": "high T → the distribution flattened and irrelevant tokens can turn up",
  "AĞACIN YAPRAĞI": "THE TREE'S LEAF",
  "ağaç (derinlik arttıkça)": "tree (as the depth grows)",
  "Ağaç etkileşimi kendi keşfedebilir. Sorusu kaç bölünme karşılığında.": "A tree can discover the interaction itself. The question is at the cost of how many splits.",
  "AĞAÇ ÖLÇEKTEN ETKİLENİR Mİ": "IS A TREE AFFECTED BY SCALE",
  "AĞAÇ RMSE": "TREE RMSE",
  "AĞAÇ TEST R²": "TREE TEST R²",
  "Aynı ağ, aynı veri, aynı öğrenme oranı. Tek fark gradyan normunun kesilip kesilmediği.": "The same network, the same data, the same learning rate. The only difference is whether the gradient norm is clipped.",
  "AYNI KOŞU TEKRARLANABİLİR Mİ": "IS THE SAME RUN REPRODUCIBLE",
  "aynı sayı. Bölünme eşik arar, mesafe değil.": "the same number. A split looks for a threshold, not a distance.",
  "AYNI YÖNTEMLE DEVAM EDERSEK": "IF WE CARRY ON WITH THE SAME METHOD",
  "BİR ŞEHİR DAHA": "ONE MORE CITY",
  "Bütün turları tek tek deniyoruz. Şehir sayısını bir artır, işe bak.": "We try every tour one by one. Add one city and look at the work.",
  "ÇEKİRDEK": "KERNEL",
  "Çok adımlı": "Multi-step",
  "doğrusal": "linear",
  "DOĞRUSAL + EN×BOY": "LINEAR + WIDTH×LENGTH",
  "Dolaylı enjeksiyon": "Indirect injection",
  "EVRİŞİM  ·  CONVOLUTION": "CONVOLUTION",
  "FİLTRE  dikey kenar": "FILTER  vertical edge",
  "GÖREV": "TASK",
  "kaç ayrı bölge": "how many distinct regions",
  "KLİPLENEN ADIM": "STEPS CLIPPED",
  "KLİPLİ SON KAYIP": "FINAL LOSS WITH CLIPPING",
  "KLİPSİZ SON KAYIP": "FINAL LOSS WITHOUT CLIPPING",
  "Kodlama / şifreleme": "Encoding / ciphering",
  "KOMBİNATORİK · GEZGİN SATICI": "COMBINATORICS · THE TRAVELLING SALESMAN",
  "Komşu çiftleri karşılaştırır, ters olanı takas eder, büyükler sona “kabarır”.": "It compares neighbouring pairs, swaps the ones out of order, and the large ones \"bubble\" to the end.",
  "Küçük bir filtre görüntüde geziyor ve her yerde aynı örüntüyü arıyor.": "A small filter travels over the image looking for the same pattern everywhere.",
  "ÖĞRENME ORANI": "LEARNING RATE",
  "ÖZELLİK MÜHENDİSLİĞİ · MODEL KENDİ ÖĞRENİR Mİ": "FEATURE ENGINEERING · CAN THE MODEL LEARN IT ITSELF",
  "PATLAYAN GRADYAN · KLİPLEME": "EXPLODING GRADIENTS · CLIPPING",
  "sarı: başlangıç şehri": "yellow: the starting city",
  "ŞEHİR SAYISI": "NUMBER OF CITIES",
  "tamamen değişmez": "does not change at all",
  "tur sayısı bu kadar artar": "the number of tours grows by this much",
  "yeşil: bulunan en kısa tur": "green: the shortest tour found",
  "\"ilk\" en zoru: \"en büyük\" ve \"en küçük\" ile": "\"first\" is the hardest: unlike \"largest\" and \"smallest\"",
  "AÇGÖZLÜ · sadece sezgi": "GREEDY · heuristic only",
  "ağaç": "tree",
  "AĞIRLIKLAR  ·  yeşil + · kırmızı −  ·  kalınlık = büyüklük": "WEIGHTS  ·  green + · red −  ·  thickness = magnitude",
  "Aşağıdaki faturayı incele ve KDV tutarını çı…": "Examine the invoice below and extract the VAT amo…",
  "Aykırı ağırlık duruyor. Tek fark: ölçek tensörün tamamı için mi, her satır için mi.": "The outlier weight is still there. The only difference: is the scale for the whole tensor or for every row.",
  "aykırı ağırlık yok": "no outlier weight",
  "AYKIRIYI KENDİ SATIRINA HAPSET": "CONFINE THE OUTLIER TO ITS OWN ROW",
  "Aynı ağ, her kare biraz daha öğreniyor. Renkli bölge = modelin kararı.": "The same network, learning a little more every frame. The coloured region = the model's decision.",
  "Aynı görev, iki yol: cevabı ezberlemek ya da tek adımı öğrenip tekrarlamak.": "The same task, two routes: memorise the answer or learn a single step and repeat it.",
  "Aynı rastgele arama, sadece uzay daraltıldı.": "The same random search, only the space was narrowed.",
  "bağlam etiketleme": "context labelling",
  "Bedeli neredeyse yok: satır başına iki sayı daha": "The cost is almost nothing: two more numbers per row",
  "BİR AĞIRLIK HERKESİ CEZALANDIRIYOR": "ONE WEIGHT PUNISHES EVERYBODY",
  "birkaç örnekte bitiyor.": "it is over in a few examples.",
  "bu aralığı gerdiği için adım büyür ve DİĞER": "stretches that range, so the step grows and ALL THE OTHER",
  "bütün ağırlıklar hassasiyet kaybeder.": "weights lose precision.",
  "Cevap adım adım gidilerek bulunamıyor. Zincir yazmak hiçbir şey kazandırmıyor.": "The answer cannot be reached step by step. Writing a chain gains nothing.",
  "CoT / doğrudan": "CoT / direct",
  "CoT hiçbir eğitim miktarında ilerlemiyor:": "CoT makes no progress at any amount of training:",
  "Çıktı: {\"kdv_tutari\": sayı, \"oran\": sayı}": "Output: {\"vat_amount\": number, \"rate\": number}",
  "çiftine atanmış rastgele bir değer.": "pair.",
  "DOĞRUSAL": "LINEAR",
  "DÜŞÜNME ZİNCİRİ · AYRIŞMAYAN GÖREV": "CHAIN OF THOUGHT · A TASK THAT DOES NOT DECOMPOSE",
  "DÜŞÜNME ZİNCİRİ · KAÇ OLGU ÖĞRENMEK GEREKİYOR": "CHAIN OF THOUGHT · HOW MANY FACTS HAVE TO BE LEARNED",
  "en büyük] aralığı kullanır. Tek bir aykırı değer": "largest] range. A single outlier",
  "EN ÇOK İŞE YARAYAN SIRA": "THE MOST EFFECTIVE ORDER",
  "hassasiyeti bozar. Diğer satırlar etkilenmez.": "precision of its own row. The other rows are unaffected.",
  "Hedef artık f’in tekrarı değil, (durum, sayı)": "The target is no longer a repetition of f but a random value assigned to a (state, number)",
  "Her satır kendi [en küçük, en büyük] aralığını": "Every row uses its own [smallest, largest] range,",
  "ıraksadı": "diverged",
  "imkânsız": "impossible",
  "İyi bir prompt yazı değil, YAPIDIR. Altı parça.": "A good prompt is not prose but a STRUCTURE. Six parts.",
  "KAÇ OLGU": "HOW MANY FACTS",
  "kısıt / kaynak zorunluluğu": "constraints / required sources",
  "kitapları": "kitapları",
  "KUANTİZASYON · ÖLÇEĞİ NEREDE TANIMLARSIN": "QUANTISATION · WHERE DO YOU DEFINE THE SCALE",
  "KUANTİZASYON · TEK BİR AYKIRI AĞIRLIK": "QUANTISATION · A SINGLE OUTLIER WEIGHT",
  "kullanırsa, aykırı değer sadece kendi satırındaki": "so an outlier only ruins the",
  "kurabiliyor. Ağaç aynı şeyi basamaklarla deniyor.": "can build it. The tree tries the same thing with steps.",
  "Model işlemi sıfırdan öğrenmiyor: örneklerle": "The model does not learn the operation from scratch: with examples",
  "NEDEN BU KADAR AZ ÖRNEK YETİYOR": "WHY SO FEW EXAMPLES ARE ENOUGH",
  "net görev + format": "a clear task + a format",
  "o talimattan görülen örnek sayısı": "examples seen of that instruction",
  "oy sayısı K": "number of votes K",
  "PROMPT ANATOMİSİ": "THE ANATOMY OF A PROMPT",
  "Prompt enjeksiyonu çözülmüş bir problem değil. Savunma tek katman değil, KATMANLAR.": "Prompt injection is not a solved problem. The defence is not one layer but LAYERS.",
  "rol tanımı": "a role definition",
  "SALDIRI TÜRLERİ": "TYPES OF ATTACK",
  "saldırıyı sonradan görebilmek": "being able to see the attack afterwards",
  "satır (kanal) bazında ölçek": "a scale per row (channel)",
  "SAVUNMA KATMANLARI  ·  tek başına hiçbiri yetmez": "LAYERS OF DEFENCE  ·  none of them is enough alone",
  "Sen bir Türk vergi mevzuatı uzmanısın.": "You are an expert in Turkish tax legislation.",
  "SİNİR AĞI EĞİTİLİYOR": "A NEURAL NETWORK BEING TRAINED",
  "sondan uzaklık (adım)": "distance from the end (steps)",
  "şema + içerik kontrolü": "schema + content checking",
  "TALİMAT AYARI · TALİMAT BAŞINA KAÇ ÖRNEK": "INSTRUCTION TUNING · HOW MANY EXAMPLES PER INSTRUCTION",
  "talimat başına": "per instruction",
  "TENSÖR BAZINDA": "PER TENSOR",
  "Tensör bazında kuantalama tek bir [en küçük,": "Per tensor quantisation uses a single [smallest,",
  "tensör bazında tek ölçek": "a single scale per tensor",
  "toplamsal eksi ağaç": "additive minus tree",
  "TOPLAMSAL MODEL · ESNEKLİK KARŞILAŞTIRMASI": "ADDITIVE MODEL · A COMPARISON OF FLEXIBILITY",
  "Toplamsal model bunu bildiği için pürüzsüz eğri": "The additive model knows this, so it",
  "UZAY, ALGORİTMADAN ÖNEMLİ": "THE SPACE MATTERS MORE THAN THE ALGORITHM",
  "VERİ GERÇEKTEN TOPLAMSAL": "THE DATA REALLY IS ADDITIVE",
  "Veri gerçekten toplamsalsa, toplamsal varsayım bedava doğruluk demektir.": "If the data really is additive, the additive assumption means free accuracy.",
  "yıkıcı işlemlerde zorunlu": "mandatory for destructive operations",
  "ZİNCİR NEDEN İŞE YARAMIYOR": "WHY THE CHAIN DOES NOT WORK",
  "\"Geçerli olanlar arasından modelin dağılımı\"": "\"The model's distribution among the valid ones\"",
  "A kabındaki litre →": "litres in jug A →",
  "A YA EĞİLİM": "LEANING TOWARDS A",
  "AÇILAN DÜĞÜM": "NODES EXPANDED",
  "AI YIĞINI · KATMANI HIZLANDIRMAK YERİNE ATLAMAK": "THE AI STACK · SKIPPING A LAYER INSTEAD OF SPEEDING IT UP",
  "alanlar arası açı": "angle between domains",
  "Amdahl sınırı bir katmanı hızlandırmak için": "Amdahl's limit applies to speeding a layer up.",
  "ARAMA UZAYI · DURUM VE GEÇİŞ": "THE SEARCH SPACE · STATES AND TRANSITIONS",
  "atılan yöndeki bilgiyi geri getirilemez şekilde siler.": "irrecoverably erases the information in the discarded direction.",
  "Aynı mimari, tek fark hangi konumların birbirini görebildiği.": "The same architecture; the only difference is which positions can see each other.",
  "Az görevle öğrenilen temsil, bol veriyle bile aşılamayan bir sınır koyuyor.": "A representation learned from few tasks sets a limit that even plenty of data cannot pass.",
  "AZ ÖRNEK, AYNI SONUÇ": "FEW EXAMPLES, THE SAME RESULT",
  "BASKIN GÖREV": "DOMINANT TASK",
  "Baskın görevi değiştir: zirve onunla birlikte": "Change the dominant task and the peak moves with it.",
  "Bedava değil: sonraki adımda bedelini ölçeceğiz.": "It is not free: we measure the price in the next step.",
  "Bedelini sıradaki adımlar ölçüyor.": "The next steps measure the price.",
  "belge başına tahmin": "prediction per document",
  "BELGE UZUNLUĞU": "DOCUMENT LENGTH",
  "BN yok: bu ölçekte şanslıyız. Ama ölçeği azıcık kaydır, her şey bozuluyor.": "No BN: we are lucky at this scale. But shift the scale a little and everything breaks.",
  "bölen küçük olur ve o yol şişer.": "the divisor is small and that path inflates.",
  "Bu yüzden RNN her uzunluktaki diziyi aynı modelle işleyebilir. Bedeli, bütün geçmişi": "This is why an RNN can process a sequence of any length with the same model. The price is carrying the whole history",
  "BÜYÜK TEST KÜMESİ ÇÖZÜM AMA UCUZ DEĞİL": "A LARGE TEST SET IS A SOLUTION BUT NOT A CHEAP ONE",
  "cevap veriyor ve o cevabı korpusta en sık geçen": "answers and the most frequent",
  "ÇİFT YÖNLÜ": "BIDIRECTIONAL",
  "çift yönlü / nedensel": "bidirectional / causal",
  "çözücü · nedensel": "decoder · causal",
  "DAR GEÇİT KURALI": "THE NARROW PASSAGE RULE",
  "değil temsilin körlüğü.": "not the data but the blindness of the representation.",
  "DİKKAT MASKESİ · KİM KİMİ GÖREBİLİR": "THE ATTENTION MASK · WHO CAN SEE WHOM",
  "dilbilgisi aynı dilbilgisi.": "the grammar is the same grammar.",
  "DİLBİLGİSİ KISITI · İKİ YOL, İKİ FATURA": "GRAMMAR CONSTRAINTS · TWO ROUTES, TWO BILLS",
  "DİLBİLGİSİ KISITI · KISITLI ÇÖZÜMLEME, KOŞULLAMA DEĞİLDİR": "GRAMMAR CONSTRAINTS · CONSTRAINED DECODING IS NOT CONDITIONING",
  "DİLBİLGİSİ KISITI · SERBEST ÜRETİM KALIBI TUTTURAMIYOR": "GRAMMAR CONSTRAINTS · FREE GENERATION CANNOT HIT THE PATTERN",
  "DİLBİLGİSİ KISITI · ŞİŞME NEREDEN GELİYOR": "GRAMMAR CONSTRAINTS · WHERE THE INFLATION COMES FROM",
  "dizi uzunluğu T": "sequence length T",
  "durum ileri taşınıyor · her okta AYNI W matrisi var": "the state is carried forward · every arrow has the SAME W matrix",
  "EĞİTİM KAYBI": "TRAINING LOSS",
  "EN ÇOK SÖNEN": "MOST SUPPRESSED",
  "EN ÇOK ŞİŞEN": "MOST INFLATED",
  "EN HIZLI ÇAĞRI YAPILMAYAN ÇAĞRIDIR": "THE FASTEST CALL IS THE ONE NOT MADE",
  "EN KISA ÇÖZÜM": "SHORTEST SOLUTION",
  "EN KÖTÜ GÖREV": "WORST TASK",
  "Fark hesapta değil, görülen bilgide.": "The difference is not in the computation but in the information seen.",
  "geçerli": "valid",
  "geçerlidir. Katmanı tamamen atlarsan o sınır": "If you skip the layer entirely that limit",
  "geçerlilik olasılığı": "probability of validity",
  "GEÇERSİZ": "INVALID",
  "GERİ  ← hata": "BACKWARD  ← error",
  "GERİ YAYILIM": "BACKPROPAGATION",
  "görev belirliyor.": "task in the corpus determines it.",
  "GÖREV SAYISI": "NUMBER OF TASKS",
  "Görev: dizinin ilk sayısını T adım sonra hatırlamak. Ölçülen şey test kaybı.": "The task: recall the first number of the sequence T steps later. What is measured is the test loss.",
  "görünür çift": "visible pairs",
  "h ← tanh(W h + u x). Aynı W her adımda tekrar uygulanıyor.": "h ← tanh(W h + u x). The same W is applied again at every step.",
  "Hata çıktıdan girdiye doğru akar; her ağırlık kendi payını öğrenir.": "The error flows from the output to the input; every weight learns its own share.",
  "Her adımda geçersiz devamları maskelersen çıktı": "Mask the invalid continuations at every step and the output",
  "Her adımda maskeleme bir miktar olasılık kütlesi": "Masking at every step removes some probability mass",
  "Her parça sırayla test olur. Tek bölünmenin şansına bağlı kalmazsın.": "Every part becomes the test in turn. You do not depend on the luck of a single split.",
  "her zaman geçerli": "always valid",
  "iki dağılım arası": "between the two distributions",
  "İKİ FARKLI ŞEY": "TWO DIFFERENT THINGS",
  "ile \"her adımda geçersizleri eleyip yeniden": "and \"eliminating the invalid ones at every step and",
  "İLERİ  tahmin →": "FORWARD  prediction →",
  "İLERİ BESLEMELİ OLSA": "IF IT WERE FEEDFORWARD",
  "İSABET ORANI": "HIT RATE",
  "İYİ TEMEL ZEMİN, KÖTÜ TEMEL TAVAN": "A GOOD BASE IS A FLOOR, A BAD BASE IS A CEILING",
  "İzdüşüm alınca o yöndeki bilgi tamamen siliniyor.": "Projecting erases the information in that direction entirely.",
  "K-KAT ÇAPRAZ DOĞRULAMA": "K-FOLD CROSS VALIDATION",
  "KALIBI GARANTİ ETMENİN KOLAY YOLU": "THE EASY WAY TO GUARANTEE THE PATTERN",
  "kalkar, çünkü artık payı da düşüyor.": "goes away, because its share falls too.",
  "Kazanç modelin büyüklüğünden değil, aranacak": "The gain comes not from the size of the model but from the shrinking of the space",
  "KENDİ KENDİNE GÖZETİM · NE KADAR HAM VERİ GEREKİYOR": "SELF SUPERVISION · HOW MUCH RAW DATA IS NEEDED",
  "kırmızı: şişme = P(geçerli) / ΠZ": "red: inflation = P(valid) / ΠZ",
  "Klipsiz koşu kaotik: sonucu son bitteki": "The unclipped run is chaotic: its result depends even on the rounding of the last bit.",
  "kodlayıcı · çift yönlü": "encoder · bidirectional",
  "Konu başına tek etiket. Değişen tek şey belge uzunluğu.": "One label per topic. The only thing that changes is the document length.",
  "log₁₀ belge uzunluğu": "log₁₀ document length",
  "Maskeleme dar geçitlerden geçen dizileri şişiriyor. Kırmızı eğri tam formül.": "Masking inflates the sequences that pass through narrow passages. The red curve is the exact formula.",
  "mavi: p(x | geçerli)": "blue: p(x | valid)",
  "Model bir şeyde iyi değil, sadece varsayılanı öyle.": "The model is not good at one thing; that is just its default.",
  "Model eğilimi arttıkça geçerlilik düşüyor ve": "As the model's leaning grows, validity falls and",
  "Model sayısı ise şişmeyi büyütür ve skor tablosunda": "The number of models grows the inflation, and on a leaderboard",
  "model sayısını sen kontrol etmiyorsun.": "you do not control the number of models.",
  "nedenselin tam iki katı bağlantı görüyor.": "sees exactly twice as many connections as the causal one.",
  "normalize etmek\" aynı şey değil.": "renormalising\" are not the same thing.",
  "O GÖREVDE": "ON THAT TASK",
  "olası sembolü seçe seçe AAAAA üretiyor ve bu geçersiz.": "likely symbol at every step, producing AAAAA, which is invalid.",
  "olasılık": "probability",
  "ORAN NEREYE GİDİYOR": "WHERE THE RATIO GOES",
  "ORTAK YAPI YOKSA TEMSİL DE YOK": "NO SHARED STRUCTURE, NO REPRESENTATION",
  "ORTALAMA GECİKME": "AVERAGE LATENCY",
  "Öğrenilen ağırlıkların baskın yönlerini çıkarınca": "When the dominant directions of the learned weights are removed",
  "ön eğitim görevi sayısı": "number of pretraining tasks",
  "Ön eğitim metninde talimat yok, sadece girdi-çıktı var. Model hangi görevi yaptığını seçemiyor.": "There are no instructions in the pretraining text, only input and output. The model cannot choose which task it is doing.",
  "ön-görev": "pretext task",
  "ÖN-GÖREV DOĞRULUĞU": "PRETEXT TASK ACCURACY",
  "ÖN-GÖREV SİNYALİ": "PRETEXT TASK SIGNAL",
  "önbellek isabet oranı": "cache hit rate",
  "Önbellek isabetinde model çağrısı ve bağlam kurma hiç yapılmıyor.": "On a cache hit the model call and the context building never happen.",
  "ÖNBELLEKSİZ": "WITHOUT CACHE",
  "Reddet-tekrarla doğru dağılımı verir ama pahalıdır. Maskeleme tek çağrıdır ama saptırır.": "Reject and retry gives the right distribution but is expensive. Masking is a single call but it distorts.",
  "RNN · AYNI AĞIRLIKLAR, HER ADIMDA": "RNN · THE SAME WEIGHTS AT EVERY STEP",
  "sadece girdi katmanı": "the input layer only",
  "Sapma ise kaybolmuyor. Tamamen düzgün bir modelde": "The distortion does not go away. Even in a perfectly uniform model",
  "Sebebi basit: eksik bir temsile izdüşüm almak,": "The reason is simple: projecting onto an incomplete representation",
  "SERBEST AÇGÖZLÜ": "FREE GREEDY",
  "Serbest çözümlemede model kuralı bilmiyor: en": "In free decoding the model does not know the rule: it picks the most",
  "sıfırdan eğitmeyi geçiyor.": "beats training from scratch.",
  "sıfırdanın altında": "below training from scratch",
  "sıralama değişimi": "change in ranking",
  "SIRALAMA NE İŞE YARAR?": "WHAT IS SORTING GOOD FOR?",
  "SIRALI  ikiye böle böle": "SORTED  halving each time",
  "SIRALI DİZİ  ·  ikili arama": "A SORTED LIST  ·  binary search",
  "SIRASIZ DİZİ  ·  doğrusal tarama": "AN UNSORTED LIST  ·  linear scan",
  "SKOR TABLOSU · TEST KÜMESİNİ BÜYÜTMEK": "LEADERBOARD · GROWING THE TEST SET",
  "şişme (yüzde puan)": "inflation (percentage points)",
  "şişme = P(geçerli) / ΠZ, makine hassasiyetinde.": "inflation = P(valid) / ΠZ, to machine precision.",
  "şişme oranı": "inflation ratio",
  "T den bağımsız": "independent of T",
  "TALİMAT AYARI · TEMEL MODEL NE YAPIYOR": "INSTRUCTION TUNING · WHAT A BASE MODEL DOES",
  "TEK ZİNCİR": "A SINGLE CHAIN",
  "TEMEL MODEL · AZ ÖRNEKLE YENİ GÖREV": "A FOUNDATION MODEL · A NEW TASK WITH FEW EXAMPLES",
  "TEMEL MODEL · ORTAK YAPI KAÇ GÖREVDE ORTAYA ÇIKIYOR": "A FOUNDATION MODEL · AT HOW MANY TASKS THE SHARED STRUCTURE APPEARS",
  "TEMEL MODEL · ORTAK YAPININ DIŞINDAKİ GÖREV": "A FOUNDATION MODEL · A TASK OUTSIDE THE SHARED STRUCTURE",
  "TEMEL MODEL · ZAYIF TEMEL BİR TAVANDIR": "A FOUNDATION MODEL · A WEAK BASE IS A CEILING",
  "Temel modelin \"temel\" olması bu kesişimden geliyor.": "What makes a foundation model \"foundational\" is that intersection.",
  "temel yok · sıfırdan": "no base · from scratch",
  "TEMSİL, GÖREVLERİN KESİŞİMİDİR": "A REPRESENTATION IS THE INTERSECTION OF THE TASKS",
  "TERS DÖNEN ÇİFT": "PAIRS REVERSED",
  "TEST KÜMESİ": "TEST SET",
  "test kümesi büyüklüğü": "test set size",
  "TOPLAM DEĞİŞİM": "TOTAL CHANGE",
  "turuncu: maskeli çözümleme": "orange: masked decoding",
  "Tüm noktalar tam olarak kırmızı eğrinin üstünde:": "Every point sits exactly on the red curve:",
  "ULAŞILABİLİR": "REACHABLE",
  "UZUNLUĞA GÖRE": "BY LENGTH",
  "UZUNLUĞA GÖRE AÇIKLANAN ORAN": "SHARE EXPLAINED BY LENGTH",
  "Ve önbellek, modeli hızlandırmaktan çok daha ucuz.": "And a cache is far cheaper than speeding the model up.",
  "vermen bir şey değiştirmiyor, çünkü sorun veri": "changes nothing, because the problem is",
  "W MATRİSİ": "THE W MATRIX",
  "Yani sapma modelin değil, dilbilgisinin şeklinden.": "So the distortion comes from the shape of the grammar, not of the model.",
  "Yani uzun dizilerde çift yönlü model,": "So on long sequences the bidirectional model",
  "Yeni görevin yönü öğrenilen altuzaya dik.": "The direction of the new task is perpendicular to the learned subspace.",
  "Yeni görevin yönü, ön eğitim görevlerinin paylaştığı altuzaya dik.": "The direction of the new task is perpendicular to the subspace the pretraining tasks share.",
  "yerin küçülmesinden geliyor.": "to be searched.",
  "YETENEK PROFİLİ = KORPUS PROFİLİ": "THE CAPABILITY PROFILE = THE CORPUS PROFILE",
  "yol boyunca korunan kütle · ΠZ": "the mass preserved along the path · ΠZ",
  "yuvarlamaya bile bağlı. Klipleme bunu kaldırıyor.": "Clipping removes that.",
  "ZİNCİR  ∂L/∂w": "THE CHAIN  ∂L/∂w",
  "\"yalnızca bağlamı kullan, yoksa bilmiyorum": "\"use the context only, otherwise say I do not know",
  "adım başına tekrar hakkı": "retries allowed per step",
  "ADİLLİK · İMKANSIZLIK BİR GÖRÜŞ DEĞİL, BİR DENKLEM": "FAIRNESS · THE IMPOSSIBILITY IS AN EQUATION, NOT AN OPINION",
  "ADİLLİK · PPV Yİ EŞİTLEMEYE ÇALIŞMAK": "FAIRNESS · TRYING TO EQUALISE THE PPV",
  "AĞIRLIK İLKLEME · GERÇEKTEN EĞİTİM": "WEIGHT INITIALISATION · ACTUAL TRAINING",
  "AKTARIM BEDAVA DEĞİL, ÖLÇÜLEBİLİR": "TRANSFER IS NOT FREE, IT IS MEASURABLE",
  "ALANA ÖZEL MODEL · GENEL VERİ NE KADAR BİLGİ TAŞIYOR": "A DOMAIN SPECIFIC MODEL · HOW MUCH INFORMATION GENERAL DATA CARRIES",
  "Ama k büyüdükçe saflık da büyür: her belgeyi": "But purity grows with k: put every document",
  "ara sonuca bakılıyor ve gerekirse tekrarlanıyor.": "the intermediate result is checked and retried if needed.",
  "Aynı ağ, aynı veri, aynı adım sayısı.": "The same network, the same data, the same number of steps.",
  "aynı bağlam penceresi": "the same context window",
  "Aynı bölünmüş zincir, tek farkla: her dikişte": "The same split chain with one difference: at every seam",
  "Aynı BPE, aynı sözlük, aynı bütçe. Parça sayısı dilden dile değişiyor.": "The same BPE, the same vocabulary, the same budget. The number of pieces varies by language.",
  "Aynı eğitilmiş BPE. Kelimelerin hiçbiri eğitim listesinde yok.": "The same trained BPE. None of the words is in the training list.",
  "aynı eşikte": "at the same threshold",
  "aynı genel hatırlama": "the same overall recall",
  "aynı metin için": "for the same text",
  "Aynı ölçüm, aynı görev: çıktının t adım öncesindeki girdiye duyarlılığı.": "The same measurement, the same task: the sensitivity of the output to the input t steps earlier.",
  "Aynı uzunluktaki metin, türüne göre kat kat farklı token ediyor.": "Text of the same length costs many times more tokens depending on its kind.",
  "B grubunun eşiği, PPV si A ile eşitlensin diye kaydırılıyor. Bedeli hata oranlarında.": "Group B's threshold is shifted so that its PPV equals A's. The price is in the error rates.",
  "B grubunun taban oranı": "base rate of group B",
  "B NİN YENİ EŞİĞİ": "B'S NEW THRESHOLD",
  "baskın dile göre": "compared with the dominant language",
  "başa baş": "break even",
  "başlangıcından": "from the start",
  "bir bölge yok, çünkü olgu ya bağlamda ya değil.": "no such region, because the fact is either in the context or not.",
  "Bir olgu T − t özetlemeden geçiyor, yani hatırlama": "A fact passes through T − t summarisations, so recall",
  "BİR ÖLÇÜTÜ DÜZELTMEK DİĞERİNİ BOZUYOR": "FIXING ONE MEASURE BREAKS ANOTHER",
  "bir sapma tesadüfen doğru zincire denk gelebiliyor.": "a deviation can by chance land on the right chain.",
  "boğaz": "bottleneck",
  "BOĞAZ BOYU": "BOTTLENECK SIZE",
  "Boğaz dar olduğu için kopyalayamıyor, sıkıştırmak zorunda. Sıkıştırırken neyin önemli": "Because the bottleneck is narrow it cannot copy and has to compress. While compressing, what matters",
  "bölündüğü için hiçbiri doğruyu geçemiyor.": "is split, so none of them can pass the truth.",
  "Bu bir tasarım tercihi değil, cebirsel bir zorunluluk.": "This is not a design choice but an algebraic necessity.",
  "Bu kurgusal bir korpus: mutlak sayıları değil, mekanizmayı gösteriyor.": "This is a synthetic corpus: it shows the mechanism rather than the absolute numbers.",
/*SON*/
};
