/* ML Academy · tuval etiketleri sözlüğü (TR → EN)
   viz.js içindeki CEV() bu tabloyu kullanır. Sayı içeren metinlerde sayılar
   # ile temsil edilir ve karşılıkta aynı sırayla geri konur.
   Envanteri güncellemek için: node tuval-metin.js eksik   */
var TUVAL_EN = {
  "gürültü": "noise",
  "doğru sınıfa verilen olasılık": "probability given to the correct class",
  "kuş": "bird",
  "doğruluk": "accuracy",
  "ceza gücü λ": "penalty strength λ",
  "köpek": "dog",
  "çalışma saati": "study hours",
  "eğitim": "training",
  "■ çapraz entropi": "■ cross entropy",
  "ÇAPRAZ ENTROPİ  = −log( p(doğru) )": "CROSS ENTROPY  = −log( p(correct) )",
  "emin ve yanlış → ceza patlar": "confident and wrong → the penalty explodes",
  "Ham puanlar olasılığa dönüşür, kayıp yalnızca DOĞRU sınıfa verilen olasılığa bakar.": "Raw scores turn into probabilities; the loss looks only at the probability given to the CORRECT class.",
  "kayıp": "loss",
  "model en çok yanıldığında MSE en az öğrenir": "MSE learns least when the model is most wrong",
  "SOFTMAX ve ÇAPRAZ ENTROPİ": "SOFTMAX AND CROSS ENTROPY",
  "DETERMİNANT": "DETERMINANT",
  "gerçek fonksiyon": "true function",
  "b (kesişim)": "b (intercept)",
  "BU NOKTADAKİ MODEL": "THE MODEL AT THIS POINT",
  "EN İYİ": "BEST",
  "KAYIP HARİTASI": "LOSS MAP",
  "w (eğim)": "w (slope)",
  "ham doğrusal": "raw linear",
  "EĞİTİM RSS": "TRAINING RSS",
  "katsayı değeri": "coefficient value",
  "süt": "milk",
  "SAĞ yaprak": "RIGHT leaf",
  "|DETERMİNANT|": "|DETERMINANT|",
  "gri: özgün şekil": "grey: the original shape",
  "MATRİS": "MATRIX",
  "MATRİS · UZAYA UYGULANAN İŞLEM": "MATRIX · AN OPERATION APPLIED TO SPACE",
  "Matris bir sayı tablosu değil. Her noktayı başka bir noktaya taşıyan bir kural.": "A matrix is not a table of numbers. It is a rule that moves every point to another point.",
  "oranla aynı sayı": "the same number as the ratio",
  "ÖZGÜN ALAN": "ORIGINAL AREA",
  "renkli: dönüşmüş hâli": "colour: the transformed version",
  "yeni / özgün": "new / original",
  "YENİ ALAN": "NEW AREA",
  "Alan tam olarak |determinant| katına çıkıyor.": "The area grows by exactly a factor of |determinant|.",
  "DETERMİNANT NE ANLATIYOR": "WHAT THE DETERMINANT TELLS YOU",
  "Determinant pozitif: yön korundu.": "The determinant is positive: the orientation is preserved.",
  "görülen görev": "seen task",
  "çapraz entropi": "cross entropy",
  "Eğitim yok. Soru gelince tüm veriye bakar, en yakın k komşuya oy verdirir.": "No training. When a question arrives it looks at all the data and lets the nearest k neighbours vote.",
  "DOĞRULUK": "ACCURACY",
  "çıktı": "output",
  "GERÇEK": "TRUTH",
  "ı": "i",
  "sayı": "number",
  "çalışma": "study",
  "Girdileri ağırlıklarla çarpar, toplar, bir eşikten geçirir. Sinir ağının tek yapıtaşı.": "It multiplies the inputs by weights, sums them and passes them through a threshold. The single building block of a neural network.",
  "önceki": "previous",
  "TEK NÖRON": "A SINGLE NEURON",
  "VERİ": "DATA",
  "AKTİVASYON": "ACTIVATION",
  "ÇIKTI": "OUTPUT",
  "◎ yanlış": "◎ wrong",
  "● sınıf A": "● class A",
  "● sınıf B": "● class B",
  "BAŞLANGIÇTAKİ DEĞER": "THE STARTING VALUE",
  "bölüm": "episode",
  "görülmeyen görev": "unseen task",
  "ÖDÜL SİNYALİ ULAŞAN HÜCRE": "CELLS THE REWARD SIGNAL REACHED",
  "ÖĞRENİLEN POLİTİKA": "THE LEARNED POLICY",
  "öğrenirken kaç kez kazandı": "how often it won while learning",
  "polinom + ölçekleme": "polynomial + scaling",
  "Q-ÖĞRENME · ÖDÜLLE ÖĞRENMEK": "Q-LEARNING · LEARNING FROM REWARD",
  "Sınıflandırma = uzayı ikiye bölen bir çizgi çizmek.": "Classification = drawing a line that splits the space in two.",
  "\"Kahvaltıda genellikle ___\"  ·  model olasılık verir, seçimi SEN ayarlarsın.": "\"For breakfast usually ___\"  ·  the model gives probabilities and YOU tune the choice.",
  "çay": "tea",
  "ÇEŞİTLİLİK": "DIVERSITY",
  "en olası": "most likely",
  "ham olasılık (soluk)  ·  filtrelenmiş ve yeniden normalize (parlak)": "raw probability (faint)  ·  filtered and renormalised (bright)",
  "olasılığı": "probability",
  "ÖRNEKLEME  ·  bir sonraki token nasıl seçilir": "SAMPLING  ·  how the next token is chosen",
  "reçel": "jam",
  "test hatası": "test error",
  "polinom özellikler": "polynomial features",
  "ALGORİTMA": "ALGORITHM",
  "Aynı problem, aynı test kümesi. Değişen sadece hangi kaldıracı çektiğin.": "The same problem, the same test set. The only difference is which lever you pull.",
  "KALDIRAÇLARI TEK TEK ÇEKİNCE": "PULLING THE LEVERS ONE BY ONE",
  "log₁₀ eğitim turu": "log₁₀ training rounds",
  "log₁₀ test hatası": "log₁₀ test error",
  "TEMELE GÖRE KAZANÇ": "GAIN OVER THE BASELINE",
  "ÜÇ KALDIRAÇ · VERİ, HESAP, ALGORİTMA": "THREE LEVERS · DATA, COMPUTE, ALGORITHM",
  "ÜÇÜ BİRDEN": "ALL THREE AT ONCE",
  "çünkü": "because",
  "meraklıydı": "was curious",
  "AYNI BÜTÇE, İKİ ESNEKLİK BİÇİMİ": "THE SAME BUDGET, TWO FORMS OF FLEXIBILITY",
  "BU EĞRİNİN ORTALAMA KARE HATASI": "THE MEAN SQUARED ERROR OF THIS CURVE",
  "EN KÖTÜ SAPMA": "WORST DEVIATION",
  "Global polinom derece yükseltir, spline düğüm ekler. Parametre sayısı eşit.": "A global polynomial raises its degree, a spline adds knots. The parameter count is equal.",
  "parametre sayısı": "number of parameters",
  "yoğunluk": "density",
  "+ artık": "+ residual",
  "ADIMDAN SONRA GERÇEK f": "THE TRUE f AFTER THE STEP",
  "buradayız": "we are here",
  "değer": "value",
  "EĞİTİM ÖRNEĞİ": "TRAINING EXAMPLES",
  "gerçek": "truth",
  "GERÇEK EN KÜÇÜK NOKTA": "THE TRUE MINIMUM",
  "gerçek f(x)": "true f(x)",
  "Gradyan inişi \"buradan sonrası düz\" varsayar. Adım büyüdükçe bu varsayım çöker.": "Gradient descent assumes \"it is flat from here on\". That assumption collapses as the step grows.",
  "haftalık çalışma saati": "weekly study hours",
  "ölçekli": "scaled",
  "sınav puanı": "exam score",
  "TAHMİN HATASI": "PREDICTION ERROR",
  "YEREL YAKLAŞIM · TAYLOR": "LOCAL APPROXIMATION · TAYLOR",
  "■ sınıf A": "■ class A",
  "■ sınıf B": "■ class B",
  "BU YÖNDE DOĞRULUK": "ACCURACY IN THIS DIRECTION",
  "CANLIDA ÖLÇEBİLİRSİN · sadece girdiler": "MEASURABLE IN PRODUCTION · inputs only",
  "CANLIDA ÖLÇEMEZSİN · etiket yok": "NOT MEASURABLE IN PRODUCTION · no labels",
  "DAĞILIM KAYMASI": "DISTRIBUTION SHIFT",
  "doğruluk %": "accuracy %",
  "doğrusal yaklaşım (teğet)": "linear approximation (tangent)",
  "DOĞRUSAL YAKLAŞIMIN TAHMİNİ": "THE LINEAR APPROXIMATION'S PREDICTION",
  "FISHER ÖLÇÜSÜ J": "FISHER MEASURE J",
  "FISHER: SINIFLARI AYIRAN YÖN": "FISHER: THE DIRECTION THAT SEPARATES THE CLASSES",
  "gerçek kural (eğri)": "the true rule (curve)",
  "Katsayılar sıfıra doğru ÇEKİLİR ama sıfır olmaz.": "The coefficients are PULLED towards zero but never become zero.",
  "kayma miktarı": "amount of shift",
  "Model bir satır bile değişmedi. Değişen tek şey, gelen verinin nereden geldiği.": "Not a single line of the model changed. The only thing that changed is where the incoming data comes from.",
  "modelin sınırı (doğru)": "the model's boundary (line)",
  "soluk = eğitim · parlak = canlı": "faint = training · bright = production",
  "top-k  kapalı": "top-k  off",
  "Veriyi tek bir yöne indireceğiz. Hangi yön? En çok yayılan mı, en iyi ayıran mı?": "We will reduce the data to a single direction. Which one? The one that spreads most or the one that separates best?",
  "yazı tura seviyesi": "coin flip level",
  "yön (derece)": "direction (degrees)",
  "yön üstündeki konum": "position along the direction",
  "■ dolandırıcılık": "■ fraud",
  "AĞIRLIK İLKLEME · SİNYAL KATMAN KATMAN": "WEIGHT INITIALISATION · THE SIGNAL LAYER BY LAYER",
  "BAŞLANGIÇ ÖLÇEĞİ": "INITIAL SCALE",
  "doğru geçen": "correctly passed",
  "DOĞRULUK NEDEN YALAN SÖYLER": "WHY ACCURACY LIES",
  "dolandırıcı": "fraudulent",
  "dolandırıcılık": "fraud",
  "eşik": "threshold",
  "KAÇAN": "MISSED",
  "Kapı doğrusal olduğu için ÇAPRAZ kesebilir. CART merdiven yapmak zorundaydı.": "Because the gate is linear it can cut DIAGONALLY. CART had to build a staircase.",
  "KATMAN BAŞINA ORAN": "RATIO PER LAYER",
  "Katsayılar sıfıra ÇARPILIR, model özellik seçer.": "The coefficients are SLAMMED to zero and the model selects features.",
  "KESİNLİK (precision)": "PRECISION",
  "METRİKLER": "METRICS",
  "MODELİN DEDİĞİ": "WHAT THE MODEL SAID",
  "SKOR DAĞILIMI": "SCORE DISTRIBUTION",
  "top-p  kapalı": "top-p  off",
  "yakalama oranı": "recall",
  "yanlış alarm": "false alarm",
  "yanlış alarm oranı": "false alarm rate",
  "ağırlık normu ‖W‖": "weight norm ‖W‖",
  "AŞIRI UYUM ve DÜZENLİLEŞTİRME": "OVERFITTING AND REGULARISATION",
  "doğrulama": "validation",
  "KLASİK KARAR AĞACI": "A CLASSICAL DECISION TREE",
  "BAĞLAM": "CONTEXT",
  "ETİKET SAYISI": "NUMBER OF LABELS",
  "öğretmen": "teacher",
  "(uzak−yakın)/yakın": "(far−near)/near",
  "BOYUT LANETİ": "THE CURSE OF DIMENSIONALITY",
  "EN UZAK KOMŞU, EN YAKININDAN KAÇ KAT UZAK": "HOW MANY TIMES FURTHER THE FURTHEST NEIGHBOUR IS THAN THE NEAREST",
  "noktaların bu kadarı kenara yapışık": "this share of the points is stuck to the edge",
  "sağlıklı": "healthy",
  "sorgu noktasına uzaklık": "distance to the query point",
  "AYNI SÜREÇTEN İKİ AYRI ÖRNEKLEM": "TWO SEPARATE SAMPLES FROM THE SAME PROCESS",
  "en büyük / en küçük eğrilik": "largest / smallest curvature",
  "hatırlama": "recall",
  "HESSIAN · VADİNİN ŞEKLİ": "THE HESSIAN · THE SHAPE OF THE VALLEY",
  "İKİ ÖRNEKLEM ARASI FARK (w₁)": "DIFFERENCE BETWEEN THE TWO SAMPLES (w₁)",
  "İki yön, iki farklı eğrilik. Gradyan inişi dar yönde titrerken geniş yönde sürünüyor.": "Two directions, two different curvatures. Gradient descent oscillates in the narrow direction while crawling in the wide one.",
  "KOŞUL SAYISI": "CONDITION NUMBER",
  "KOŞUL SAYISI κ": "CONDITION NUMBER κ",
  "örneklem A": "sample A",
  "örneklem B": "sample B",
  "Tek adımda kapalı çözüm. Ama XᵀX tersi alınamaz hale gelirse ne olur?": "A closed form solution in a single step. But what if XᵀX becomes impossible to invert?",
  "BU STRATEJİ": "THIS STRATEGY",
  "Değişken: sütun. Alan: satırlar. Kısıt: aynı satır ya da köşegen olmasın.": "Variable: a column. Domain: the rows. Constraint: not the same row or diagonal.",
  "GERİ DÖNÜŞ": "BACKTRACK",
  "GERİ İZLEMEYE GÖRE": "COMPARED WITH BACKTRACKING",
  "hiç kısıt kullanmadan": "using no constraints at all",
  "İzmir": "Izmir",
  "kaç kat az": "times fewer",
  "KISIT TATMİN · N-VEZİR": "CONSTRAINT SATISFACTION · N-QUEENS",
  "kısıtlar aramayı budayınca": "when the constraints prune the search",
  "■ yanlılık²": "■ bias²",
  "hata bileşeni": "error component",
  "kraliçe": "queen",
  "● eğitim": "● training",
  "BPE TOKENİZASYON": "BPE TOKENISATION",
  "En sık geçen karakter çiftlerini birleştire birleştire alt-kelime sözlüğü kurar.": "It builds a sub-word vocabulary by merging the most frequent character pairs over and over.",
  "İstanbul": "Istanbul",
  "kitaplarımızdan": "kitaplarımızdan",
  "öğrenilen birleşme sayısı": "number of merges learned",
  "ÖĞRENİLEN BİRLEŞMELER (sırayla)": "THE MERGES LEARNED (in order)",
  "token sayısı": "number of tokens",
  "BAŞABAŞ HACİM": "BREAK-EVEN VOLUME",
  "İKİ FARKLI MALİYET ŞEKLİ": "TWO DIFFERENT COST SHAPES",
  "kadın": "woman",
  "■ eğitim hatası (ayrı ölçek, hep düşüyor)": "■ training error (separate scale, always falling)",
  "■ ızgara": "■ grid",
  "■ log kanıt": "■ log evidence",
  "bağlamdaki örnek sayısı": "number of examples in the context",
  "BU DERECENİN LOG KANITI": "THE LOG EVIDENCE OF THIS DEGREE",
  "BULUNAN EN İYİ SKOR": "BEST SCORE FOUND",
  "deneme bütçesi": "trial budget",
  "derece arttıkça hep düşer": "it always falls as the degree rises",
  "Doğrulama kümesi yok. Model karmaşıklığını verinin kendisi seçiyor.": "There is no validation set. The data itself chooses the model complexity.",
  "EĞİTİM HATASI": "TRAINING ERROR",
  "en iyi bölge": "the best region",
  "HİPERPARAMETRE ARAMASI": "HYPERPARAMETER SEARCH",
  "İki ayar var ama sadece biri sonucu belirliyor. Bütçeni nasıl harcarsın?": "There are two settings but only one determines the result. How do you spend your budget?",
  "KANITIN ZİRVESİ": "THE PEAK OF THE EVIDENCE",
  "log kanıt": "log evidence",
  "ÖNEMLİ ayar": "the setting that MATTERS",
  "ÖNEMLİ AYARDA KAÇ FARKLI DEĞER": "HOW MANY DISTINCT VALUES ON THE SETTING THAT MATTERS",
  "önemsiz ayar": "the setting that does not matter",
  "■ ÖNBELLEKLİ": "■ WITH CACHE",
  "■ ÖNBELLEKSİZ": "■ WITHOUT CACHE",
  "API FİYATI": "API PRICE",
  "aylık token hacmi": "monthly token volume",
  "KV CACHE BELLEĞİ  (GB)": "KV CACHE MEMORY  (GB)",
  "Üretilen her token için tüm geçmişi yeniden hesaplamak yerine, K ve V'yi sakla.": "Instead of recomputing the whole history for every token generated, store K and V.",
  "üretilen token": "tokens generated",
  "ÜRETİM MALİYETİ": "GENERATION COST",
  "ağırlık başına bit": "bits per weight",
  "BELİRSİZLİK · VERİ NOKTASINDA": "UNCERTAINTY · AT A DATA POINT",
  "BİT": "BITS",
  "çocuk": "child",
  "en büyük": "largest",
  "GAUSSIAN PROCESS · BELİRSİZLİĞİNİ SÖYLEYEN MODEL": "GAUSSIAN PROCESS · A MODEL THAT STATES ITS UNCERTAINTY",
  "GP ortalaması": "GP mean",
  "model nerede bilmediğini biliyor": "the model knows where it does not know",
  "Tek bir sayı değil, bir dağılım. Bant daraldıkça model emin, açıldıkça bilmiyor.": "Not a single number but a distribution. The narrower the band the more confident the model, the wider the less it knows.",
  "\"kitaplarımızdan\" nasıl parçalanıyor?": "how is \"kitaplarımızdan\" split up?",
  "−∇L gideceğimiz yön": "−∇L the direction we go",
  "■ lojistik regresyon · ayırıcı": "■ logistic regression · discriminative",
  "■ naive Bayes · üretici": "■ naive Bayes · generative",
  "Aynı veri, iki felsefe. Hangisi kazanır? Cevap elindeki veri miktarına bağlı.": "The same data, two philosophies. Which wins? The answer depends on how much data you have.",
  "eğitim örneği (log ölçek)": "training examples (log scale)",
  "LOJİSTİK REGRESYON · ayırıcı": "LOGISTIC REGRESSION · discriminative",
  "NAIVE BAYES · üretici": "NAIVE BAYES · generative",
  "test doğruluğu %": "test accuracy %",
  "ÜRETİCİ ve AYIRICI": "GENERATIVE AND DISCRIMINATIVE",
  "○ destek vektörü": "○ support vector",
  "● şehir": "● city",
  "Ankara Üniversitesi'nden": "from Ankara University",
  "Boğaziçi Üniversitesi'nden": "from Bogazici University",
  "Bu kişi hakkında bilgim yok.": "I have no information about this person.",
  "destek vektörü": "support vectors",
  "Doğrusal bir skor üretir, sigmoid ile olasılığa çevirir, çapraz entropi ile eğitilir.": "It produces a linear score, turns it into a probability with a sigmoid, and is trained with cross entropy.",
  "doygun nöron": "saturated neurons",
  "EVAL SETİ · kaç örnek yeterli?": "EVAL SET · how many examples are enough?",
  "gözlenen doğruluk": "observed accuracy",
  "HALÜSİNASYON NEDEN OLUYOR?": "WHY DOES HALLUCINATION HAPPEN?",
  "Her katmanda aktivasyonları yeniden ölçekler. Başlangıç ağırlıkları ne olursa olsun dağılım sabit kalır.": "It rescales the activations at every layer. Whatever the initial weights, the distribution stays fixed.",
  "Hiç etiket verilmedi. Model kategorileri sadece BİRLİKTE GEÇMEDEN öğrendi.": "No labels were given. The model learned the categories from CO-OCCURRENCE alone.",
  "İstanbul Teknik Üniversitesi'nden": "from Istanbul Technical University",
  "kategori DIŞI ortalama kosinüs": "mean cosine ACROSS categories",
  "kategori İÇİ ortalama kosinüs": "mean cosine WITHIN a category",
  "KATMAN KATMAN DAĞILIM": "THE DISTRIBUTION LAYER BY LAYER",
  "KAZANÇ": "GAIN",
  "KELİME GÖMMELERİ": "WORD EMBEDDINGS",
  "kötü": "bad",
  "LOJİSTİK REGRESYON": "LOGISTIC REGRESSION",
  "marj genişliği": "margin width",
  "Model \"doğru ol\" diye eğitilmedi. \"Bir sonraki tokenı tahmin et\" diye eğitildi.": "The model was not trained to \"be correct\". It was trained to \"predict the next token\".",
  "Negatif çıktıları sıfırladığı için varyans her": "Because it zeroes the negative outputs, the variance",
  "ODTÜ'den": "from METU",
  "OLASILIK HARİTASI": "PROBABILITY MAP",
  "ÖRNEK SAYISI  →  ARALIK GENİŞLİĞİ": "NUMBER OF EXAMPLES  →  WIDTH OF THE INTERVAL",
  "ReLU SİNYALİN YARISINI ATIYOR": "ReLU THROWS AWAY HALF THE SIGNAL",
  "Sadece ayırmakla yetinmez, iki sınıf arasındaki BOŞLUĞU en geniş yapmaya çalışır.": "It is not content with separating; it tries to make the GAP between the two classes as wide as possible.",
  "sarı bant = marj": "yellow band = the margin",
  "∇L yokuş YUKARI": "∇L UPHILL",
  "ÇOK BAŞLI DİKKAT": "MULTI-HEAD ATTENTION",
  "KESİŞİM": "CROSSING",
  "olgunun yaşı (kaç tur önce söylendi)": "age of the fact (how many turns ago it was said)",
  "ŞİŞME": "INFLATION",
  "Tek bir dikkat yetmez. Paralel başlar farklı ilişki türlerini aynı anda izler.": "One attention is not enough. Parallel heads track different kinds of relation at the same time.",
  "katman sayısı": "number of layers",
  "yaklaşım artık geçersiz": "the approximation is no longer valid",
  "AÇILAN HÜCRE": "CELLS EXPANDED",
  "Algoritma sadece noktaların yerini biliyor.": "The algorithm only knows where the points are.",
  "arasındaki bağ kopuyor ve bunu fark etmek zor.": "breaks down, and that is hard to notice.",
  "artı: gerçek konu merkezleri": "crosses: the true topic centres",
  "Dört gerçek konu var. Kümeleme etiketleri görmüyor, sadece gömmeleri görüyor.": "There are four true topics. Clustering does not see the labels, only the embeddings.",
  "Harita biliniyor. Soru öğrenmek değil, en az hücreyi açarak en kısa yolu bulmak.": "The map is known. The question is not to learn but to find the shortest path expanding the fewest cells.",
  "Konu diye bir kavramı yok; sadece birbirine": "It has no concept of a topic; it only gathers",
  "KONU KEŞFİ · GÖMMELER VE KÜMELER": "TOPIC DISCOVERY · EMBEDDINGS AND CLUSTERS",
  "Konular üst üste bindikçe kümeler ile konular": "As the topics overlap, the link between the clusters and the topics",
  "KÜME SAYISI": "NUMBER OF CLUSTERS",
  "KÜMELEME ETİKET GÖRMÜYOR": "CLUSTERING DOES NOT SEE THE LABELS",
  "merkezler arası": "between centres",
  "OPTİMAL Mİ": "OPTIMAL?",
  "renk: kümeleme kararı": "colour: the clustering decision",
  "SİLUET": "SILHOUETTE",
  "test doğ.": "test acc.",
  "TRANSFER ÖĞRENME": "TRANSFER LEARNING",
  "yakın noktaları bir araya topluyor.": "nearby points together.",
  "DİZİ UZUNLUĞU": "SEQUENCE LENGTH",
  "Etiket yok. Model verideki grupları kendisi buluyor.": "No labels. The model finds the groups in the data by itself.",
  "k-MEANS KÜMELEME": "k-MEANS CLUSTERING",
  "ÖĞRENME  gözetimsiz": "LEARNING  unsupervised",
  "-, gerçek ilişki": "-, the true relationship",
  "(tipik dağılım, önce GETİRMEYİ ölç)": "(a typical distribution, measure RETRIEVAL first)",
  "⚠ DİKKAT": "⚠ CAUTION",
  "bağlam + soru → LLM": "context + question → LLM",
  "Çıkış izd.": "Out proj.",
  "deneme sayısı": "number of trials",
  "eşit": "equal",
  "GENİŞ UZAY": "WIDE SPACE",
  "getirme (vektör arama)": "retrieval (vector search)",
  "getirme hatası": "retrieval error",
  "Halüsinasyonu azaltmanın ana yolu: modele cevaplamadan önce doğru belgeleri ver.": "The main way to reduce hallucination: give the model the right documents before it answers.",
  "her parça → vektör (çok dilli model)": "every chunk → a vector (a multilingual model)",
  "hiç arama yok": "no search at all",
  "iki özellik neredeyse tek çizgi": "the two features are almost a single line",
  "karakter başına token": "tokens per character",
  "model doğruluğu": "model accuracy",
  "vektörler → vektör veritabanı (HNSW)": "vectors → a vector database (HNSW)",
  "◎ test (model bunları hiç görmedi)": "◎ test (the model never saw these)",
  "BAĞLAM İÇİ ÖĞRENME · AĞIRLIKLAR SABİT": "IN-CONTEXT LEARNING · THE WEIGHTS ARE FIXED",
  "Bağlamdaki örnek sayısı arttıkça tahmin iyileşiyor. Hiçbir ağırlık güncellenmiyor.": "The prediction improves as the number of examples in the context grows. No weight is updated.",
  "Bu iki sayı hiç değişmiyor. Değişen tek şey": "These two numbers never change. The only thing that changes",
  "DOĞRU POZİTİF": "TRUE POSITIVE",
  "görevi bilseydi": "if it knew the task",
  "Görülen görevde fazla kayıp sıfıra iniyor:": "On a seen task the excess loss falls to zero:",
  "Görülmeyen görevde bir tabanda takılıyor.": "On an unseen task it sticks at a floor.",
  "ICL, görevi bilen tahminciyi yakalıyor.": "ICL catches the predictor that knows the task.",
  "KÂHİN NLL": "ORACLE NLL",
  "kâhine göre fazla kayıp": "excess loss over the oracle",
  "KESİNLİK": "PRECISION",
  "POZİTİF ÇIKANLARIN İÇİNDE": "AMONG THOSE FLAGGED POSITIVE",
  "pozitifin ne kadarı doğru": "what share of the positives is correct",
  "temsildeki bağıl değişim": "relative change in the representation",
  "YANLIŞ POZİTİF": "FALSE POSITIVE",
  "⚠ KV cache modelin ağırlıklarından BÜYÜK, uzun bağlamın asıl maliyeti bu": "⚠ the KV cache is LARGER than the model's weights; that is the real cost of long context",
  "AÇIK MI KAPALI MI · BAŞABAŞ HACMİ": "OPEN OR CLOSED · THE BREAK-EVEN VOLUME",
  "AI PROJESİ KARARI · BAŞABAŞ DOĞRULUK": "AI PROJECT DECISION · BREAK-EVEN ACCURACY",
  "Altında API, üstünde kendi barındırma ucuz.": "Below it the API is cheaper, above it self hosting.",
  "Altında hiçbir model, hiçbir doğrulukla kâr etmez.": "Below it no model turns a profit at any accuracy.",
  "API doğrusal: hacimle birlikte artar, sıfırda": "The API is linear: it grows with the volume and at zero",
  "artık": "residual",
  "aşırı uyum: yanlılık küçük ama modeller birbirinden çok farklı": "overfitting: the bias is small but the models differ greatly from each other",
  "aylık": "monthly",
  "BAŞABAŞ NOKTASI KAPALI FORMDA": "THE BREAK-EVEN POINT IN CLOSED FORM",
  "BİR BLOKTAKİ PARAMETRE DAĞILIMI": "THE PARAMETER DISTRIBUTION IN ONE BLOCK",
  "BU HACİMDE API": "THE API AT THIS VOLUME",
  "BU HACİMDE KENDİ": "SELF HOSTING AT THIS VOLUME",
  "büyük C → dar marj, az destek vektörü, hataya tahammülsüz (aşırı uyum riski)": "large C → a narrow margin, few support vectors, no tolerance for error (a risk of overfitting)",
  "büyük model": "large model",
  "çalışma saati (x)": "study hours (x)",
  "çoğu görev için yeter": "enough for most tasks",
  "DEĞİŞİM": "CHANGE",
  "dolana kadar sabit, sonra GPU ekleyip zıplar.": "flat until it fills up, then it jumps as a GPU is added.",
  "GEREKEN DOĞRULUK": "ACCURACY REQUIRED",
  "günlük": "daily",
  "HATA EĞRİSİ": "ERROR CURVE",
  "HAVUZLAMA · KAYDIRMAYA DİRENÇ": "POOLING · RESISTANCE TO SHIFT",
  "HAVUZSUZ DEĞİŞİM": "CHANGE WITHOUT POOLING",
  "İMKÂNSIZLIK EŞİĞİ": "THE IMPOSSIBILITY THRESHOLD",
  "istek başı": "per request",
  "k'yı düşür, reranker koy": "lower k, add a reranker",
  "küçük model": "small model",
  "log₁₀ aylık maliyet": "log₁₀ monthly cost",
  "MALİYET ve GECİKME": "COST AND LATENCY",
  "MALİYETİ DÜŞÜRME SIRASI": "THE ORDER OF COST REDUCTION",
  "MSE nin cevabı": "MSE's answer",
  "MÜDAHALE MALİYETİ": "COST OF INTERVENTION",
  "olayın taban oranı (log)": "base rate of the event (log)",
  "ön-görev temsili": "pretext task representation",
  "SEÇİLİ MODEL": "SELECTED MODEL",
  "sıfırdır. Kendi barındırma basamaklı: kapasite": "is zero. Self hosting is stepped: capacity",
  "sınav puanı (y)": "exam score (y)",
  "sinyal söndü": "the signal died out",
  "taban bunun altında ise": "if the base rate is below this",
  "Taban oranı düştükçe gereken doğruluk hızla": "As the base rate falls the accuracy required rises",
  "TEK-SİMGE": "SINGLE-TOKEN",
  "test doğruluğu": "test accuracy",
  "Token başına ücret küçük görünür. Ölçekte hiç öyle değil.": "The price per token looks small. At scale it is not at all.",
  "TRANSFORMER BLOĞU": "A TRANSFORMER BLOCK",
  "turuncu: kendi barındırma": "orange: self hosting",
  "yıllık": "yearly",
  "alanı seçmek, en şanslı ölçüm hatasını seçmektir.": "the highest one is picking the luckiest measurement error.",
  "BİRİNCİ OLMAK BİR SEÇİM İŞLEMİDİR": "BEING FIRST IS AN ACT OF SELECTION",
  "BİRİNCİNİN SKORU": "THE LEADER'S SCORE",
  "Bu bir hile değil; hiç kimse yanlış bir şey yapmadı.": "This is not cheating; nobody did anything wrong.",
  "Bütün modeller aynı. Aralarından en yüksek skoru": "Every model is the same. Picking",
  "cezasız çözüm": "the unpenalised solution",
  "gözlenen skor": "observed score",
  "henüz sağlıklı, doğrulama kaybı hâlâ düşüyor": "still healthy, the validation loss is still falling",
  "hepsinde aynı": "the same in all of them",
  "ÖN EĞİTİM GÖREVİ": "PRETEXT TASK",
  "P(GEÇERLİ)": "P(VALID)",
  "Sadece en yüksek sayı seçildi ve o sayı sapmalı.": "The highest number was simply picked, and that number is biased.",
  "SKOR TABLOSU · KAZANANIN SKORU ŞİŞMİŞTİR": "LEADERBOARD · THE WINNER'S SCORE IS INFLATED",
  "skor tablosundaki model sayısı": "number of models on the leaderboard",
  "yaklaşım hâlâ geçerli": "the approximation is still valid",
  "yeni görevden örnek sayısı": "number of examples from the new task",
  "BN OLMADAN: NÖRONLAR DOYUYOR": "WITHOUT BN: THE NEURONS SATURATE",
  "ÇAĞIR": "CALL",
  "değerlendirme": "evaluation",
  "DÜŞÜN": "THINK",
  "GÖZLEM": "OBSERVE",
  "kapı çıktısı  =  sağ dala gitme ağırlığı": "gate output  =  the weight of going to the right branch",
  "ÖRNEK SAYISI": "NUMBER OF EXAMPLES",
  "x  (özelliğin değeri)": "x  (the feature's value)",
  "en küçük": "smallest",
  "EZBERLEYEN, en yakın kaydı söyler": "MEMORISING, it returns the nearest record",
  "karşılaştırma": "comparison",
  "KLASİK ML": "CLASSICAL ML",
  "KURAL ÖĞRENEN, formül uygular": "RULE LEARNING, it applies a formula",
  "AÇI": "ANGLE",
  "aday eşik": "candidate threshold",
  "ağırlıklı çocuk Gini": "weighted child Gini",
  "AI MÜH.": "AI ENG.",
  "AI MÜHENDİSLİĞİ vs KLASİK ML · EMEK NEREYE GİDİYOR": "AI ENGINEERING vs CLASSICAL ML · WHERE THE EFFORT GOES",
  "ARADAKİ FARK": "THE DIFFERENCE",
  "Aynı problemi iki farklı çalışma biçimiyle çözerken emeğin dağılımı.": "How the effort is distributed when solving the same problem in two different ways.",
  "bağlam": "context",
  "BÖLÜNME NASIL SEÇİLİR?": "HOW IS A SPLIT CHOSEN?",
  "dağıtım": "deployment",
  "doğal dil": "natural language",
  "eğitimi": "training",
  "emek payı (%)": "share of effort (%)",
  "Gini kazancı": "Gini gain",
  "Her aday eşik denenir, Gini kazancı hesaplanır, en büyüğü kazanır.": "Every candidate threshold is tried, the Gini gain is computed, and the largest wins.",
  "İngilizce": "English",
  "kayıt / izleme": "logging / monitoring",
  "KAZANÇ = ebeveyn − çocuk": "GAIN = parent − children",
  "mühendisliği": "engineering",
  "özellik": "feature",
  "SEÇİLİ AŞAMA": "SELECTED STAGE",
  "tanımı": "definition",
  "tasarımı": "design",
  "Türkçe": "Turkish",
  "yeşil: AI mühendisliği": "green: AI engineering",
  "✓ değme noktası KÖŞEDE, bir katsayı tam sıfır": "✓ the touch point is at a CORNER, one coefficient is exactly zero",
  "ağaç derinliği": "tree depth",
  "aynı veri, test R²": "the same data, test R²",
  "bağlam kurma": "context building",
  "çıktı doğrulama": "output validation",
  "doğrudan cevap": "direct answer",
  "DOĞRUSAL MODEL": "LINEAR MODEL",
  "düşünme zinciri": "chain of thought",
  "düz: modelin bulduğu": "solid: what the model found",
  "eğitim R²": "training R²",
  "giriş / yetkilendirme": "auth / authorisation",
  "kesikli: gerçek şekil": "dashed: the true shape",
  "model çağrısı": "model call",
  "TOPLAMSAL MODEL · GERİ-UYDURMA": "ADDITIVE MODEL · BACKFITTING",
  "y = a₀ + f₁(x₁) + f₂(x₂). Her eğri, diğerinin artığına uyduruluyor.": "y = a₀ + f₁(x₁) + f₂(x₂). Every curve is fitted to the residual of the other.",
  "YANLIŞ ALARM f": "FALSE ALARM f",
  "| artık (hata)": "| residual (error)",
  "● gerçek": "● truth",
  "adım sayısı": "number of steps",
  "Ağaç yalnızca EKSEN-HİZALI kesebilir. Çapraz sınırı merdivenle yaklaşır.": "A tree can only cut AXIS ALIGNED. It approximates a diagonal boundary with a staircase.",
  "AĞAÇ YAPISI": "TREE STRUCTURE",
  "ağırlık başına": "per weight",
  "AI YIĞINI · GECİKME NEREYE GİDİYOR": "THE AI STACK · WHERE THE LATENCY GOES",
  "ARAMA ÖNCE VARSAYILANI YAKALAMALI": "THE SEARCH HAS TO CATCH THE DEFAULT FIRST",
  "artık kuantalama değil, model değiştirme oluyor.": "it stops being quantisation and becomes changing the model.",
  "Asıl soru \"hangisi daha iyi\" değil, \"kaç etiket": "The real question is not \"which is better\" but \"how many labels",
  "AUTOML · GENİŞ UZAYDA RASTGELE ARAMA": "AUTOML · RANDOM SEARCH IN A WIDE SPACE",
  "belirsizlik örneklemesi": "uncertainty sampling",
  "bilmiyor. Özet her yaşta bir şans veriyor ama": "does not know. The summary gives a chance at every age but",
  "Çünkü uzayın çoğu kötü ve rastgele seçim onlara": "Because most of the space is bad and random selection lands",
  "dağınık": "scattered",
  "DOĞRUDAN": "DIRECT",
  "dünkü olgu aynı olasılıkla geliyor.": "yesterday's fact comes back with the same probability.",
  "düşüyor.": "on them.",
  "Eğitilmiş ağın ağırlıkları n bitle yeniden yazılıyor. Ağ yeniden eğitilmiyor.": "The weights of a trained network are rewritten with n bits. The network is not retrained.",
  "eğitim örneği": "training examples",
  "eklenen ağaç sayısı": "number of trees added",
  "eklenen düzeltme": "the correction added",
  "EN İYİSİ": "THE BEST",
  "etiket bütçesi": "label budget",
  "etiketli örnek sayısı": "number of labelled examples",
  "GETİRME · GENEL": "RETRIEVAL · OVERALL",
  "HATA ARTIŞI": "ERROR INCREASE",
  "Her yeni kütük, önceki modelin KALAN hatasına uyar. Hatalar birikerek erir.": "Every new stump fits the REMAINING error of the previous model. The errors melt away as they accumulate.",
  "KAÇ BİLEŞEN YETER?": "HOW MANY COMPONENTS ARE ENOUGH?",
  "kanal bazında": "per channel",
  "KARAR AĞACI  ·  CART": "DECISION TREE  ·  CART",
  "KARAR BÖLGELERİ  ·  ◎ hatalı": "DECISION REGIONS  ·  ◎ misclassified",
  "KONUŞMA HAFIZASI · ÜÇ STRATEJİ YAN YANA": "CONVERSATION MEMORY · THREE STRATEGIES SIDE BY SIDE",
  "KUANTİZASYON · KAÇ BİT YETİYOR": "QUANTISATION · HOW MANY BITS ARE ENOUGH",
  "KÜÇÜK MODEL": "SMALL MODEL",
  "kümülatif varyans": "cumulative variance",
  "LLM BİR TABAN ÇİZGİSİDİR": "AN LLM IS A BASELINE",
  "LLM in doğruluğu etiket sayısından bağımsız:": "The LLM's accuracy is independent of the number of labels:",
  "LLM SINIFLANDIRICI · NE ZAMAN KÜÇÜK MODELE GEÇMELİ": "LLM CLASSIFIER · WHEN TO SWITCH TO A SMALL MODEL",
  "LLM veri miktarından bağımsız sabit. Küçük model etiketle öğreniyor.": "The LLM is flat regardless of the amount of data. The small model learns from the labels.",
  "MODEL ÇAĞRISININ PAYI": "THE MODEL CALL'S SHARE",
  "öğrenci": "student",
  "ÖZET · GENEL": "SUMMARY · OVERALL",
  "SEKİZ BİT NEREDEYSE BEDAVA": "EIGHT BITS IS ALMOST FREE",
  "SIFIR ATIŞLI LLM": "ZERO-SHOT LLM",
  "sıfır atışlıyı geçtiği": "it passes zero-shot",
  "ŞEKİLLER FARKLI, SAYILAR KARŞILAŞTIRILABİLİR": "THE SHAPES DIFFER, THE NUMBERS ARE COMPARABLE",
  "tensör bazında": "per tensor",
  "Uzun konuşmada tek ölçeklenen strateji bu.": "In a long conversation this is the only strategy that scales.",
/*SON*/
};
